<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/results.js'));
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $episode Logs_Model_Episode */
$episode = $this->episode;
/* @var $participants Story_Model_Charakter */
$participants = $this->participants;
/* @var $skill Story_Model_Skill */
?>
<h1>Review der Episode <?= $episode->getName() ?></h1>
<hr />
<h2>
    Beschreibung der Episode
</h2>
<div>
    <?= $purifier->purify($episode->getBeschreibung()) ?>
</div>
<h2>
    Ausgang der Episode
</h2>
<div>
    <?= $purifier->purify($episode->getZusammenfassung()) ?>
</div>
<h2>
    Logs
</h2>
<div>
    <a href="<?= $this->baseUrl() ?>/Logs/review/gesamtlog/episode/<?= $episode->getId() ?>">
        Alle Logs herunterladen
    </a>
    <?php foreach($this->logs as $log): ?>
    <a href="<?= $this->baseUrl() ?>/Logs/review/download/episode/<?= $episode->getId() ?>/log/<?= $log->getId() ?>">
        <div class="documentList">
            <p>
                <span>
                    Download: <?= $purifier->purify($log->getName()) ?>
                </span>
            </p>
            <p>
                <?= $purifier->purify($log->getBeschreibung()) ?>
            </p>
        </div>
    </a>
    <?php endforeach; ?>
</div>
<h2>Eintragungen für die teilnehmenden Charaktere</h2>
<div id="auswertung" data-id="<?= $episode->getId() ?>">
    <?php
    foreach($participants as $charakter):
        $charakterId = $charakter->getCharakterId();
        $result = $charakter->getResult();

        $charakterKills = '';
        if (count($result->getCharaktersKilled()) > 0) {
            foreach ($result->getCharaktersKilled() as $kill) {
                $charakterKills .= $kill->getVorname() . ' ' . $kill->getNachname() . ', ';
            }
            $charakterKills = substr($charakterKills, 0, strlen($charakterKills) - 2);
        }
    ?>
    <fieldset>
        <legend>Charakter: <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?></legend>
        <div>
            <div style="display: inline-block; width: 30%; vertical-align: top">
                <p>
                    Hat <?= $result->getKillNpcs() ?> NPCs getötet.
                </p>
                <?php if($result->getDied()): ?>
                <p style="font-weight: bold; color: red;">
                    Ist in dieser Episode gestorben.
                </p>
                <?php endif; ?>
            </div>
        </div>
        <div>
            Bemerkungen vom Spielleiter zum Charakter:
            <p>
                <?= $result->getComment() !== '' ? $purifier->purify($result->getComment()) : 'Keine' ?>
            </p>
        </div>
        <div>Besondere Leistungen:</div>
        <?php foreach ($result->getAchievementsToAdd() as $achievement): ?>
        <div>
            <p style="font-weight: bold"><?= $purifier->purify($achievement->getTitle()) ?> (hinzugefügt)</p>
            <p><?= $purifier->purify($achievement->getDescription()) ?></p>
        </div>
        <?php endforeach; ?>
        <?php foreach ($result->getAchievementsToRemove() as $achievement): ?>
        <div>
            <p style="font-weight: bold"><?= $purifier->purify($achievement->getTitle()) ?> (entfernt)</p>
            <p><?= $purifier->purify($achievement->getDescription()) ?></p>
        </div>
        <?php endforeach; ?>

        <fieldset>
            <legend>Fähigkeiten, Magien, Items</legend>
            <div>
                <div style="display: inline-block; width: 50%; vertical-align: top;">
                    Gelernte Fähigkeiten: <?= $purifier->purify($result->getSkillsToAddString()) ?>
                </div>
                <div style="display: inline-block; width: 40%; vertical-align: top;">
                    Verlernte Fähigkeiten: <?= $purifier->purify($result->getSkillsToRemoveString()) ?>
                </div>
            </div>
            <div>
                <div style="display: inline-block; width: 50%; vertical-align: top;">
                    Gelernte Magien: <?= $purifier->purify($result->getMagicToAddString()) ?>
                </div>
                <div style="display: inline-block; width: 40%; vertical-align: top;">
                    Verlernte Magien: <?= $purifier->purify($result->getMagicToRemoveString()) ?>
                </div>
            </div>
            <div>
                <div style="display: inline-block; width: 50%; vertical-align: top;">
                    Neue Items: <?= $purifier->purify($result->getItemsToAddString()) ?>
                </div>
                <div style="display: inline-block; width: 40%; vertical-align: top;">
                    Verlorene Items: <?= $purifier->purify($result->getItemsToRemoveString()) ?>
                </div>
            </div>
        </fieldset>
        <?php if ($charakterKills !== '') : ?>
        <fieldset>
            <legend>Getötete Spielercharaktere</legend>
            <?= $purifier->purify($charakterKills) ?>
        </fieldset>
        <?php endif; ?>
    </fieldset>
    <?php endforeach; ?>
</div>
<h2>Deine Bewertung</h2>
<div>
    <form method="post" action="<?= $this->baseUrl() ?>/Logs/review/review">
        <p>
            <label for="isAccepted">Episode akzeptieren?</label>
            <select name="isAccepted" id="isAccepted">
                <option value="">Bitte auswählen</option>
                <option value="0">Nein</option>
                <option value="1">Ja</option>
            </select>
        </p>
        <p>
            <label for="feedback">Feedback zur Episode:</label><br />
            <textarea name="feedback" id="feedback" rows="10" cols="96"></textarea>
        </p>
        <input type="hidden" name="episodenId" value="<?= $episode->getId() ?>" />
        <input type="submit" value="Bewertung absenden" />
    </form>
</div>