<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/story.css');
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$participantsReady = $this->participantsReady;
$participantsPending = $this->participantsPending;
/* @var $episode Story_Model_Episode */
$episode = $this->episode;
$charakterId = $this->layoutData->getCharakter()->getCharakterId();
?>
<h2>Status: <?= $episode->getName() ?></h2>
<div>
    <a href="<?= $this->baseUrl() ?>/Story/plots/show/id/<?= $episode->getPlotId() ?>">
        Zurück zum Plot
    </a>
</div>
<hr />
<div>
    <?php if($episode->getStatus()->getId() <= 2){ ?>
    <div>
        <fieldset id="inviteList">
            <legend>Offen</legend>
            <div>
                <ul>
                    <?php foreach($participantsPending as $charakter): ?>
                    <li class="listRow" >
                        <span class="charaktername">
                            <?= $purifier->purify($charakter->getVorname() . ' '  . $charakter->getNachname()) ?>
                        </span>
                        <?php if($charakterId === $charakter->getCharakterId()): ?>
                        <span class="rowForm">
                            <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/ready">
                                <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
                                <input type="submit" value="Bereit">
                            </form>
                        </span>
                        <?php endif; ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </fieldset>
        <fieldset id="participantList">
            <legend>Bereit zum Start</legend>
            <div>
                <ul>
                    <?php foreach($participantsReady as $charakter): ?>
                    <li class="listRow" >
                        <span class="charaktername">
                            <?= $purifier->purify($charakter->getVorname() . ' '  . $charakter->getNachname()) ?>
                        </span>
                        <?php if($charakterId === $charakter->getCharakterId()): ?>
                        <span class="rowForm">
                            <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/unready">
                                <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
                                <input type="submit" value="Nicht Bereit">
                            </form>
                        </span>
                        <?php endif; ?>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </fieldset>
    </div>
    <?php } else { ?>
    <fieldset>
        <legend>Mitspieler</legend>
        <?php foreach($participantsReady as $charakter): ?>
        <div style="margin: 3px; display: inline-block">
            <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
        </div>
        <?php endforeach; ?>
    </fieldset>
    <?php } ?>
    <fieldset>
        <legend>Beschreibung</legend>
        <div>
            <?= $purifier->purify($episode->getBeschreibung()) ?>
        </div>
    </fieldset>
</div>