<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/editor.js'));
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $episode Story_Model_Episode */
$episode = $this->episode;
?>
<div class="row">
    <div class="col">
        <h1 class="fs-1">Abschluss: <?= $episode->getName() ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-2">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/Story/plots/sl/id/<?= $episode->getPlotId() ?>">
            Zurück zum Plot
        </a>
    </div>
    <div class="col-2">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/Story/episoden/review/episode/<?= $episode->getId() ?>">
            Episode bearbeiten
        </a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-12">
        <h3 class="fs-3">
            Zusammenfassung der Episode
        </h3>
        <p class="text-muted">
            Nach dem Abschluss einer Episode, wird sie für die Logleser freigegeben.
        </p>
    </div>
    <div class="col-12">
        <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/close">
            <textarea name="zusammenfassung"><?= $purifier->purify($episode->getZusammenfassung()) ?></textarea>
            <input type="hidden" value="<?= $episode->getId() ?>" name="episodenId">
            <input class="btn btn-primary" type="submit" value="Speichern">
        </form>
    </div>
</div>