<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/story.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/story/editor.js');
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $gruppe Gruppen_Model_Gruppe */
$participantsSize = count($this->possibleParticipants) > 10 ? 10 : count($this->possibleParticipants);
$charakterIds = [];
foreach ($this->participants as $participant) {
    $charakterIds[] = $participant->getCharakterId();
}
$episode = $this->episode;
/* @var $episode Story_Model_Episode */
?>
<h2>Episode für <?= $purifier->purify($this->plot->getName()) ?> ändern</h2>
<?php if($this->editSuccess === true): ?>
<p>
    Änderungen Gespeichert.
</p>
<?php endif; ?>
<div>
    <a href="<?= $this->baseUrl() ?>/Story/plots/sl/id/<?= $episode->getPlotId() ?>">
        Zurück zum Plot
    </a>
</div>
<hr />
<div>
    <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/edit">
        <div style="display: inline-block; width: 40%; vertical-align: top">
            <p>
                <label for="episodename">Episode:</label><br />
                <input type="text" id="episodename" name="episodename" size="35" required="" value="<?= $purifier->purify($this->episode->getName()) ?>">
            </p>
        </div>
        <div style="display: inline-block; width: 40%">
            <p style="vertical-align: top">
                <label for="participants">Teilnehmer:</label><br />
                <select class="charakterSelect" id="participants" name="participants[]" multiple="" size="<?= $participantsSize ?>">
                    <?php foreach($this->possibleParticipants as $charakter): 
                        $selected = in_array($charakter->getCharakterId(), $charakterIds) ? 'selected=""' : '';
                    ?>
                    <option <?= $selected ?> value="<?= $charakter->getCharakterId() ?>"><?= $charakter->getVorname() . ' ' . $charakter->getNachname() ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
        </div>
        <p>
            <label for="beschreibung">Darum gehts:</label><br />
            <textarea name="beschreibung"><?= $purifier->purify($episode->getBeschreibung()) ?></textarea>
        </p>
        <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
        <input type="submit" value="Speichern">
    </form>
</div>
<hr>
<div>
    <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/delete">
        <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
        <input type="submit" value="Diese Episode löschen">
    </form>
</div>