<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/editor.js'));
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $gruppe Gruppen_Model_Gruppe */
$participantsSize = count($this->possibleParticipants) > 10 ? 10 : count($this->possibleParticipants);
$charakterIds = [];
foreach ($this->participants as $participant) {
    $charakterIds[] = $participant->getCharakterId();
}
$episode = $this->episode;
/* @var $episode Story_Model_Episode */
?>
<div class="row">
    <div class="col">
        <h1 class="fs-1">Episode für <?= $purifier->purify($this->plot->getName()) ?> ändern</h1>
    </div>
</div>
<?php if($this->editSuccess): ?>
<p>
    Änderungen Gespeichert.
</p>
<?php endif; ?>
<div class="row">
    <div class="col">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/Story/plots/sl/id/<?= $episode->getPlotId() ?>">
            Zurück zum Plot
        </a>
    </div>
</div>

<hr />


<form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/edit">

    <div class="row m-3">
        <div class="col-6">
            <label class="form-label" for="episodename">Episode</label>
            <input
                class="form-control"
                type="text"
                id="episodename"
                name="episodename"
                required=""
                value="<?= $purifier->purify($this->episode->getName()) ?>" />
        </div>
    </div>
    <div class="row m-3">
        <div class="col-6">
            <label class="form-label" for="participants">Teilnehmer</label>
            <select class="charakterSelect form-select" id="participants" name="participants[]" multiple size="<?= $participantsSize ?>">
                <?php foreach($this->possibleParticipants as $charakter):
                    $selected = in_array($charakter->getCharakterId(), $charakterIds) ? 'selected=""' : '';
                    ?>
                    <option <?= $selected ?> value="<?= $charakter->getCharakterId() ?>"><?= $charakter->getVorname() . ' ' . $charakter->getNachname() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="row m-3">
        <div class="col-12">
            <label class="form-label" for="beschreibung">Darum gehts</label><br />
            <textarea name="beschreibung"><?= $purifier->purify($episode->getBeschreibung()) ?></textarea>
        </div>
    </div>

    <div class="row m-3">
        <div class="col-6">
            <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
            <input class="btn btn-primary" type="submit" value="Speichern">
        </div>
    </div>

</form>

<hr>

<div class="row m-3">
    <div class="col-12">
        <form method="post" action="<?= $this->baseUrl() ?>/Story/episoden/delete">
            <input type="hidden" name="episodeId" value="<?= $episode->getId() ?>">
            <input class="btn btn-danger" type="submit" value="Diese Episode löschen">
        </form>
    </div>
</div>