<?php
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$participantsReady = $this->participantsReady;
$participantsPending = $this->participantsPending;
/* @var $episode Story_Model_Episode */
$episode = $this->episode;
?>
<div class="row">
    <div class="col">
        <h1 class="fs-1">Status: <?= $episode->getName() ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-2">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/Story/plots/sl/id/<?= $episode->getPlotId() ?>">
            Zurück zum Plot
        </a>
    </div>
    <div class="col-2">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/Story/episoden/review/episode/<?= $episode->getId() ?>">
            Episode bearbeiten
        </a>
    </div>
</div>

<hr />

<div class="row">
    <div class="col">
        <h2 class="fs-2">Offen</h2>
    </div>
</div>
<div class="row">
    <?php foreach($participantsPending as $charakter): ?>
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <?= $purifier->purify($charakter->getVorname() . ' '  . $charakter->getNachname()) ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>


<div class="row">
    <div class="col">
        <h2 class="fs-2">Bereit</h2>
    </div>
</div>
<div class="row">
    <?php foreach($participantsReady as $charakter): ?>
        <div class="col-3">
            <div class="card">
                <div class="card-body">
                    <?= $purifier->purify($charakter->getVorname() . ' '  . $charakter->getNachname()) ?>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>


<div class="row">
    <h3 class="fs-3">
        Beschreibung
    </h3>
    <div class="col-12 text-muted">
        <?= $purifier->purify($episode->getBeschreibung()) ?>
    </div>
</div>