<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/items.js'));
/* @var $purifier HTMLPurifier */
/** @var $item \Shop\Models\Item */
/** @var $character Application_Model_Charakter */
$purifier = $this->purifier;
$character = $this->character;
$itemCategoryNames = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => ['name' => 'Nahkampfwaffen', 'descr' => 'Waffen für den Nahkampf'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => ['name' => 'Distanzwaffen', 'descr' => 'Waffen für den Fernkampf'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => ['name' => 'Konzeptwaffen', 'descr' => 'Konzept-basierte Waffen'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => ['name' => 'Mystic Codes', 'descr' => 'Magische Items'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => ['name' => 'Rezepte', 'descr' => 'Kochrezepte'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => ['name' => 'Sonstiges', 'descr' => 'Alles mögliche'],
];
$itemCategories = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => [],
];
foreach ($this->items as $item) {
    $itemCategories[$item->getType()][] = $item;
}
?>
<h1 class="fs-1">Shop</h1>
<?php
foreach ($itemCategories as $key => $category):
    if (count($category) === 0) {
        continue;
    }
    usort($category, function (\Shop\Models\Item $previous, \Shop\Models\Item $next) {
        return $previous->getRank() <=> $next->getRank();
    })
?>
<fieldset>
    <legend class="fs-3"><?= $itemCategoryNames[$key]['name'] ?> <span class="indicator"></span></legend>
    <p class="fs-5">
        <?= $itemCategoryNames[$key]['descr'] ?>
    </p>
    <div class="subContent">
        <div class="row">
            <?php foreach ($category as $item): ?>
                <div class="col-6 p-2">
                    <div class="card" style="height: 17rem; overflow: auto">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-6">
                                    <div class="card-title fs-4">
                                        <?= $purifier->purify($item->getName()) ?>
                                    </div>
                                    <?php if ($item->activeDiscountDay()): ?>
                                        <div class="card-subtitle">20% Tagesrabatt</div>
                                    <?php endif; ?>
                                </div>
                                <div class="col-6">
                                    <button class="buy btn btn-primary" data-id="<?= $item->getId() ?>">
                                        Kaufen - <?= $item->getActualCost($character) ?> FP
                                    </button>
                                </div>
                            </div>
                            <div>
                                Rang: <span class="fw-bold"><?= $purifier->purify($item->getRank()) ?></span>
                            </div>
                            <div class="m-1 text-muted">
                                <?= $purifier->purify($item->getDescription()) ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</fieldset>
<?php endforeach; ?>