<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/items.js'));
/* @var $purifier HTMLPurifier */
/** @var $item \Shop\Models\Item */
/** @var $character Application_Model_Charakter */
$purifier = $this->purifier;
$character = $this->character;
$itemCategoryNames = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => ['name' => 'Nahkampfwaffen', 'descr' => 'Waffen für den Nahkampf'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => ['name' => 'Distanzwaffen', 'descr' => 'Waffen für den Fernkampf'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => ['name' => 'Konzeptwaffen', 'descr' => 'Konzept-basierte Waffen'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => ['name' => 'Mystic Codes', 'descr' => 'Magische Items'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => ['name' => 'Rezepte', 'descr' => 'Kochrezepte'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => ['name' => 'Sonstiges', 'descr' => 'Alles mögliche'],
];
$itemCategories = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => [],
];
foreach ($this->items as $item) {
    $itemCategories[$item->getType()][] = $item;
}
?>
<h1>Shop</h1>
<?php
foreach ($itemCategories as $key => $category):
    if (count($category) === 0) {
        continue;
    }
    usort($category, function (\Shop\Models\Item $previous, \Shop\Models\Item $next) {
        return $previous->getRank() <=> $next->getRank();
    })
?>
<fieldset>
    <legend><?= $itemCategoryNames[$key]['name'] ?> <span class="indicator"></span></legend>
    <p>
        <?= $itemCategoryNames[$key]['descr'] ?>
    </p>
    <div class="subContent">
        <?php foreach ($category as $item): ?>
            <div class="item">
                <p style="font-weight: bold; margin-top: 10px;"><?= $purifier->purify($item->getName()) ?></p>
                <?php if ($item->activeDiscountDay()): ?>
                    <p style="font-weight: bold; color: red">20% Tagesrabatt</p>
                <?php endif; ?>
                <p>
                    Rang: <span style="font-weight: bold"><?= $purifier->purify($item->getRank()) ?></span>
                </p>
                <p>
                    <?= $purifier->purify($item->getDescription()) ?>
                </p>
                <p>
                    <button class="buy" data-id="<?= $item->getId() ?>">
                        Gegenstand kaufen - <?= $item->getActualCost($character) ?> FP
                    </button>
                </p>
                <hr />
            </div>
        <?php endforeach; ?>
    </div>
</fieldset>
<?php endforeach; ?>