<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $achievement Application_Model_Achievement */
$charakterId = $this->charakterId;
?>
<fieldset>
    <legend>Errungenschaften entfernen</legend>
    <div>
        <?php if (count($this->achievements) > 0) { ?>
            <select id="removeAchievement" multiple="" size="5">
                <?php foreach($this->achievements as $achievement): ?>
                    <option value="<?= $achievement->getId() ?>"><?= $purifier->purify($achievement->getTitel()) ?></option>
                <?php endforeach; ?>
            </select>
            <input data-art="achievement" data-request="remove" data-id="<?= $charakterId ?>" class="save" type="submit" value="Speichern">
            <?php
        } else {
            echo 'Der Charakter hat noch keine besonderen Leistungen vollbracht.';
        }
        ?>
    </div>
</fieldset>