<?php
/* @var $achievement Application_Model_Achievement */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<fieldset>
    <legend>Errungenschaften entfernen</legend>
    <div>
        <?php if (count($this->achievements) > 0) { ?>
            <select id="removeAchievement" multiple="" size="5">
                <?php foreach($this->achievements as $achievement): ?>
                    <option value="<?= $achievement->getId() ?>">
                        <?= $purifier->purify($achievement->getTitle()) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <input class="removeExistingAchievement" type="submit" value="Speichern">
            <?php
        } else {
            echo 'Der Charakter hat noch keine besonderen Leistungen vollbracht.';
        }
        ?>
    </div>
</fieldset>