<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$charakterId = $this->charakterId;
?>
<div class="row">
    <div class="col-12 fs-4">
        Errungenschaften eintragen
    </div>
</div>
<div class="row">
    <div class="col-1">
        <label class="form-label" for="title_<?= $charakterId ?>">
            Titel
        </label>
    </div>
    <div class="col-3">
        <input class="form-control" type="text" id="title_<?= $charakterId ?>" />
    </div>
    <div class="col-4">
        <input type="submit" class="saveAchievement btn btn-primary" value="Speichern" />
    </div>
</div>
<div class="row">
    <div class="col-8">
        <label class="form-label" for="description_<?= $charakterId ?>">
            Beschreibung
        </label>
        <textarea id="description_<?= $charakterId ?>" ></textarea>
    </div>
</div>