<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$charakterId = $this->charakterId;
?>
<fieldset>
    <legend>Errungenschaften eintragen</legend>
    <div>
        <label for="title_<?= $charakterId ?>">
            Titel
        </label>
        <input type="text" id="title_<?= $charakterId ?>" />
    </div>
    <div>
        <label for="description_<?= $charakterId ?>">
            Beschreibung
        </label>
        <textarea id="description_<?= $charakterId ?>" />
    </div>
    <input type="submit" class="saveAchievement" />
</fieldset>