<?php
$itemCategoryNames = [
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MELEE => [
        'name' => 'Nahkampfwaffen', 'descr' => 'Schöne Waffen zum Draufhauen'],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_RANGED => ['name' => 'Distanzwaffen', 'descr' => 'Pfeile, Bolzen, Patronen'],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_CONCEPT => ['name' => 'Konzeptwaffen', 'descr' => 'Laser?'],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MYSTIC => ['name' => 'Mystic Codes', 'descr' => 'Dunno'],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_RECIPE => ['name' => 'Rezepte', 'descr' => 'Was zu futtern.'],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MISC => ['name' => 'Sonstiges', 'descr' => 'Alles mögliche'],
];
$itemCategories = [
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MELEE => [],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_RANGED => [],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_CONCEPT => [],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MYSTIC => [],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_RECIPE => [],
    Shop_Model_Itemtypes::ITEMTYPE_WEAPON_MISC => [],
];
foreach ($charakter->getItems() as $item) {
    $itemCategories[$item->getType()][] = $item;
}
?>
<fieldset>
    <legend><h2>Gegenstände</h2></legend>
    <?php
    foreach ($itemCategories as $key => $category):
        if (count($category) === 0) {
            continue;
        }
        usort(
            $category, function (Application_Model_Item $previous, Application_Model_Item $next) {
            return $previous->getRank() <=> $next->getRank();
        }
        )
        ?>
        <fieldset>
            <legend><?= $itemCategoryNames[$key]['name'] ?> <span class="indicator"></span></legend>
            <p>
                <?= $itemCategoryNames[$key]['descr'] ?>
            </p>
            <div class="subContent">
                <?php foreach ($category as $item): ?>
                    <div class="item">
                        <p style="font-weight: bold; margin-top: 10px;"><?= $purifier->purify($item->getName()) ?></p>
                        <p>
                            Rang: <span style="font-weight: bold"><?= $purifier->purify($item->getRank()) ?></span>
                        </p>
                        <p>
                            <?= $purifier->purify($item->getDescription()) ?>
                        </p>
                        <hr/>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    <?php endforeach; ?>
</fieldset>