<?php
/* @var $element Administration_Model_Element */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Elemente
</h1>
<?php
foreach ($this->list as $element){
?>
<a href="<?= $this->baseUrl() ?>/Administration/element/show/id/<?= $element->getId() ?>">
    <fieldset>
        <p>
            <?= $purifier->purify($element->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify(substr($element->getBeschreibung(), 0, 100)) ?>
            <?= (strlen($element->getBeschreibung()) > 100) ? '...' : '' ?>
        </p>
    </fieldset>
</a>
<?php
}