<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/Administration/editor.js');
?>
<h1>Element erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/element/create" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" />
        </p>
        <label for="beschreibung">
            Beschreibung
        </label>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <label for="charakter">
            Charakter
        </label>
        <textarea name="charakter" cols="80" rows="10"></textarea>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Element erstellen" />
    </div>
</form>