<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1 class="fs-1">Element erstellen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/element/create" method="post">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="name">Name</label>
            <input class="form-control" id="name" type="text" size="35" name="name" />
        </div>
        <div class="col-4">
            <label class="form-label" for="kosten">Kosten</label>
            <input class="form-control" id="kosten" type="number" name="kosten" />
        </div>
    </div>
    <div class="row m-3">
        <div class="col-12">
            <label class="form-label" for="beschreibung">
                Beschreibung
            </label>
            <textarea name="beschreibung" id="beschreibung" cols="80" rows="10"></textarea>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-12">
            <label class="form-label" for="charakter">
                Charakter
            </label>
            <textarea name="charakter" id="charakter" cols="80" rows="10"></textarea>
        </div>
    </div>

    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Element erstellen" />
        </div>
    </div>
</form>