<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/skillList.js'));
/* @var $skill Administration_Model_Skill */
/* @var $gruppe Application_Model_Klassengruppe */
/* @var $klasse Application_Model_Klasse */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$skillartArray = array();
$skillarten = array(
    1 => 'Schützenfähigkeiten',
    2 => 'Kämpferfähigkeiten',
    3 => 'Übungsfähigkeiten',
    4 => 'Spezialfähigkeiten',
);
?>
<h1>
    Fähigkeiten
</h1>
<fieldset>
    <legend>Filter</legend>
    <div>
        <select id="skillarten" multiple size="4" style="vertical-align: top">
            <?php foreach ($skillarten as $key => $skillart) : ?>
            <option value="<?= $key ?>"><?= $skillart ?></option>
            <?php endforeach; ?>
        </select>
        <select id="gruppen" multiple size="5" style="vertical-align: top">
            <?php foreach ($this->klassengruppen as $gruppe) : ?>
            <option value="<?= $gruppe->getId() ?>"><?= $gruppe->getBezeichnung() ?></option>
            <?php endforeach; ?>
        </select>
        <select id="klassen" multiple size="7" style="vertical-align: top">
            <?php foreach ($this->klassen as $klasse) : ?>
            <option value="<?= $klasse->getId() ?>"><?= $klasse->getBezeichnung() ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <button id="filterExecute">Suchen</button>
</fieldset>
<div id="list">
    <?php
    foreach ($this->list as $skill){ ?>
        <?php if(!in_array($skill->getSkillArt(), $skillartArray)){ ?>
        <h2 id="<?= $skill->getSkillArt() ?>">
            <?= $skillarten[$skill->getSkillArt()] ?>
        </h2>
        <?php } ?>
    <a href="<?= $this->baseUrl() ?>/Administration/skill/show/id/<?= $skill->getId() ?>">
        <fieldset>
            <legend>
                <?= $purifier->purify($skill->getBezeichnung()) ?>
            </legend>
            <div>
                <?= $purifier->purify(substr($skill->getBeschreibung(), 0, 100)) ?>
                <?= (strlen($skill->getBeschreibung()) > 100) ? '...' : '' ?>
            </div>
        </fieldset>
    </a>
    <?php
    $skillartArray[] = $skill->getSkillArt();
    }
    ?>
</div>