<?php
/* @var $skill Administration_Model_Skill */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$skillartArray = array();
$skillarten = array(
    1 => 'Schützenfähigkeiten',
    2 => 'Kämpferfähigkeiten',
    3 => 'Übungsfähigkeiten',
    4 => 'Spezialfähigkeiten',
);
?>
<h1>
    Fähigkeiten
</h1>
<?php
for($i = 0; $i < count($skillarten); $i++){
    echo '<a href="#' . ($i+1) . '">' . $skillarten[1+$i] . '</a>';
    if($i < count($skillarten)-1){
        echo ', ';
    }
}
foreach ($this->list as $skill){ ?>
    <?php if(!in_array($skill->getSkillArt(), $skillartArray)){ ?>
    <h2 id="<?= $skill->getSkillArt() ?>">
        <?= $skillarten[$skill->getSkillArt()] ?>
    </h2>
    <?php } ?>
<a href="<?= $this->baseUrl() ?>/Administration/skill/show/id/<?= $skill->getId() ?>">
    <fieldset>
        <p>
            <?= $purifier->purify($skill->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify(substr($skill->getBeschreibung(), 0, 100)) ?>
            <?= (strlen($skill->getBeschreibung()) > 100) ? '...' : '' ?>
        </p>
    </fieldset>
</a>
<?php
$skillartArray[] = $skill->getSkillArt();
}