<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/Administration/editor.js');
/* @var $skill Administration_Model_Skill */
$skill = $this->skill;
?>
<h1>Fähigkeit anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/skill/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $skill->getBezeichnung() ?>" />
            <label for="kosten">FP-Kosten</label>
            <input type="number" name="fp" value="<?= $skill->getFp() ?>" />
        </p>
        <p>
            <label for="skillart">
                Fähigkeitenart
            </label>
            <select name="skillart">
                <option value="1">Schützenfähigkeit</option>
                <option value="2">Kämpferfähigkeit</option>
                <option value="3">Übungsfähigkeit</option>
                <option value="4">Spezialfähigkeit</option>
            </select>
        </p>
        <p>
            <label for="rang">
                Rang
            </label>
            <select name="rang">
                <option>EX</option>
                <option>A</option>
                <option>B</option>
                <option>C</option>
                <option>D</option>
                <option>E</option>
                <option>F</option>
            </select>
        </p>
        <p>
            <label for="uebung">
                benötigte Übung
            </label>
            <input type="number" name="uebung" value="<?= $skill->getUebung() ?>" />
        </p>
        <p>
            <label for="disziplin">
                benötigte Disziplin
            </label>
            <input type="number" name="disziplin" value="<?= $skill->getDisziplin() ?>" />
        </p>
            <label for="gruppen">
                Klassengruppen:
            </label>
            <select name="gruppen[]" multiple="true" size="8">
                <?php foreach ($this->klassengruppen as $gruppe) { ?>
                <option value="<?= $gruppe->getId() ?>">
                    <?= $gruppe->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="klassen">
                Klassen:
            </label>
            <select name="klassen[]" multiple="true" size="8">
                <?php foreach ($this->klassen as $klasse) { ?>
                <option value="<?= $klasse->getId() ?>">
                    <?= $klasse->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="skills">
                Fähigkeiten:
            </label>
            <select name="skills[]" multiple="true" size="8">
                <?php foreach ($this->skills as $skill) { ?>
                <option value="<?= $skill->getId() ?>">
                    <?= $skill->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
        <label for="beschreibung">
            Beschreibung
        </label>
        <textarea name="beschreibung" cols="80" rows="10">
            <?= $skill->getBeschreibung() ?>
        </textarea>
    </fieldset>
    <div align="center">
        <input type="hidden" name="skillId" value="<?= $this->skill->getId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Speichern" />
    </div>
</form>