<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/nachrichtencenter/editor.js');
/* @var $users Application_Model_User */
$users = $this->users;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $respondTo Nachrichten_Model_Nachricht */
$respondTo = $this->respondTo;
?>
<h1>
    Nachricht verfassen
</h1>
<div class="submenu">
    <?php include __DIR__ . '/../partials/submenu.phtml'; ?>
</div>
<br />
<fieldset>
    <form method="post" action="<?= $this->baseUrl() ?>/Nachrichten/index/send">
        <p>
            <label for="user">
                An:
            </label>
            <select class="userSelect" name="user" <?= ($respondTo !== null) ?  'disabled=""' : '' ?>>
                <?php foreach ($users as $user) : ?>
                <option <?= ($respondTo !== null AND $respondTo->getVerfasserId() == $user->getId()) ? 'selected=""' : '' ?> value="<?= $user->getId() ?>">
                    <?= $purifier->purify($user->getProfilname()) ?> <?= ($user->getUsergruppe() === 'Admin') ? '- Administrator' : '' ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>
        <p>
            <label for="betreff">Betreff</label>
            <input class="betreffInput" type="text" name="betreff" value="<?= ($respondTo !== null && $respondTo->getBetreff() !== null) ? 'RE: ' . $respondTo->getBetreff() : '' ?>">
        </p>
        <?php if($respondTo !== null): ?>
        <input type="hidden" name="user" value="<?= $respondTo->getVerfasserId() ?>">
        <?php endif ?>
        <textarea rows="20" cols="95" name="nachricht"></textarea>
        <input type="submit" value="Nachricht senden">
    </form>
</fieldset>