<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/nachrichtencenter/editor.js'));
/* @var $users Application_Model_User */
$users = $this->users;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $respondTo \Nachrichten\Models\Message */
$respondTo = $this->respondTo;
?>
<h1>
    Nachricht verfassen
</h1>
<?php include __DIR__ . '/../partials/submenu.phtml'; ?>
<form method="post" action="<?= $this->baseUrl() ?>/Nachrichten/index/send">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="user">
                An:
            </label>
            <select class="form-control" name="user" <?= ($respondTo !== null) ?  'disabled=""' : '' ?>>
                <?php foreach ($users as $user) : ?>
                    <option <?= ($respondTo !== null AND $respondTo->getVerfasserId() == $user->getId()) ? 'selected=""' : '' ?> value="<?= $user->getId() ?>">
                        <?php
                        if($user->getCharakter() !== null){
                            $name = $user->getCharakter()->getVorname() . ' - ' . $user->getProfilname();
                        } else {
                            $name = $user->getProfilname();
                        }
                        ?>
                        <?= $purifier->purify($name) ?> <?= ($user->getUsergruppe() === 'Admin') ? '- Administrator' : '' ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="betreff">Betreff</label>
            <input class="form-control" type="text" name="betreff" value="<?= ($respondTo !== null && $respondTo->getBetreff() !== null) ? 'RE: ' . $respondTo->getBetreff() : '' ?>">
        </div>
    </div>
    <?php if(Zend_Auth::getInstance()->getIdentity()->usergruppe === 'Admin'): ?>
        <div class="row m-3">
            <div class="col-4">
                <div class="form-check">
                    <label class="form-check-label" style="margin-left: 50px; width: 200px;" for="admin">Als Admin anonym versenden: </label>
                    <input class="form-check-input" type="checkbox" id="admin" name="admin" />
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if($respondTo !== null): ?>
        <input type="hidden" name="user" value="<?= $respondTo->getVerfasserId() ?>">
    <?php endif ?>
    <textarea rows="10" cols="95" name="nachricht"></textarea>
    <input class="btn btn-primary" type="submit" value="Nachricht senden">
</form>
