<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/plots.js'));
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $plot Story_Model_Plot */
$plot = $this->plot;
/* @var $charakter Story_Model_Charakter */
/* @var $invites Application_Model_Charakter */
$submitDescriptions = [
    0 => 'Charaktere einladen',
    3 => 'Mehr Charaktere einladen',
    5 => 'Noch mehr Charaktere einladen',
    10 => 'Ein paar Leute brauchen wir noch',
];
$participantCount = count($this->participants);
foreach ($submitDescriptions as $key => $text) {
    if($key <= $participantCount){
        $submitDescription = $text;
    }
}
$invitablesSize = count($this->invitables) > 10 ? 10 : count($this->invitables);
$changableEpisodes = array();
$activeEpisodes = array();
$episodeCount = count($this->episodes);
/* @var $episode Story_Model_Episode */
if($episodeCount > 0){
    foreach ($this->episodes as $episode) {
        if(in_array($episode->getStatus()->getId(), [1, 2])){
            $changableEpisodes[] = $episode;
        } else {
            $activeEpisodes[] = $episode;
        }
    }
}
unset($this->episodes);
?>
<div class="row">
    <div class="col">
        <h1 class="fs-1">
            <?= $purifier->purify($plot->getName()) ?>
        </h1>
    </div>
</div>

<form class="row" method="post" action="<?= $this->baseUrl() ?>/Story/charakter/freigabe">

    <div class="col-12">
        <label class="form-label" for="freigabe">
            Charakterdaten für den Spielleiter freigeben?
        </label>
    </div>

    <div class="col-2">
        <select class="form-select" id="freigabe" name="freigabe" size="2">
            <option value="0" <?= $this->freigabe ? '' : 'selected=""' ?>>Nein</option>
            <option value="1"<?= $this->freigabe ? 'selected=""' : '' ?>>Ja</option>
        </select>
    </div>

    <div class="col-4">
        <input type="hidden" name="plotId" value="<?= $plot->getId() ?>">
        <input class="btn btn-primary" type="submit" value="Auswahl speichern">
    </div>

</form>

<fieldset>
    <legend>
        Beschreibung
    </legend>
    <div>
        <?= $purifier->purify($plot->getBeschreibung()) ?>
    </div>
</fieldset>
<fieldset>
    <legend>Episoden</legend>
    <?php if($episodeCount > 0){ ?>
    <div>
        <fieldset id="episodesFieldset">
            <legend>Deine Episoden</legend>
            <div id="openEpisodes">
                <?php if(count($changableEpisodes) > 0): ?>
                <label>Geplante Episoden:</label>
                <ul>
                <?php foreach($changableEpisodes as $episode): ?>
                    <li class="episode">
                        <p>
                            <span class="episodeName">
                                <?= $purifier->purify($episode->getName()); ?>
                            </span>
                        </p>
                        <p>
                            <span class="episodeStatus" style="background-color: <?= $episode->getStatus()->getColorCode() ?>">
                                <?= $episode->getStatus()->getStatus() ?>
                            </span>
                            <?php if($episode->getStatus()->getId() === 2){ ?>
                            <span class="episodeStart">
                                <a href="<?= $this->baseUrl() ?>/Story/episoden/details/episode/<?= $episode->getId() ?>">
                                    <span class="episodeLink">
                                        Details
                                    </span>
                                </a>
                            </span>
                            <?php } ?>
                        </p>
                    </li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
            <div id="closedEpisodes">
                <?php if(count($activeEpisodes) > 0): ?>
                <label>Episoden in Aktion</label>
                <ul>
                <?php foreach($activeEpisodes as $episode): ?>
                    <li class="episode">
                        <p>
                            <span class="episodeName">
                                <?= $purifier->purify($episode->getName()); ?>
                            </span>
                        </p>
                        <p>
                            <span class="episodeStatus" style="background-color: <?= $episode->getStatus()->getColorCode() ?>">
                                <?= $episode->getStatus()->getStatus() ?>
                            </span>
                            <span class="episodeStart">
                                <a href="<?= $this->baseUrl() ?>/Story/episoden/details/episode/<?= $episode->getId() ?>">
                                    <span class="episodeLink">
                                        Details
                                    </span>
                                </a>
                            </span>
                        </p>
                    </li>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
        </fieldset>
    </div>
    <?php } else { ?>
    <p>
        Du wurdest in diesem Plot noch für keine Episode eingetragen.
    </p>
    <?php } ?>
</fieldset>