<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/Administration/editor.js');
?>
<h1>Nachrichten editieren</h1>
<form action="<?= $this->baseUrl() ?>/Administration/news/edit" method="post" name="News" id="News">
    <table cellspacing="25" cellpadding="5">
        <tr>
            <td>
                <b>Titel</b>
            </td>
            <td>
                <input type="text" size="40" name="Titel" id="Titel" value="<?= $this->news->getTitel() ?>" />
            </td>
        </tr>
        <tr>
            <td valign="top">
                <b>Nachricht</b>
            </td>
            <td colspan="20">
                <textarea name="Nachricht" id="Nachricht" cols="80" rows="20">
                    <?= $this->news->getNachricht() ?>
                </textarea>
            </td>
        </tr>
    </table>
    <div align="center">
        <input type="hidden" name="newsId" value="<?= $this->news->getId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Nachricht eintragen" />
    </div>
</form>