<?php
$news = $this->news;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Neuigkeiten
</h1>
<?php
if($news !== false){
    foreach ($news as $nachricht){
        /* @var $nachricht Application_Model_News */
    ?>
        <div class="News">
            <div class="NewsTitel">
                <h2><?= htmlspecialchars($nachricht->getTitel()); ?></h2>
            </div>
            <div class="NewsNachricht">
                <?= $purifier->purify($nachricht->getNachricht()) ?>
            </div>
            <div class="NewsBottom">
                <a href="<?= $this->baseUrl(); ?>/charakter/id/<?= $nachricht->getVerfasser(); ?>">
                    <div class="NewsVerfasser">
                        Verfasst von: <?= htmlentities($nachricht->getVerfasserName()); ?>
                    </div>
                </a>
                <div class="NewsEdit">
                    <?php if($nachricht->getEditorName() !== null): ?>
                        Editiert von: <?= htmlentities($nachricht->getEditorName()) ?>
                        am <?= $nachricht->getEditdatum() ?>
                    <?php endif ?>
                </div>
                <div class="NewsDatum">
                    Verfasst am <?= $nachricht->getDatum(); ?>
                </div>
            </div>
        </div>
    <?php
    }
}
?>
