<?php
$news = $this->news ?? [];
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
if ($this->message !== null) {
    ?>
    <div class="error">
        <?= $this->message ?>
    </div>
    <?php
}
?>
<h1>
    Neuigkeiten
</h1>
<?php
foreach ($news as $nachricht){
    /* @var $nachricht Application_Model_News */
    ?>
    <div class="row m-3">
        <div class="container">
            <div class="row">
                <h2><?= $this->purify($nachricht->getTitel()); ?></h2>
            </div>
            <div class="row p-3">
                <?= $this->purify($nachricht->getNachricht()) ?>
            </div>
            <div class="row justify-content-between">
                <div class="col-3">
                    Verfasst von: <?= $this->purify($nachricht->getVerfasserName()); ?>
                </div>
                <div class="col-3">
                    <?php if($nachricht->getEditorName() !== null): ?>
                        Editiert von: <?= $this->purify($nachricht->getEditorName()) ?>
                        am <?= $nachricht->getEditdatum() ?>
                    <?php endif ?>
                </div>
                <div class="col-3">
                    Verfasst am <?= $nachricht->getDatum(); ?>
                </div>
            </div>
        </div>
        <hr />
    </div>
    <?php
}
?>
