<img src="<?= $this->baseUrl() ?>/images/sonstige/Startseite-Kirei.png" width="355" height="596" style="border: 0px; vertical-align: middle;" alt="Kirei" />
<p>
    <i>
        Frohlocke, arme Seele.
    </i>
</p>
<p>
    <i>
        Mein Name ist <strong>Kotomine Kirei</strong>, und ich bin der <strong>Supervisor</strong> dieser Seite. 
        Meine leidvolle Aufgabe besteht darin dir die <strong>Grundzüge dieses Spiels</strong> zu erklären, um deiner Orientierungslosigkeit auf die Sprünge zu helfen und mir mein Abendbrot zu verdienen.
    </i>
</p>
<p>
    <i>
        Wir befinden uns im <strong>Nasuverse</strong>, einer Welt ähnlich der welcher du anscheinend entflohen bist. Der wichtigste Unterschied ist die Gegenwart von Magie, ein Wissen welches der Menschheit 
        unbedingt vorenthalten werden muss. Es ist sicher mit Harry Potter oder Twilight dahingehend vergleichbar, dass der gewöhnliche Normalmensch von alldem nichts erfahren darf, doch rechne nicht 
        damit Zauberstab schwingende Kinder, flirtende Vampire oder gar Werwölfe anzutreffen.
    </i>
</p>
<p>
    <i>
        Ganz gleich für welche der zahlreichen <strong>Klassen und Spezialisierungsmöglichkeiten</strong> du dich entscheidest, allen ist dasselbe Schicksal gemein: F&uuml;hre einen normalen Menschen in diese Welt ein, 
        und du stirbst. <strong>Der Tod</strong> ist in diesem Spiel allgegenw&auml;rtig und, heh, sicherlich wirst auch du hier deinen Tod finden. Ob er das Ende oder ein Neuanfang ist, wielange du ihm entgehen kannst, 
        dass sind die Dinge die mein pers&ouml;nliches Interesse wecken.
        <br /> 
        Doch geht es hier nicht darum was ich m&ouml;chte, also fahren wir fort.
    </i>
</p>
<p>
    <i>
        Dieses Spiel findet beinahe ausschließlich in der japanischen Kleinstadt <strong>Fuyuki City</strong> statt, welche am Miongawa Fluss entfernt jeglicher Zivilisation zu sein scheint. Auf vielen Karten ist Fuyuki nicht 
        verzeichnet und auch die Menschen die hier leben scheinen eine große <strong>Ignoranz</strong> f&uuml;r Belange ausserhalb ihrer Stadtgrenzen an den Tag zu legen.
        <br />
        Dies ist nach Kyoto in Japan der Ort mit der h&ouml;chsten Population an 'Eingeweihten'. Hier befinden sich Anwesen der <strong>Emiya, Matou, Einzbern und Tohsaka</strong>, vierer m&auml;chtiger Magi-Familien, ebenso wie Anwesen 
        der <strong>Touzaki-Bluterbler und Fujou-D&auml;monenj&auml;ger</strong>. Auch meine eigene Familie, die <strong>Kotomine</strong>, lebt seit einigen Generationen in Fuyuki.
    </i>
</p>
<p>
    <i>
        Doch, arme Seele, diese Details m&uuml;ssen erm&uuml;dend sein. Nach der Charakter-Erstellung und der Bekanntmachung mit den &Ouml;rtlichkeiten wirst du dir sicher die Frage meines Lebens stellen: <strong>Und was nun?</strong>
    </i>
</p>
<p>
    <i>
        Nun kommt die Besonderheit des Spiels zum Tragen: <strong>Das Plot-System</strong>. Ob du einer bestimmten Organisation beitreten m&ouml;chtest, auf eigene Faust nach Abenteuern suchst oder auch dein ganz eigenes Konzept auf die Beine stellen m&ouml;chtest, 
        ist dir selbst &uuml;berlassen. Neben dem gew&ouml;hnlichen <strong>&Ouml;ffentlichen RPG</strong> gibt es das sogenannte <strong>Plot-RPG</strong>, in welchem du von Spielleitern geleitete Missionen und Situationen durchlebst. Die &Uuml;berg&auml;nge von &ouml;ffentlichem RPG und Plot-RPG k&ouml;nnen fliessend sein:
    </i>
</p>
<p>
    <i>
        Du kannst einen befreundeten Charakter im &ouml;ffentlichen RPG kennenlernen, ehe ihr zwei in einem Plot-RPG in <strong>diverse Abenteuer</strong> hineingeratet die es zu bestehen gilt. Der signifikanteste Unterschied ist dabei das Stichwort <strong>"Charakter-Entwicklung"</strong>.
        <br />
        Nun hast du also einen Pokerface-Charakter mit trauriger Hintergrundgeschichte erstellt. Er traut niemandem und sorgt sich nur um sich selbst, vielleicht hassen ihn die meisten Menschen gar grundlos. Nun lernt er im &ouml;ffentlichen RPG ein M&auml;dchen kennen 
        mit welchem er viel unternimmt. Er erz&auml;hlt ihr von seiner Vergangenheit, wird offener und eventuell findet er durch sie sogar weitere Freunde. Das ist <strong>langweilig</strong>.                     
    </i>
</p>
<p>
    <i>
        Das Prinzip dieses Spiels geht davon aus, dass dieser Charakter im &ouml;ffentlichen RPG das M&auml;dchen kennenlernen kann, doch sollte er sich ihr gegen&uuml;ber nur in geringem Ma&szlig;e erw&auml;rmen. All das Vertrauen welches er zu ihr aufbaut um eventuell aufzutauen, sollte innerhalb des <strong>Plot-RPGs</strong> geschehen.
        <br />
        <strong>Warum?</strong> Nun, es ist einfach interessanter wenn sich zwei Charaktere vertrauen da sie gemeinsam wieder und wieder durch die H&ouml;lle gingen, als wenn sie bloß einige Wochen miteinander gesprochen und geflirtet haben.
        <br />
        Durch Plot-RPG erh&auml;lt man so genannte <strong>"Erfolge"</strong>. Dies sind RPG-bezogene Vorteile, so k&ouml;nnte ein Erfolg aus dem eben genannten Beispiel die "Freundschaft" oder "Liebe" zwischen zwei Charakteren sein, wenn in dem Plot klar wurde, dass sie tats&auml;chlich soviel f&uuml;reinander empfinden. 
        Durch das Spielsystem ist es dann m&ouml;glich diese Erfolge zum Vorteil des eigenen Charakters zu nutzen. Du k&ouml;nntest einen Werteboost bekommen wenn es um den Schutz einer Person geht welche du liebst, oder einen Plot aufbauen der auf eben dieser Liebe basiert. 
        Diese Liebe ist im &ouml;ffentlichen RPG entstanden? Dann ist es leider nicht m&ouml;glich auf diese Boni zuzugreifen                       
    </i>
</p>
<p>
    <i>
        Da im Prinzip jeder Spieler das Recht hat sich <strong>Spielleiter</strong> zu nennen, solange es andere Spieler gibt welche ihn als solchen akzeptieren, sollte es keinen Mangel an ihnen geben. Eine Gruppe die sich mit einem Plot befasst kann unendlich groß sein, allerdings sollte bedacht werden dass eine gr&ouml;&szlig;ere Gruppe 
        auch mehr Spielleiter ben&ouml;tigen wird. Ob sich der Plot um ein Schuldrama handelt, man die eigene Schulfu&szlig;ballmannschaft zur Landesmeisterschaft f&uuml;hren will, die Jagd nach einem finsteren Dead Apostle stattfindet, 
        man durch ungl&uuml;ckliche Zust&auml;nde in die F&auml;nge krimineller Machenschaften ger&auml;t oder man gar versucht die Kontrolle der eigenen Firma auf ganz Fuyuki auszuweiten - es gibt viele Mßglichkeiten Plots zu spinnen
    </i>
</p>
<p>
    <i>
        Fr&uuml;her oder sp&auml;ter wird es f&uuml;r jeden Charakter sicherlich einmal zum <strong>Kampf</strong> kommen. Das <strong>Kampfsystem von Fate</strong> unterscheidet sich von vergleichbaren vor allem durch sein <strong>Kategorien-System</strong>. Neben den normalen <strong>Werten</strong> (zB 150 Stßrke, 80 Ausdauer, ... ) gibt es Werte-abh&auml;ngige Kategorien welche den Powerlevel des Charakters 
        im Verh&auml;ltnis zu seiner Umgebung wiederspiegelt.
        <br />
        Diese Kategorien reichen von F bis A und demzufolge von Sehr Schwach bis &Uuml;berm&auml;&szlig;ig Stark. Normale Menschen sind f&uuml;r gew&ouml;hnlich nicht in der Lage &uuml;ber eine Kategorie von C hinauszukommen, das heisst jedoch nicht dass ein Wertetraining nicht weiterhin m&ouml;glich w&auml;re.
    </i>
</p>
<i>
    F&uuml;r weitere Informationen solltest du im <strong>Chat</strong> nachfragen oder die <strong>Spiel-Informationen</strong> studieren. Es mag sicher sein, dass du nicht alles von dem begreifen konntest was ich dir erz&auml;hlte, doch was w&auml;re eine Welt ohne &Uuml;berraschungen? F&uuml;r den Beginn ist es nur wichtig sich &uuml;ber die <strong>Charakter-Erstellung</strong> klar zu werden und sich f&uuml;r einen Charakter zu entscheiden, 
    mit dem man spielen m&ouml;chte. Da jede Klasse <strong>individuelle St&auml;rken und Schw&auml;chen</strong> besitzt, ist es als Anf&auml;nger sinnlos sich den Kopf ßber die besten Skillungen zu zerbrechen. 
    Denke daran, arme Seele, dass dies ein <strong>Plot-basierendes RPG</strong> ist! K&auml;mpfe sind durchaus wichtig und sollen Spaß machen, doch einen Charakter aufgrund von Werten zu erstellen ist dasselbe als w&uuml;rde man gesundes Curry gen&uuml;sslichem Curry vorziehen. Es wird dir zweifelsohne helfen, doch letzten Endes wirst du dich fragen: <strong>War es das wert?</strong>
</i>
<p>
    <i>
        Ah, endlich. Mein Curry ist fertig, du darfst gehen.
    </i>
</p>
<p>
    <i>
        M&ouml;glicherweise, wenn du es schaffst bis dahin am Leben zu bleiben, sehen wir uns irgendwann im <strong>Gralskrieg</strong> wieder.
        <br />
        Du weisst nicht was der Gralskrieg ist? Hum Hum Hum... arme Seele.
    </i>
</p>
<div style="max-width: 650px; margin: 0 auto;">
    <img src="<?= $this->baseUrl() ?>/images/sonstige/Startseite-Kirei2.jpg" width="100%" style="border: 0px; vertical-align: middle;" alt="Nochmal Kirei" />
</div>
