<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/story/charakter.js'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $gruppe Gruppen_Model_Gruppe */
$gruppe = $this->gruppe;
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
$werte = $charakter->getCharakterwerte();


$sortorder = [
    'Übungsfähigkeiten' => 1,
    'Schützenfähigkeiten' => 2,
    'Kämpferfähigkeiten' => 3,
    'Spezialfähigkeiten' => 4,
];

$order = function (Application_Model_Skillart $a, Application_Model_Skillart $b) use ($sortorder)
{
    return $sortorder[$a->getBezeichnung()] > $sortorder[$b->getBezeichnung()];
};

/* @var $skillart Application_Model_Skillart */
/* @var $skill Application_Model_Skill */
$skillarten = $this->skillarten;
usort($skillarten, $order);
/* @var $schule Application_Model_Schule */
$magieschulen = $this->magieschulen;
$magien = $this->magien;
$categoryStr = $werte->getCategory('str');
$categoryAgi = $werte->getCategory('agi');
$categoryAus = $werte->getCategory('aus');
$categoryKon = $werte->getCategory('kon');
$categoryDis = $werte->getCategory('dis');
$categoryPra = $werte->getCategory('pra');
?>
<h1>
    <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
</h1>
<?php if ($charakter->getSlData() !== '') { ?>
    <fieldset class="characterObjectives">
        <legend>Ziele des Charakters</legend>
        <div><?= $this->purify($charakter->getSlData()) ?></div>
    </fieldset>
<?php } ?>
<div>
    <fieldset style="display: inline-block; width: 49%; float: left">
        <legend><h2>Charakterdaten</h2></legend>
        <p>
            <label>
                Name
            </label>
            <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
        </p>
        <p>
            <label>
                Geschlecht
            </label>
            <?= $purifier->purify($charakter->getGeschlecht()) ?>
        </p>
        <p>
            <label>
                Geburtsdatum
            </label>
            <?= $purifier->purify($charakter->getGeburtsdatum('d.m.Y') . ' (' . $charakter->getAlter() . ')') ?>
        </p>
        <p>
            <label>
                Wohnort
            </label>
            <?= $purifier->purify($charakter->getWohnort()) ?>
        </p>
        <p>
            <label>
                Sexuelle Orientierung
            </label>
            <?= $purifier->purify($charakter->getSexualitaet()) ?>
        </p>
        <p>
            <label>
                Odo
            </label>
            <?= $charakter->getOdo()->getActualAmount() . ' ' . $charakter->getOdo()->getKategorie() ?>
        </p>
        <p>
            <label>
                Glück
            </label>
            <?= $charakter->getLuck()->getKategorie() ?>
        </p>
        <p>
            <label>
                Vermögen
            </label>
            <?= $charakter->getVermoegen()->getMenge() . ' ' . $charakter->getVermoegen()->getKategorie() ?>
        </p>
        <p>
            <label>
                Naturelement
            </label>
            <?= $charakter->getNaturElement()->getBezeichnung() ?>
        </p>
        <?php if ($charakter->getMagiccircuit()->getKategorie() !== 'F'): ?>
            <p>
                <label>
                    Circuit
                </label>
                <?= $charakter->getMagiccircuit()->getMenge() . ' ' . $charakter->getMagiccircuit()->getKategorie() ?>
            </p>
        <?php endif; ?>
    </fieldset>
    <fieldset style="display: inline-block; width: 49%; float: right">
        <legend><h2>Werte</h2></legend>
        <p>
            <label>
                Stärke
            </label>
            <span title="<?= $werte->getStaerke() ?>">
                <?= floor($werte->getStaerke()) ?>
            </span>
            <span class="<?= $categoryStr->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryStr->getCategory() ?> (<?= $categoryStr->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Agilität
            </label>
            <span title="<?= $werte->getAgilitaet() ?>">
                <?= floor($werte->getAgilitaet()) ?>
            </span>
            <span class="<?= $categoryAgi->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryAgi->getCategory() ?> (<?= $categoryAgi->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Ausdauer
            </label>
            <span title="<?= $werte->getAusdauer() ?>">
                <?= floor($werte->getAusdauer()) ?>
            </span>
            <span class="<?= $categoryAus->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryAus->getCategory() ?> (<?= $categoryKon->getNumericValue() ?>) = <?= $werte->getEnergie() ?> HP
            </span>
        </p>
        <p>
            <label>
                Kontrolle
            </label>
            <span title="<?= $werte->getKontrolle() ?>">
                <?= floor($werte->getKontrolle()) ?>
            </span>
            <span class="<?= $categoryKon->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryKon->getCategory() ?> (<?= $categoryKon->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Disziplin
            </label>
            <span title="<?= $werte->getDisziplin() ?>">
                <?= floor($werte->getDisziplin()) ?>
            </span>
            <span class="<?= $categoryDis->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryDis->getCategory() ?> (<?= $categoryDis->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Übung
            </label>
            <span title="<?= $werte->getUebung() ?>">
                <?= floor($werte->getUebung()) ?>
            </span>
            <span class="<?= $categoryPra->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryPra->getCategory() ?> (<?= $categoryPra->getNumericValue() ?>)
            </span>
        </p>
    </fieldset>
    <div style="clear: both"></div>
</div>
<div>
    <fieldset>
        <legend><h2>Klasse</h2></legend>
        <h3>
            <?= $purifier->purify($charakter->getKlassengruppe()->getBezeichnung()) ?>
        </h3>
        <p>
            Unterklasse: <?= $purifier->purify($charakter->getKlasse()->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify($charakter->getKlasse()->getBeschreibung()) ?>
        </p>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend><h2>Fähigkeiten</h2></legend>
        <?php foreach ($skillarten as $skillart): ?>
            <fieldset>
                <legend><?= $purifier->purify($skillart->getBezeichnung()) ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <?php foreach ($skillart->getSkills() as $skill): ?>
                        <h3>
                            <?= $purifier->purify($skill->getBezeichnung()) ?>
                        </h3>
                        <p>
                            Rang: <?= $skill->getRang() ?>
                        </p>
                        <p>
                            <?= $purifier->purify($skill->getBeschreibung()) ?>
                        </p>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend><h2>Magien</h2></legend>
        <?php
        foreach ($magieschulen as $schule):
            /** @var Application_Model_Schule $schoolMagic */
            $schoolMagic = array_filter($magien, function (Application_Model_Magie $magie) use ($schule) {
                return $magie->getSchule()->getId() === $schule->getId();
            });
            ?>
            <fieldset>
                <legend><?= $schule->getBezeichnung() ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <?php foreach ($schoolMagic as $magie): ?>
                        <h3>
                            <?= $purifier->purify($magie->getBezeichnung()) ?>
                        </h3>
                        <p>
                            Rang: <?= $magie->getRang() ?>
                        </p>
                        <p>
                            <?= $purifier->purify($magie->getBeschreibung()) ?>
                        </p>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<?php include __DIR__ . '/partials/inventar.phtml' ?>
<div>
    <fieldset>
        <legend><h2>Traits</h2></legend>
        <?php foreach ($charakter->getTraits() as $trait): ?>
        <fieldset>
            <legend><?= $purifier->purify($trait->getName()) ?> <span class="indicator"></span></legend>
            <div class="subContent">
                <?= $purifier->purify($trait->getBeschreibung()) ?>
            </div>
        </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend><h2>Profildaten</h2></legend>
        <h3>Charaktergeschichte</h3>
        <div><?= $purifier->purify($charakter->getCharakterprofil()->getCharaktergeschichte()) ?></div>
        <h3>Private Daten</h3>
        <div><?= $purifier->purify($charakter->getCharakterprofil()->getPrivatdaten()) ?></div>
        <h3>Pics</h3>
        <div style="display: inline-block; width: 45%; float: left"><img width="200px" src="<?= $purifier->purify($charakter->getCharakterprofil()->getCharpic()) ?>"/></div>
        <div style="display: inline-block; width: 45%; float: right"><img width="200px" src="<?= $purifier->purify($charakter->getCharakterprofil()->getProfilpic()) ?>"/></div>
        <div style="clear: both"></div>
    </fieldset>
</div>