<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/skillarten.js'));
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
/* @var $skillart Shop_Model_Skillart */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Fähigkeiten
</h1>
<?php
$lockedSkillarten = array();
foreach ($this->skillarten as $skillart):
    if($skillart->getLearned() === false){
        $lockedSkillarten[] = $skillart;
        continue;
    }
    if($skillart->getId() === 3): ?>
<img src="http://i.imgur.com/QDDjNup.jpg">
    <?php
    endif;
    ?>
<fieldset style="margin-bottom: 1.5em">
    <legend>
        <?= $purifier->purify($skillart->getBezeichnung()) ?>
    </legend>
    <p>
        <?= $purifier->purify($skillart->getBeschreibung()) ?>
    </p>
    <fieldset>
        <legend class="skillart" data-id="<?= $skillart->getId() ?>">Fähigkeiten anzeigen</legend>
        <div class="subContent"></div>
    </fieldset>
</fieldset>
<hr />
<?php endforeach;
foreach ($lockedSkillarten as $skillart):
?>
<fieldset style="margin-bottom: 1.5em">
    <p>
        <?= $purifier->purify($skillart->getBezeichnung()) ?>
    </p>
    <p>
        <?= $purifier->purify($skillart->getBeschreibung()) ?>
    </p>
    <form method="POST" action="<?= $this->baseUrl() ?>/Shop/skill/unlockskillart">
        <input type="hidden" value="<?= $skillart->getId() ?>" name="skillartId">
        <input type="submit" value="Kategorie freischalten">
    </form>
</fieldset>
<hr />
<?php
endforeach;
?>
<div id="dialog"></div>