<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/skillarten.js'));
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
/* @var $skillart \Shop\Models\Skillart */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1 class="fs-1">
    Fähigkeiten
</h1>
<?php
foreach ($this->skillarten as $skillart):
    if (!$skillart->getLearned()) {
        continue;
    }
    if ($skillart->getId() === 3): ?>
        <img src="http://i.imgur.com/QDDjNup.jpg">
    <?php
    endif;
    ?>
    <fieldset style="margin-bottom: 1.5em">
        <legend class="fs-2">
            <?= $purifier->purify($skillart->getBezeichnung()) ?>
        </legend>
        <p>
            <?= $purifier->purify($skillart->getBeschreibung()) ?>
        </p>
        <fieldset>
            <legend class="skillart fs-5" data-id="<?= $skillart->getId() ?>">Fähigkeiten anzeigen</legend>
            <div class="subContent"></div>
        </fieldset>
    </fieldset>
    <hr/>
<?php endforeach; ?>
<div id="dialog"></div>