<?php
/* @var $skill \Shop\Models\Skill */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$countGelernt = 0;
foreach ($this->skills as $skill):
    if($skill->getLearned() === true){
        $countGelernt++;
        continue;
    }
?>
<div class="col-12 p-2">
    <div class="card">
        <div class="card-body">
            <div class="row justify-content-between">
                <div class="col-9">
                    <div class="card-title fs-4">
                        <?= $purifier->purify($skill->getBezeichnung()) ?>
                    </div>
                </div>
                <div class="col-3">
                    <button id="<?= $skill->getId() ?>" class="skill btn btn-primary">
                        Lernen - <?= $skill->getFp() ?> FP
                    </button>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="m-1 text-muted">
                        <?= $purifier->purify($skill->getBeschreibung()) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endforeach;
if(count($this->skills) === $countGelernt){
?>
<p>
    Für dich gibt es gerade keine Fähigkeiten dieser Kategorie.
</p>
<?php } ?>