<?php
/* @var $skill \Shop\Models\Skill */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$countGelernt = 0;
foreach ($this->skills as $skill):
    if($skill->getLearned() === true){
        $countGelernt++;
        continue;
    }
?>
<div>
    <p style="font-weight: bold; margin-top: 10px;">
        <?= $purifier->purify($skill->getBezeichnung()) ?>
    </p>
    <p>
        <?= $purifier->purify($skill->getBeschreibung()) ?>
    </p>
    <div class="unlock">
        <button id="<?= $skill->getId() ?>" class="skill">Fähigkeit lernen - <?= $skill->getFp() ?> FP</button>
    </div>
</div>
<hr />
<?php endforeach;
if(count($this->skills) === $countGelernt){
?>
<p>
    Für dich gibt es gerade keine Fähigkeiten dieser Kategorie.
</p>
<?php } ?>