<?php
/* @var $trait Administration_Model_Trait*/
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Traits
            </h1>
        </div>
    </div>
    <div class="row">
        <?php
        foreach ($this->list as $trait){
        ?>
            <div class="col-4 p-2">
                <div class="card" style="height: 10rem; overflow: auto">
                    <a href="<?= $this->baseUrl() ?>/Administration/trait/show/id/<?= $trait->getTraitId() ?>">
                        <div class="card-body">
                            <div class="card-title fs-3">
                                <?= $purifier->purify($trait->getName()) ?>
                            </div>
                            <div class="text-muted">
                                <?= $purifier->purify(substr($trait->getBeschreibung(), 0, 200)) ?>
                                <?= (strlen($purifier->purify($trait->getBeschreibung())) > 200) ? '...' : '' ?>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
</div>