<?php
/* @var $trait Administration_Model_Trait*/
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<div class="container">
<h1>
    Traits
</h1>
<?php
foreach ($this->list as $trait){
?>
    <div class="row">
        <a href="<?= $this->baseUrl() ?>/Administration/trait/show/id/<?= $trait->getTraitId() ?>">
            <?= $purifier->purify($trait->getName()) ?>
        </a>
    </div>
<?php
}
?>
</div>