<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1>Neuen Trait erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/trait/create" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input id="name" type="text" size="30" name="name" />
            <label for="kosten">Kosten</label>
            <input id="kosten" type="number" name="kosten" />
        </p>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <label for="vorteile">
            Nicht kombinierbar mit den Vorteilen:
        </label>
        <select name="traits[]" multiple="true" size="8">
            <?php foreach ($this->traits as $traitOption) { ?>
            <option value="<?= $traitOption->getTraitId() ?>">
                <?= $traitOption->getName() ?>
            </option>
            <?php } ?>
        </select>
        <br />
        <label for="klassen">
            Nicht kombinierbar mit den Klassen:
        </label>
        <select name="klassen[]" multiple="true" size="8">
            <?php foreach ($this->klassen as $klasse) { ?>
            <option value="<?= $klasse->getId() ?>">
                <?= $klasse->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Vorteil speichern" />
    </div>
</form>