<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1>Neuen Trait erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/trait/create" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input id="name" type="text" size="30" name="name" />
            <label for="kosten">Kosten</label>
            <input id="kosten" type="number" name="kosten" />
        </p>
        <p>
            <label for="isIndividual">Individueller Trait?</label>
            <select name="isIndividual" id="isIndividual">
                <option value="0">Nein</option>
                <option value="1">Ja</option>
            </select>
        </p>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <label for="trait">
            Nicht kombinierbar mit den Traits:
        </label>
        <select name="trait[]" multiple="true" size="8">
            <?php foreach ($this->traits as $traitOption) { ?>
            <option value="<?= $traitOption->getTraitId() ?>">
                <?= $traitOption->getName() ?>
            </option>
            <?php } ?>
        </select>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Vorteil speichern" />
    </div>
</form>