<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
/** @var Administration_Model_Trait $trait */
$trait = $this->trait;
$individual = $trait->isIndividual();
$incompatibleTraitIds = array_map(function (Application_Model_Trait $trait) {
    return $trait->getTraitId();
    },$trait->getIncompatibleTraits()
);
?>
<h1>Trait anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/trait/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $trait->getName() ?>" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" value="<?= $trait->getKosten() ?>" />
        </p>
        <p>
            <label for="isIndividual">Individueller Trait?</label>
            <select name="isIndividual" id="isIndividual">
                <option value="0" <?= $individual ? '' : 'selected=""' ?>>Nein</option>
                <option value="1" <?= $individual ? 'selected=""' : '' ?>>Ja</option>
            </select>
        </p>
        <textarea name="beschreibung" cols="80" rows="10">
            <?= $trait->getBeschreibung() ?>
        </textarea>
        <label for="trait">
            Nicht kombinierbar mit den Traits:
        </label>
        <select name="trait[]" multiple="true" size="8">
            <?php
            foreach ($this->traits as $traitOption) {
                /** @var $traitOption Administration_Model_Trait */
                $selected = '';
                if (in_array($traitOption->getTraitId(), $incompatibleTraitIds)) {
                    $selected = 'selected=""';
                }
            ?>
            <option <?= $selected ?> value="<?= $traitOption->getTraitId() ?>">
                <?= $traitOption->getName() ?>
            </option>
            <?php } ?>
        </select>
    </fieldset>
    <div align="center">
        <input type="hidden" name="traitId" value="<?= $trait->getTraitId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Trait ändern" />
    </div>
</form>