<?php
/* @var $werte Application_Model_CharakterWerte */
$categoryStr = $werte->getCategory('str');
$categoryAgi = $werte->getCategory('agi');
$categoryAus = $werte->getCategory('aus');
$categoryKon = $werte->getCategory('kon');
$categoryDis = $werte->getCategory('dis');
?>
<form method="post" action="<?= $this->baseUrl() ?>/Administration/charakter/editstats" style="margin: 0">
    <input type="hidden" name="charakterId" value="<?= $charakter->getCharakterid() ?>">
    <fieldset>
        <legend>Werte</legend>
        <div>
            <p>
                <label>
                    Stärke
                </label>
                <span>
                    <input type="number" name="staerke" value="<?= $werte->getStaerke() ?>">
                </span>
                <span>
                    <?= $categoryStr->getCategory() ?>
                </span>
            </p>
            <p>
                <label>
                    Agilität
                </label>
                <span>
                    <input type="number" name="agilitaet" value="<?= $werte->getAgilitaet() ?>">
                </span>
                <span>
                    <?= $categoryAgi->getCategory() ?>
                </span>
            </p>
            <p>
                <label>
                    Ausdauer
                </label>
                <span>
                    <input type="number" name="ausdauer" value="<?= $werte->getAusdauer() ?>">
                </span>
                <span>
                    <?= $categoryAus->getCategory() ?>
                </span>
            </p>
            <p>
                <label>
                    Kontrolle
                </label>
                <span>
                    <input type="number" name="kontrolle" value="<?= $werte->getKontrolle() ?>">
                </span>
                <span>
                    <?= $categoryKon->getCategory() ?>
                </span>
            </p>
            <p>
                <label>
                    Disziplin
                </label>
                <span>
                    <input type="number" name="disziplin" value="<?= $werte->getDisziplin() ?>">
                </span>
                <span>
                    <?= $categoryDis->getCategory() ?>
                </span>
            </p>
            <p>
                <label>
                    Übung
                </label>
                <span>
                    <input type="number" name="uebung" value="<?= $werte->getUebung() ?>">
                </span>
            </p>
            <p>
                <label>
                    FP
                </label>
                <span>
                    <input type="number" name="fp" value="<?= $werte->getFp() ?>">
                </span>
            </p>
            <p>
                <label>
                    Bonustage
                </label>
                <span>
                    <input type="number" name="bonustage" value="<?= $werte->getStartpunkte() ?>">
                </span>
            </p>
        </div>
        <input type="submit" value="Werte ändern">
    </fieldset>
</form>