<?php
/** @var Administration_Model_Information[] $informations */
$informations = $this->informations;
$characterInfoIds = array_map(function (Administration_Model_Information $information) {
    return $information->getInformationId();
}, $this->characterInformations);
?>
<fieldset>
    <legend>Info Freigabe <span class="indicator"></span></legend>
    <div class="subContent">
        <form method="post" action="<?= $this->baseUrl() ?>/Administration/charakter/informations">
            <select name="infoIds[]" multiple size="15">
                <?php
                foreach($informations as $information):
                    $selected = '';
                    if (in_array($information->getInformationId(), $characterInfoIds)) {
                        $selected = 'selected=""';
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $information->getInformationId() ?>"><?= $information->getName() ?></option>
                <?php endforeach; ?>
            </select>
            <br />
            <input type="hidden" name="characterId" value="<?= $charakter->getCharakterid() ?>" />
            <input type="submit" value="Infos freigeben" />
        </form>
    </div>
</fieldset>