<?php
$itemCategoryNames = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => [
        'name' => 'Nahkampfwaffen', 'descr' => 'Schöne Waffen zum Draufhauen'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => ['name' => 'Distanzwaffen', 'descr' => 'Pfeile, Bolzen, Patronen'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => ['name' => 'Konzeptwaffen', 'descr' => 'Laser?'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => ['name' => 'Mystic Codes', 'descr' => 'Dunno'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => ['name' => 'Rezepte', 'descr' => 'Was zu futtern.'],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => ['name' => 'Sonstiges', 'descr' => 'Alles mögliche'],
];
$itemCategories = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => [],
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => [],
];
foreach ($charakter->getItems() as $item) {
    $itemCategories[$item->getType()][] = $item;
}
?>
<h1 class="fs-1">Gegenstände</h1>
<?php
foreach ($itemCategories as $key => $category):
    if (count($category) === 0) {
        continue;
    }
    usort(
        $category, function (Application_Model_Item $previous, Application_Model_Item $next) {
        return $previous->getRank() <=> $next->getRank();
    }
    )
    ?>
    <fieldset>
        <legend class="fs-2"><?= $itemCategoryNames[$key]['name'] ?> <span class="indicator"></span></legend>
        <p>
            <?= $itemCategoryNames[$key]['descr'] ?>
        </p>
        <div class="subContent">
            <div class="row">
                <?php foreach ($category as $item): ?>
                    <div class="col-4 p-2">
                        <div class="card" style="height: 12rem; overflow: auto">
                            <div class="card-body">
                                <div class="card-title fs-5">
                                    <?= $this->purify($item->getName()) ?>
                                </div>
                                <div class="card-subtitle text-muted">
                                    Rang: <span class="fw-bold"><?= $this->purify($item->getRank()) ?></span>
                                </div>
                                <div>
                                    <?= $this->purify($item->getDescription()) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </fieldset>
<?php endforeach; ?>