<fieldset>
    <legend>Klasse <span class="indicator"></span></legend>
    <div class="subContent">
        <h4>Klasse - <?= $this->purify($charakter->getKlassengruppe()->getBezeichnung()) ?></h4>
        <p>
            <?= $this->purify($charakter->getKlassengruppe()->getBeschreibung()) ?>
        </p>
        <h4>Unterklasse - <?= $this->purify($charakter->getKlasse()->getBezeichnung()) ?></h4>
        <p>
            <?= $this->purify($charakter->getKlasse()->getBeschreibung()) ?>
        </p>
    </div>
</fieldset>