<fieldset>
    <legend>Profilbild <span class="indicator"></span></legend>
    <div class="subContent">
        <form method="post" action="<?= $this->baseUrl() ?>/charakter/profilpic">
            <input type="text" name="profilpic" placeholder="<?= $purifier->purify($charakter->getCharakterprofil()->getProfilpic()) ?>">
            <input type="submit" value="Profilbild speichern">
        </form>
        <img src="<?= $purifier->purify($charakter->getCharakterprofil()->getProfilpic()) ?>" height="200px" width="200px">
    </div>
</fieldset>