<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Feedback/wishes/ckeditor.js'));
?>
<script src="<?= $this->baseurl ?>/js/ckeditor/ckeditor.js"></script>
<style type="text/css">
    .cke_textarea_inline {
        border: 1px solid #ccc;
        padding: 10px;
        min-height: 300px;
        background: #fff;
        color: #000;
    }
</style>
<h1>Deine Wünsche für das Spiel</h1>
<p>
    Hallo!
</p>
<p>
    Du kannst hier eintragen was du so für die Zukunft von Fate/Alpha wünschst.
</p>
<p>
    Was du hier einträgst können nur die Administratoren (Kirika, Heinrich) sehen.<br />
    Die Einträge sind nicht anonym.
</p>
<div>
    <form method="post" action="<?= $this->baseUrl()?>/Feedback/wishes/create">
        <p>
            <label for="title">Titel</label>
            <input type="text" name="title" id="title" />
        </p>
        <p>
            <label for="description">Dein Wunsch</label>
            <textarea name="description" id="description"></textarea>
        </p>
        <p>
            <input type="submit"/>
        </p>
    </form>
</div>