<?php
$this->headLink()->prependStylesheet($this->autoVersion($this->baseUrl() . '/styles/wish.css'));
/** @var \Feedback\Models\View\Wish[] $wishes */
$wishes = $this->wishes;
/** @var HTMLPurifier $purifier */
$purifier = $this->purifier;
?>
<h1>Spielerwünsche</h1>
<div>
    <?php foreach ($wishes as $wish): ?>
    <div>
        <p class="wishTitle">
            <a href="<?= $this->baseUrl() ?>/Feedback/wishes/show/id/<?= $wish->getId() ?>"><?= $purifier->purify($wish->getTitle()) ?></a>
            <a href="#<?= $wish->getId() ?>">#<?= $wish->getId() ?></a>
        </p>
        <p>Eingereicht von: <?= $wish->getSender() ?> am: <?= $wish->getDate() ?></p>
        <div class="wishDescription"><?= $purifier->purify($wish->getDescription()) ?></div>
    </div>
    <hr />
    <?php endforeach; ?>
</div>