<?php
/** @var \Feedback\Models\Wish[] $wishes */
$wishes = $this->wishes;
/** @var HTMLPurifier $purifier */
$purifier = $this->purifier;
?>
<h1>Spielerwünsche</h1>
<div>
    <?php foreach ($wishes as $wish): ?>
    <div>
        <a href="<?= $this->baseUrl() ?>/Feedback/wishes/show/id/<?= $wish->getWishId() ?>"><?= $purifier->purify($wish->getTitle()) ?></a>
        <a href="#<?= $wish->getWishId() ?>">#</a>
        <p><?= $wish->getCreationDatetime() ?></p>
        <p><?= $purifier->purify($wish->getDescription()) ?></p>
    </div>
    <hr />
    <?php endforeach; ?>
</div>