<?php
/** @var \Feedback\Models\View\Wish[] $wishes */
$wishes = $this->wishes;
/** @var HTMLPurifier $purifier */
$purifier = $this->purifier;
?>
<h1>Spielerwünsche</h1>
<div>
    <?php foreach ($wishes as $wish): ?>
    <div>
        <a href="<?= $this->baseUrl() ?>/Feedback/wishes/show/id/<?= $wish->getId() ?>"><?= $purifier->purify($wish->getTitle()) ?></a>
        <a href="#<?= $wish->getId() ?>">#<?= $wish->getId() ?></a>
        <p>Eingereicht von: <?= $wish->getSender() ?> am: <?= $wish->getDate() ?></p>
        <p><?= $purifier->purify($wish->getDescription()) ?></p>
    </div>
    <hr />
    <?php endforeach; ?>
</div>