<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1>Neuen Nachteil erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/nachteil/create" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" />
        </p>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <label for="nachteile">
            Nicht kombinierbar mit den Nachteilen:
        </label>
        <select name="nachteile[]" multiple="true" size="8">
            <?php foreach ($this->nachteile as $nachteilOption) { ?>
            <option value="<?= $nachteilOption->getId() ?>">
                <?= $nachteilOption->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
        <br />
        <label for="vorteile">
            Nicht kombinierbar mit den Vorteilen:
        </label>
        <select name="vorteile[]" multiple="true" size="8">
            <?php foreach ($this->vorteile as $vorteilOption) { ?>
            <option value="<?= $vorteilOption->getId() ?>">
                <?= $vorteilOption->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
        <br />
        <label for="klassen">
            Nicht kombinierbar mit den Klassen:
        </label>
        <select name="klassen[]" multiple="true" size="8">
            <?php foreach ($this->klassen as $klasse) { ?>
            <option value="<?= $klasse->getId() ?>">
                <?= $klasse->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Nachteil speichern" />
    </div>
</form>