<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$nachteil = $this->nachteil;
?>
<h1>Nachteil anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/nachteil/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $nachteil->getBezeichnung() ?>" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" value="<?= $nachteil->getKosten() ?>" />
        </p>
        <textarea name="beschreibung" cols="80" rows="10">
            <?= $nachteil->getBeschreibung() ?>
        </textarea>
        <label for="nachteile">
            Nicht kombinierbar mit den Nachteilen:
        </label>
        <select name="nachteile[]" multiple="true" size="8">
            <?php foreach ($this->nachteile as $nachteilOption) { ?>
            <option value="<?= $nachteilOption->getId() ?>">
                <?= $nachteilOption->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
        <br />
        <label for="vorteile">
            Nicht kombinierbar mit den Vorteilen:
        </label>
        <select name="vorteile[]" multiple="true" size="8">
            <?php foreach ($this->vorteile as $vorteil) { ?>
            <option value="<?= $vorteil->getId() ?>">
                <?= $vorteil->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
        <br />
        <label for="klassen">
            Nicht kombinierbar mit den Klassen:
        </label>
        <select name="klassen[]" multiple="true" size="8">
            <?php foreach ($this->klassen as $klasse) { ?>
            <option value="<?= $klasse->getId() ?>">
                <?= $klasse->getBezeichnung() ?>
            </option>
            <?php } ?>
        </select>
    </fieldset>
    <div align="center">
        <input type="hidden" name="nachteilId" value="<?= $nachteil->getId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Nachteil ändern" />
    </div>
</form>