<?php
/* @var $nachrichten \Nachrichten\Models\Message[] */
$nachrichten = $this->nachrichten;
?>
<h1>
    Archiv
</h1>
<?php include __DIR__ . '/../partials/submenu.phtml'; ?>
<div class="row m-2 g-0 p-1">
    <div class="col-4">
        Betreff
    </div>
    <div class="col-4">
        Empfänger
    </div>
    <div class="col-4">
        Datum
    </div>
</div>
<?php
foreach ($nachrichten as $nachricht):
    $subject = $nachricht->getBetreff() !== ''
        ? $this->purify($nachricht->getBetreff())
        : 'Nachricht von: ' . $this->purify($nachricht->getVerfasser()->getProfilname());
    ?>
    <div class="row m-2 g-0 p-1">
        <div class="col-4">
            <a href="<?= $this->baseUrl() ?>/Nachrichten/index/show/id/<?= $nachricht->getId() ?>">
                <?= $subject ?>
            </a>
        </div>
        <div class="col-4">
            <?= $this->purify($nachricht->getEmpfaenger()->getProfilname()) ?>
        </div>
        <div class="col-4">
            <?= $nachricht->getCreationDate() ?>
        </div>
        <hr />
    </div>
<?php endforeach; ?>