<?php
/* @var $nachricht \Nachrichten\Models\Message */
$nachricht = $this->nachricht;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Nachricht
</h1>
<div class="submenu">
    <?php include __DIR__ . '/../partials/submenu.phtml'; ?>
</div>
<div class="row">

</div>
<fieldset id="nachrichtencenter">
    <legend>
        <?= $purifier->purify($nachricht->getBetreff()) ?>
    </legend>
    <p class="details">
        <span>
            von: <?= ($nachricht->getAdmin() === false) ? $purifier->purify($nachricht->getVerfasser()->getProfilname()) : 'Admin' ?>
        </span>
        <span>
            gesendet am: <?= $nachricht->getCreationDate() ?>
        </span>
        <span>
            an: <?= $purifier->purify($nachricht->getEmpfaenger()->getProfilname()) ?>
        </span>
    </p>
    <div class="message">
        <?= $purifier->purify($nachricht->getNachricht()) ?>
    </div>
    <?php if($nachricht->getAdmin() === false): ?>
    <a href="<?= $this->baseUrl() ?>/Nachrichten/outbox/new/id/<?= $nachricht->getId() ?>">
        <button class="btn btn-primary">
            Antworten
        </button>
    </a>
    <?php endif; ?>
</fieldset>