<?php
/** @var $charaData Application_Model_Charakter */
$hasChara = $layoutData->getHasChara();

if ($hasChara) {
    $werte = $charaData->getCharakterWerte();
    $categoryStr = $werte->getCategory('str');
    $categoryAgi = $werte->getCategory('agi');
    $categoryAus = $werte->getCategory('aus');
    $categoryKon = $werte->getCategory('kon');
    $categoryDis = $werte->getCategory('dis');
    $categoryPra = $werte->getCategory('pra');

    $training = $layoutData->getCharakterTraining() === null
        ? '-'
        : $layoutData->getCharakterTraining()->getName() . ' (' . $layoutData->getCharakterTraining()->getRemainingDuration() . ' Tage)';
}

?>
<div class="container-fluid border-dark border-left-0">
    <?php if(!$hasChara): ?>
    <div class="row">
        <p class="Meldung">Du hast noch keinen Charakter erstellt.</p>
        <p class="Meldung"><a href="<?= $this->baseUrl() ?>/Erstellung/creation">Zur Charaktererstellung</a></p>
    </div>
    <?php endif; ?>

    <?php if($hasChara): ?>
        <h2>
            <a href="<?= $this->baseUrl() ?>/charakter"><?= $charaData->getVorname() . ' ' . $charaData->getNachname(); ?></a>
        </h2>
        <div class="row">
            <p>Aktuelles Training: <br /><?= $training ?></p>
        </div>

        <div class="row">
            <a class="imageSwitch" id="training" href="<?= $this->baseUrl() ?>/training">Training</a>
        </div>
        <div class="row">
            <a class="imageSwitch" id="magic" href="<?= $this->baseUrl() ?>/Shop/magie">Magie</a>
        </div>
        <div class="row">
            <a class="imageSwitch" id="skill" href="<?= $this->baseUrl() ?>/Shop/skill">Fähigkeiten</a>
        </div>
        <div class="row">
            <a class="imageSwitch" id="items" href="<?= $this->baseUrl() ?>/Shop/item">Shop</a>
        </div>
        <div class="row">
            <a class="imageSwitch" id="friends" href="<?= $this->baseUrl() ?>/freunde">Freunde</a>
        </div>
        <hr/>
        <ul class="list-group-flush p-0">
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Stärke</span>
                <span><?= floor($werte->getStaerke()) ?> <?= $categoryStr->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Agilität</span>
                <span><?= floor($werte->getAgilitaet()) ?> <?= $categoryAgi->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Ausdauer</span>
                <span><?= floor($werte->getAusdauer()) ?> <?= $categoryAus->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Kontrolle</span>
                <span><?= floor($werte->getKontrolle()) ?> <?= $categoryKon->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Disziplin</span>
                <span><?= floor($werte->getDisziplin()) ?> <?= $categoryDis->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>Übung</span>
                <span><?= floor($werte->getUebung()) ?> <?= $categoryPra->getCategory() ?></span>
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-start p-0 bg-transparent">
                <span>FP</span>
                <span><?= floor($werte->getFp()) ?></span>
            </li>
        </ul>
    <?php endif; ?>
</div>
