<?php
$dayWeather = $layoutData->getWeather();
$currentDateTime = new DateTime();
if ($currentDateTime->format('H') <= 11) {
    $currentWeather = $dayWeather->getWetterVormittag();
    $time = 'Tag';
}
if ($currentDateTime->format('H') > 11 && $currentDateTime->format('H') <= 14) {
    $currentWeather = $dayWeather->getWetterMittag();
    $time = 'Tag';
}
if ($currentDateTime->format('H') > 14 && $currentDateTime->format('H') <= 18) {
    $currentWeather = $dayWeather->getWetterNachmittag();
    $time = 'Tag';
}
if ($currentDateTime->format('H') > 18 && $currentDateTime->format('H') <= 21) {
    $currentWeather = $dayWeather->getWetterAbend();
    $time = 'Abend';
}
if ($currentDateTime->format('H') > 21 && $currentDateTime->format('H') <= 24) {
    $currentWeather = $dayWeather->getWetterNacht();
    $time = 'Nacht';
}
?>
<div class="compact">Ausklappen</div>
<div class="full">
    <div class="row">
        <div class="col">
            <h3>Fuyuki-City</h3>
        </div>
        <div class="col">
            <img id="weatherIcon" height="40px" width="40px" src="<?= $this->baseUrl() ?>/images/Wetter/<?= $time . '/' . $currentWeather->getName() ?>.jpg" />
        </div>

    </div>
    <hr />
    <div class="row">
        <a href="<?= $this->baseUrl() ?>/index/news">Fuyuki-News</a>
    </div>
    <div class="row">
        <a href="<?= $this->baseUrl() ?>/index/wetter">Wetterbericht</a>
    </div>
    <div class="row">
        <a href="#" class="showMap">Stadtkarte</a>
    </div>
    <div class="row">
        <a href="<?= $this->baseUrl() ?>/Nachrichten">
            Nachrichtencenter <?= ($layoutData->getUnreadPmCount() > 0) ? ' (' . $layoutData->getUnreadPmCount() . '&#9993;)' : '' ?>
        </a>
    </div>
    <div class="row">
        <a href="<?= $this->baseUrl() ?>/information">Informationen</a>
    </div>
</div>