<p></p>
<h3>Fuyuki-City</h3>
<ul style="list-style-type: none;">
    <li><a href="<?= $this->baseUrl() ?>/index/news">Fuyuki-News</a></li>
    <li><a href="<?= $this->baseUrl() ?>/index/wetter">Wetterbericht</a></li>
    <li><a href="" id="showMap">Stadtkarte</a></li>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten">
            Nachrichtencenter <?= ($layoutData->getUnreadPmCount() > 0) ? ' (' . $layoutData->getUnreadPmCount() . '&#9993;)' : '' ?>
        </a>
    </li>
    
    <li>
        <a href="<?= $this->baseUrl() ?>/information">Informationen</a>
    </li>
</ul>