<p></p>
<h3>Fuyuki-City</h3>
<ul style="list-style-type: none;">
    <li><a href="<?= $this->baseUrl() ?>/index/news">Fuyuki-News</a></li>
    <li><a href="<?= $this->baseUrl() ?>/index/wetter">Wetterbericht</a></li>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten">
            Nachrichtencenter <?= ($layoutData->getUnreadPmCount() > 0) ? ' (' . $layoutData->getUnreadPmCount() . '&#9993;)' : '' ?>
        </a>
    </li>
    <?php if ($layoutData->getUsergruppe() === 'Admin') { ?>
        <li><br /></li>
        <li><br /></li>
        <li><hr /></li>
        <li>
            <a href="<?= $this->baseUrl() ?>/Administration">Admincenter</a>
        </li>
    <?php } ?> 
</ul>