<p></p>
<h3>Fuyuki-City</h3>
<ul style="list-style-type: none;">
    <li><a href="<?= $this->baseUrl() ?>/news">Fuyuki-News</a></li>
    <li><a href="<?= $this->baseUrl() ?>/wetter">Wetterbericht</a></li>
    <?php if ($layoutData->getUsergruppe() === 'Admin') { ?>
        <li><br /></li>
        <li><br /></li>
        <li><hr /></li>
        <li>
            <a href="<?= $this->baseUrl() ?>/admin">Admincenter</a>
        </li>
    <?php } ?> 
</ul>