<?php
$lastKategorie = null;
?>
<ul>
    <li><a href="<?= $this->baseUrl() ?>/index">News</a></li>
    <li>
        <a href="" onclick="return false;">
            Profil
        </a>
        <ul>
            <li><a href="<?= $this->baseUrl() ?>/charakter">Charakter</a></li>
            <li><a href="<?= $this->baseUrl() ?>/user">Spieler</a></li>
        </ul>
    </li>
    <li class="mega-dropdown">
        <a href="" onclick="return false;">Informationen</a>
        <ul class="megamenu">
            <?php
            /* @var $information Application_Model_Information */
            foreach ($this->layoutData->getInformations() as $information){
                if($lastKategorie !== $information->getKategorie()){
                    if($lastKategorie !== null){
                        echo '</div>';
                    }
                    echo '<div class="column"><h4>' . $information->getKategorie() . '</h4>';
                    $lastKategorie = $information->getKategorie();
                }
            ?>
                <li>
                    <a 
                        href="<?= $this->baseUrl() ?>/index/information/id/<?= $information->getInformationId() ?>" 
                        title="<?= $this->purifier->purify($information->getName()) ?>">
                        <?= $this->purifier->purify($information->getName())?>
                    </a>
                </li>
            <?php 
            }
            if($lastKategorie !== null){
                echo '</div>';
            }
            ?>
        </ul>
    </li>
    <li><a href="http://alpha.mainchat.de/" target="_blank">Chat</a></li>
    <li>
        <a href="" onclick="return false;">Community</a>
        <ul>
            <li><a href="http://fate-alpha.forumprofi.de/index.php" target="_blank">Forum</a></li>
            <li><a href="<?= $this->baseUrl() ?>/Gruppen">Spielergruppen</a></li>
            <!--<li><a href="<?= $this->baseUrl() ?>/npc">NPCs</a></li>-->
        </ul>
    </li>
    <li><a href="<?= $this->baseUrl() ?>/freunde">Userliste</a></li>
</ul>