<ul>
    <li><a href="<?= $this->baseUrl() ?>/index">Startseite</a></li>
    <li>
        <a href="" onclick="return false;">Informationen</a>
        <ul>
            <li><a href="<?= $this->baseUrl() ?>/changelog">Changelog</a></li>
            <?php
//                                    foreach ($Informationen as $Information){
//                                        echo '<li><a href="Informationen.php?ID='.$Information['ID'].'">'.htmlentities($Information['Name']).'</a></li>';
//                                    }
            ?>
        </ul>
    </li>
    <li>
        <a href="" onclick="return false;">Community</a>
        <ul>
            <li><a href="http://fate-alpha.forumprofi.de/index.php" target="_blank">Forum</a></li>
            <li><a href="http://alpha.mainchat.de/" target="_blank">Chat</a></li>
            <li><a href="<?= $this->baseUrl() ?>/user/gruppen">Spielergruppen</a></li>
            <li><a href="<?= $this->baseUrl() ?>/npc">NPCs</a></li>
        </ul>
    </li>
    <li><a href="<?= $this->baseUrl() ?>/Freunde">Userliste</a></li>
    <li>
        <a href="" onclick="return false;">
            Profil   
            <?php
            if ($layoutData->getUnreadPmCount() > 0) {
                echo ' (' . $layoutData->getUnreadPmCount() . '&#9993;)';
            }
            ?>
        </a>
        <ul>
            <li><a href="<?= $this->baseUrl() ?>/charakter">Charakter</a></li>
            <li><a href="<?= $this->baseUrl() ?>/user">Spieler</a></li>
            <li><a href="<?= $this->baseUrl() ?>/pm">Nachrichten</a></li>

        </ul>
    </li>
    <li><a href="<?= $this->baseUrl() ?>/login/logout">Logout</a></li>
</ul>