<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
/* @var $item Administration_Model_Item */
/* @var $magieOption Administration_Model_Magie */
/* @var $element Administration_Model_Element */
/* @var $schule Administration_Model_Schule */
/* @var $requirement Administration_Model_Requirement */
$item = $this->item;
$lernbedingungen = [
    'Standard',
    'RPG-Ereignis',
    'Lehrer',
];
$raenge = ['EX','A','B','C','D','E','F','EA','EB','EC','ED','EE','EF',];

$elementReq = explode('|', $item->getRequirementList()->getRequirementByKey('Element')->getRequiredValue());
$magienReq = explode('|', $item->getRequirementList()->getRequirementByKey('Magie')->getRequiredValue());
$schuleReq = explode('|', $item->getRequirementList()->getRequirementByKey('Schule')->getRequiredValue());
$faehigkeitenReq = explode('|', $item->getRequirementList()->getRequirementByKey('Faehigkeit')->getRequiredValue());
$gruppenReq = explode('|', $item->getRequirementList()->getRequirementByKey('Gruppe')->getRequiredValue());
$klasseReqitReq = explode('|', $item->getRequirementList()->getRequirementByKey('Klasse')->getRequiredValue());
$traitReq = explode('|', $item->getRequirementList()->getRequirementByKey('Trait')->getRequiredValue());
$characterReq = explode('|', $item->getRequirementList()->getRequirementByKey('Character')->getRequiredValue());
$skillsAny = explode('|', $item->getRequirementList()->getRequirementByKey('FaehigkeitAny')->getRequiredValue());
$magieAny = explode('|', $item->getRequirementList()->getRequirementByKey('MagieAny')->getRequiredValue());
$magieschulenAny = explode('|', $item->getRequirementList()->getRequirementByKey('SchulenAny')->getRequiredValue());

$reqClasses = explode('|', $item->getRequirementList()->getRequirementByKey('Klasse')->getRequiredValue());
$reqGroups = explode('|', $item->getRequirementList()->getRequirementByKey('Gruppe')->getRequiredValue());
$types = [
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MELEE => 'Waffe - Nahkampf',
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RANGED => 'Waffe - Fernkampf',
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_CONCEPT => 'Waffe - Konzept',
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MYSTIC => 'Waffe - Mystic Codes',
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_RECIPE => 'Rezepte',
    \Shop\Models\Itemtypes::ITEMTYPE_WEAPON_MISC => 'Sonstiges',
];
$days = [
    1 => 'Montag',
    2 => 'Dienstag',
    3 => 'Mittwoch',
    4 => 'Donnerstag',
    5 => 'Freitag',
    6 => 'Samstag',
    7 => 'Sonntag',
];
/** @var HTMLPurifier $purifier */
$purifier = $this->purifier;
/** @var Application_Model_Charakter $characters */
$characters = $this->characters;
?>
<h1 class="fs-2">Item anpassen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/item/edit" method="post">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="name">Name</label>
            <input class="form-control" type="text" size="30" name="name" id="name" value="<?= $item->getName() ?>" />
        </div>
        <div class="col-4">
            <label class="form-label" for="bedingung">Kaufbedingung</label>
            <select class="form-select" name="bedingung" id="bedingung">
                <option <?= $item->getBedingung() === 'Standard' ? 'selected=""' : '' ?>>Standard</option>
                <option <?= $item->getBedingung() === 'RPG' ? 'selected=""' : '' ?>>RPG</option>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="characters">Nur für</label>
            <select class="form-select" name="characters[]" id="characters" multiple size="7">
                <?php
                foreach ($characters as $character):
                    $selected = '';
                    if (in_array($character->getCharakterid(), $characterReq)) {
                        $selected = 'selected=""';
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $character->getCharakterid() ?>"><?= $purifier->purify($character) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="discountDays">Rabatt-Tage</label>
            <select class="form-select" name="discountDays[]" id="discountDays" multiple size="7">
                <?php
                foreach ($days as $key => $day):
                    $selected = in_array($key, $item->getDiscountDays()) ? 'selected=""' : '';
                ?>
                    <option <?= $selected ?> value="<?= $key ?>"><?= $day ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="type">Item Art</label>
            <select class="form-select" id="type" name="type">
                <?php
                foreach ($types as $key => $type):
                    $selected = $key === $item->getType() ? 'selected=""' : '';
                ?>
                <option <?= $selected ?> value="<?= $key ?>"><?= $type ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="fp">FP-Kosten</label>
            <input class="form-control" id="fp" type="number" name="fp" value="<?= $item->getCost() ?>"/>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="rang">
                Rang
            </label>
            <select class="form-select" id="rang" name="rang">
                <?php foreach($raenge as $rang): ?>
                    <option <?= ($item->getRank() == $rang) ? 'selected=""' : '' ?>><?= $rang ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>


    <?= $this->partial('partials/values.phtml', ['requirementList' => $item->getRequirementList()]) ?>

    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="magieschule">
                Eine von diesen Magieschulen:
            </label>
            <select class="form-select" id="magieschule" name="magieschulenAny[]" multiple="true" size="5">
                <?php foreach ($this->schulen as $schule):
                    $selected = in_array($schule->getId(), $magieschulenAny) ? 'selected=""' : '';
                    ?>
                    <option value="<?= $schule->getId() ?>" <?= $selected ?>>
                        <?= $schule->getBezeichnung() ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="gruppen" style="vertical-align: top">
                Klassengruppen:
            </label>
            <select class="form-select" id="gruppen" name="gruppen[]" multiple="true" size="5">
                <?php
                foreach ($this->klassengruppen as $gruppe) {
                    $selected = in_array($gruppe->getId(), $reqGroups) ? 'selected' : '';
                    ?>
                    <option <?= $selected ?> value="<?= $gruppe->getId() ?>">
                        <?= $gruppe->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="klassen" style="vertical-align: top">
                Klassen:
            </label>
            <select class="form-select" id="klassen" name="klassen[]" multiple="true" size="5">
                <?php foreach ($this->klassen as $klasse) {
                    $selected = in_array($klasse->getId(), $reqClasses) ? 'selected' : '';
                    ?>
                    <option <?= $selected ?> value="<?= $klasse->getId() ?>">
                        <?= $klasse->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="trait">
                Nicht kombinierbar mit den Traits:
            </label>
            <select class="form-select" id="trait" name="trait[]" multiple="true" size="8">
                <?php foreach ($this->traits as $trait) {
                    $selected = in_array($trait->getTraitId(), $traitReq) ? 'selected' : '';
                    ?>
                    <option <?= $selected ?>  value="<?= $trait->getTraitId() ?>">
                        <?= $trait->getName() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="skills" style="vertical-align: top">
                Fähigkeiten:
            </label>
            <select class="form-select" id="skills" name="skills[]" multiple="true" size="8">
                <?php foreach ($this->skills as $listedSkill) {
                    $selected = '';
                    foreach ($item->getRequirementList()->getRequirementArrayByKey('Faehigkeit') as $reqSkill) {
                        if($reqSkill->getRequiredValue() == $listedSkill->getId()){
                            $selected = 'selected="true"';
                        }
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $listedSkill->getId() ?>">
                        <?= $listedSkill->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="skillsAny" style="vertical-align: top">
                Irgendeine von diesen Fähigkeiten:
            </label>
            <select class="form-select" name="skillsAny[]" id="skillsAny" multiple="true" size="8">
                <?php foreach ($this->skills as $listedSkill) {
                    $selected = '';
                    if(in_array($listedSkill->getId(), $skillsAny)){
                        $selected = 'selected="true"';
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $listedSkill->getId() ?>">
                        <?= $listedSkill->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="skillsIncompatible" style="vertical-align: top">
                Nicht kombinierbar mit:
            </label>
            <select class="form-select" id="skillsIncompatible" name="skillsIncompatible[]" multiple="true" size="8">
                <?php foreach ($this->skills as $listedSkill) {
                    $selected = '';
                    foreach ($item->getRequirementList()->getRequirementArrayByKey('FaehigkeitInc') as $reqSkill) {
                        if($reqSkill->getRequiredValue() == $listedSkill->getId()){
                            $selected = 'selected="true"';
                        }
                    }
                    ?>
                    <option <?= $selected ?>  value="<?= $listedSkill->getId() ?>">
                        <?= $listedSkill->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="magien" style="vertical-align: top">
                Magien:
            </label>
            <select class="form-select" name="magien[]" id="magien" multiple="true" size="8">
                <?php foreach ($this->magien as $listedMagie) {
                    $selected = '';
                    foreach ($item->getRequirementList()->getRequirementArrayByKey('Magie') as $reqSkill) {
                        if($reqSkill->getRequiredValue() == $listedMagie->getId()){
                            $selected = 'selected="true"';
                        }
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $listedMagie->getId() ?>">
                        <?= $listedMagie->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="magienAny" style="vertical-align: top">
                Irgendeine von diesen Magien:
            </label>
            <select class="form-select" name="magienAny[]" id="magienAny" multiple="true" size="8">
                <?php foreach ($this->magien as $listedMagie) {
                    $selected = '';
                    if(in_array($listedMagie->getId(), $magieAny)){
                        $selected = 'selected="true"';
                    }
                    ?>
                    <option <?= $selected ?> value="<?= $listedMagie->getId() ?>">
                        <?= $listedMagie->getBezeichnung() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-12">
            <textarea class="form-control" name="beschreibung" cols="80" rows="10"><?= $purifier->purify($item->getDescription()) ?></textarea>
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="hidden" name="itemId" value="<?= $item->getId() ?>">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Item ändern" />
        </div>
    </div>
</form>