<?php
/** @var Application_Model_Klasse[] $classes */
$classes = $this->classes;
?>
<label for="klassen" style="vertical-align: top">
    Klassen:
</label>
<select name="klassen[]" id="klassen" multiple="true" size="5">
    <?php foreach ($classes as $class) {
        $selected = in_array($class->getId(), $this->ids) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $class->getId() ?>">
            <?= $this->purify($class->getBezeichnung()) ?>
        </option>
    <?php } ?>
</select>