<?php
/** @var Application_Model_Klasse[] $classes */
$classes = $this->classes;
?>
<label class="form-label" for="klassen">
    Klassen:
</label>
<select class="form-select" name="klassen[]" id="klassen" multiple="true" size="5">
    <?php foreach ($classes as $class) {
        $selected = in_array($class->getId(), $this->requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::SKILL)) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $class->getId() ?>">
            <?= $this->purify($class->getBezeichnung()) ?>
        </option>
    <?php } ?>
</select>