<?php
/** @var Application_Model_Klassengruppe[] $groups */
$groups = $this->groups;
?>
<label class="form-label" for="gruppen" style="vertical-align: top">
    Klassengruppen:
</label>
<select class="form-select" name="gruppen[]" id="gruppen" multiple="" size="5">
    <?php
    foreach ($groups as $group) {
        $selected = in_array($group->getId(), $this->requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::GROUP)) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $group->getId() ?>">
            <?= $this->purify($group->getBezeichnung()) ?>
        </option>
    <?php } ?>
</select>