<?php
/** @var Application_Model_Magie[] $magic */
$magics = $this->magic;
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $this->requirementList;
?>
<label class="form-label" for="magien">
    Magien:
</label>
<select class="form-select" name="magien[]" id="magien" multiple="true" size="8">
    <?php foreach ($magics as $magic) {
        $selected = in_array(
            $magic->getId(),
            $requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::MAGIC)
        ) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $magic->getId() ?>">
            <?= $this->purify($magic->getBezeichnung()) ?>
        </option>
    <?php } ?>
</select>