<?php
/** @var Application_Model_Schule[] $school */
$schools = $this->schulen;
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $this->requirementList;
?>
<label for="schule">
    Magieschule
</label>
<select name="schule" id="schule">
    <?php foreach ($schools as $school) {
    $selected = in_array(
        $school->getId(),
        $requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::SCHOOL)
    ) ? 'selected' : '';
    ?>
        <option <?= $selected ?>  value="<?= $schools->getId() ?>">
            <?= $this->purify($schools->getBezeichnung()) ?>
        </option>
    <?php } ?>
</select>