<?php
/** @var Application_Model_Skill[] $skills */
$skills = $this->skills;
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $this->requirementList;
?>
<label for="skills" style="vertical-align: top">
    Fähigkeiten:
</label>
<select name="skills[]" multiple="true" size="8">
    <?php foreach ($skills as $listedSkill) {
        $selected = in_array(
            $listedSkill->getId(),
            $requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::SKILL)
        ) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $listedSkill->getId() ?>">
            <?= $listedSkill->getBezeichnung() ?>
        </option>
    <?php } ?>
</select>