<?php
/** @var Application_Model_Skill[] $skills */
$skills = $this->skills;
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $this->requirementList;
?>
<label class="form-label" for="skillsAny" >
    Irgendeine von diesen Fähigkeiten:
</label>
<select class="form-select" name="skillsAny[]" id="skillsAny" multiple="" size="8">
    <?php foreach ($skills as $listedSkill) {
        $selected = in_array(
            $listedSkill->getId(),
            $requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::SKILL_ANY)
        ) ? 'selected' : '';
        ?>
        <option <?= $selected ?> value="<?= $listedSkill->getId() ?>">
            <?= $listedSkill->getBezeichnung() ?>
        </option>
    <?php } ?>
</select>