<?php
/** @var Application_Model_Trait[] $traits */
$traits = $this->traits;
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $this->requirementList;
?>
<label class="form-label" for="trait">
    Keinen von diesen Traits:
</label>
<select class="form-select" name="traitIncompatible[]" id="traits" multiple="" size="8">
    <?php foreach ($this->traits as $trait) {
        $selected = in_array(
            $trait->getTraitId(),
            $requirementList->getRequirementValuesByKey(Application_Model_Requirements_Types::TRAIT_INC)
        ) ? 'selected' : '';
        ?>
        <option <?= $selected ?>  value="<?= $trait->getTraitId() ?>">
            <?= $this->purify($trait->getName()) ?>
        </option>
    <?php } ?>
</select>