<?php
/** @var Administration_Model_Requirementlist $rl */
$rl = $this->requirementList;
?>
<div class="row m-3">
    <div class="col-4">
        <label class="form-label" for="uebung">
            benötigte Übung
        </label>
        <input class="form-control" id="uebung" type="number" name="uebung" value="<?= $rl->get('Uebung')->getRequiredValue() ?>" />
    </div>
    <div class="col-4">
        <label class="form-label" for="disziplin">
            benötigte Disziplin
        </label>
        <input class="form-control" id="disziplin" type="number" name="disziplin" value="<?= $rl->get('Disziplin')->getRequiredValue() ?>" />
    </div>
</div>

<div class="row m-3">
    <div class="col-4">
        <label class="form-label" for="staerke">Stärke</label>
        <input class="form-control" type="number" size="30" name="staerke" id="staerke" value="<?= $rl->get('Staerke')->getRequiredValue() ?>" />
    </div>
    <div class="col-4">
        <label class="form-label" for="agilitaet">Agilität</label>
        <input class="form-control" type="number" size="30" name="agilitaet" id="agilitaet" value="<?= $rl->get('Agilitaet')->getRequiredValue() ?>" />
    </div>
</div>
<div class="row m-3">
    <div class="col-4">
        <label class="form-label" for="ausdauer">Ausdauer</label>
        <input class="form-control" type="number" size="30" name="ausdauer" id="ausdauer" value="<?= $rl->get('Ausdauer')->getRequiredValue() ?>" />
    </div>
    <div class="col-4">
        <label class="form-label" for="kontrolle">Kontrolle</label>
        <input class="form-control" type="number" size="30" name="kontrolle" id="kontrolle" value="<?= $rl->get('Kontrolle')->getRequiredValue() ?>" />
    </div>
</div>
