<?php
/* @var $schule Administration_Model_Schule */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Magieschulen
</h1>
<?php
foreach ($this->list as $schule){
?>
<a href="<?= $this->baseUrl() ?>/Administration/schule/show/id/<?= $schule->getId() ?>">
    <fieldset>
        <p>
            <?= $purifier->purify($schule->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify(substr($schule->getBeschreibung(), 0, 100)) ?>
            <?= (strlen($schule->getBeschreibung()) > 100) ? '...' : '' ?>
        </p>
    </fieldset>
</a>
<?php
}