<?php
/* @var $vorteil Administration_Model_Vorteil */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Nachteile
</h1>
<?php
foreach ($this->list as $vorteil){
?>
<a href="<?= $this->baseUrl() ?>/Administration/schule/show/id/<?= $vorteil->getId() ?>">
    <fieldset>
        <p>
            <?= $purifier->purify($vorteil->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify(substr($vorteil->getBeschreibung(), 0, 100)) ?>
            <?= (strlen($vorteil->getBeschreibung()) > 100) ? '...' : '' ?>
        </p>
    </fieldset>
</a>
<?php
}