<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/formular.js'));
/* @var $schule Administration_Model_Schule */
$schule = $this->schule;
foreach ($schule->getRequirementList()->getRequirements() as $requirement) {
    if($requirement->getArt() === 'Trait'){
        $traitReq = explode('|', $requirement->getRequiredValue());
    }
}
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $schule->getRequirementList();
$organizations = [
    0 => 'Keine Organisation',
    Application_Model_MagiOrganization::CLOCK_TOWER => 'Clock Tower',
    Application_Model_MagiOrganization::ATLAS => 'Atlas',
    Application_Model_MagiOrganization::WANDERING_SEA => 'Wandering Sea',
    Application_Model_MagiOrganization::CHURCH => 'Glaubenstypen',
];
?>
<h1>Magieschule anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/schule/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $schule->getBezeichnung() ?>" />
        </p>
        <p>
            <label for="MagiOrganization">Magi Organisation</label>
            <select name="MagiOrganization" id="MagiOrganization">
                <?php foreach ($organizations as $key => $organization) {
                    $selected = '';
                    if ($key === $schule->getMagiOrganization()) {
                        $selected = 'selected=""';
                    }
                ?>
                    <option value="<?= $key ?>" <?= $selected ?>><?= $organization ?></option>
                <?php } ?>
            </select>
        </p>
        <textarea name="beschreibung" cols="80" rows="10"><?= $schule->getBeschreibung() ?></textarea>
        <fieldset>
            <legend>
                Vorraussetzungen
            </legend>
            <?= $this->partial('partials/values.phtml', ['requirementList' => new Administration_Model_Requirementlist()]) ?>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/groups.phtml', ['groups' => $this->klassengruppen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/classes.phtml', ['classes' => $this->klassen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <div>
                <?= $this->partial('partials/traits.phtml', ['traits' => $this->traits, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
            </div>
            <div>
                <div style="width: 50%; display: inline-block; vertical-align: top">
                    <?= $this->partial('partials/skills.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/skillsAny.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/magic.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/magicAny.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <label for="trait">
                Nicht kombinierbar mit den Traits:
            </label>
            <select name="trait[]" multiple="true" size="8">
                <?php foreach ($this->traits as $trait) {
                    $selected = in_array($trait->getTraitId(), $traitReq) ? 'selected' : '';
                    ?>
                    <option <?= $selected ?>  value="<?= $trait->getTraitId() ?>">
                        <?= $trait->getName() ?>
                    </option>
                <?php } ?>
            </select>
        </p>
        </fieldset>
    </fieldset>
    <div align="center">
        <input type="hidden" name="schuleId" value="<?= $schule->getId() ?>" />
        <input type="submit" name="Abschicken" id="Abschicken" value="Magieschule speichern" />
    </div>
</form>