<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/formular.js'));
/* @var $schule Administration_Model_Schule */
$schule = $this->schule;

$traitReq = [];
foreach ($schule->getRequirementList()->getRequirements() as $requirement) {
    if($requirement->getArt() === 'Trait'){
        $traitReq = explode('|', $requirement->getRequiredValue());
    }
}
/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $schule->getRequirementList();
$organizations = [
    0 => 'Keine Organisation',
    Application_Model_MagiOrganization::CLOCK_TOWER => 'Clock Tower',
    Application_Model_MagiOrganization::ATLAS => 'Atlas',
    Application_Model_MagiOrganization::WANDERING_SEA => 'Wandering Sea',
    Application_Model_MagiOrganization::CHURCH => 'Glaubenstypen',
];
?>
<h1 class="fs-1">Magieschule anpassen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/schule/edit" method="post">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="name">Name</label>
            <input class="form-control" type="text" size="30" name="name" value="<?= $schule->getBezeichnung() ?>" />
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="MagiOrganization">Magi Organisation</label>
            <select class="form-select" name="MagiOrganization" id="MagiOrganization">
                <?php foreach ($organizations as $key => $organization) {
                    $selected = '';
                    if ($key === $schule->getMagiOrganization()) {
                        $selected = 'selected=""';
                    }
                    ?>
                    <option value="<?= $key ?>" <?= $selected ?>><?= $organization ?></option>
                <?php } ?>
            </select>
        </div>
    </div>

    <div class="row m-3">
        <div class="col-12">
            <textarea name="beschreibung" cols="80" rows="10"><?= $schule->getBeschreibung() ?></textarea>
        </div>
    </div>

    <div class="row m-3">
        <div class="col">
            <div class="fs-2">Vorraussetzungen</div>
        </div>
    </div>

    <?= $this->partial('partials/values.phtml', ['requirementList' => new Administration_Model_Requirementlist()]) ?>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/groups.phtml', ['groups' => $this->klassengruppen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial('partials/classes.phtml', ['classes' => $this->klassen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/traits.phtml', ['traits' => $this->traits, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/skills.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial('partials/skillsAny.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/magic.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial('partials/magicAny.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="trait">
                Nicht kombinierbar mit den Traits:
            </label>
            <select class="form-select" name="trait[]" multiple="true" size="8">
                <?php foreach ($this->traits as $trait) {
                    $selected = in_array($trait->getTraitId(), $traitReq) ? 'selected' : '';
                    ?>
                    <option <?= $selected ?>  value="<?= $trait->getTraitId() ?>">
                        <?= $trait->getName() ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input class="form-control" type="hidden" name="schuleId" value="<?= $schule->getId() ?>" />
            <input class="form-control" type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Magieschule speichern" />
        </div>
    </div>
</form>