<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1 class="fs-1">Nachrichten Verfassen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/news/create" method="post" name="News" id="News">
    <div class="row">
        <div class="col-6">
            <div class="form-floating mb-3">
                <input class="form-control" type="text" size="40" placeholder="Titel" name="Titel" id="Titel" />
                <label class="form-label" for="Titel">Titel</label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <textarea name="Nachricht" id="Nachricht" cols="80" rows="20"></textarea>
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="News eintragen" />
        </div>
    </div>
</form>