<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/gruppen/editor.js'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $gruppe Gruppen_Model_Gruppe */
$gruppe = $this->gruppe;
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
$werte = $charakter->getCharakterwerte();

/**
 * @todo Liste für Skillarten um zu sortieren
 */
$sortorder = [
    'Übungsfähigkeiten' => 1,
    'Schützenfähigkeiten' => 2,
    'Kämpferfähigkeiten' => 3,
    'Spezialfähigkeiten' => 4,
];

$order = function (Application_Model_Skillart $a, Application_Model_Skillart $b) use ($sortorder)
{
    return $sortorder[$a->getBezeichnung()] > $sortorder[$b->getBezeichnung()];
};
/* @var $skillart Application_Model_Skillart */
$skillarten = $this->skillarten;
usort($skillarten, $order);
/* @var $schule Application_Model_Schule */
$magieschulen = $this->magieschulen;
?>
<h1>
    <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
</h1>
<div>
    <fieldset style="display: inline-block; width: 45%; float: left">
        <legend>Charakterdaten</legend>
        <p>
            <label>
                Name
            </label>
            <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
        </p>
        <p>
            <label>
                Geschlecht
            </label>
            <?= $purifier->purify($charakter->getGeschlecht()) ?>
        </p>
        <p>
            <label>
                Geburtsdatum
            </label>
            <?= $purifier->purify($charakter->getGeburtsdatum('d.m.Y') . ' (' . $charakter->getAlter() . ')') ?>
        </p>
        <p>
            <label>
                Wohnort
            </label>
            <?= $purifier->purify($charakter->getWohnort()) ?>
        </p>
        <p>
            <label>
                Sexuelle Orientierung
            </label>
            <?= $purifier->purify($charakter->getSexualitaet()) ?>
        </p>
    </fieldset>
    <fieldset style="display: inline-block; width: 45%; float: right">
        <legend>Werte</legend>
        <p>
            <label>
                Stärke
            </label>
            <span>
                <?= $werte->getStaerke() ?>
            </span>
            <span>
                <?= $werte->getCategory($werte->getStaerke()) ?>
            </span>
        </p>
        <p>
            <label>
                Agilität
            </label>
            <span>
                <?= $werte->getAgilitaet() ?>
            </span>
            <span>
                <?= $werte->getCategory($werte->getAgilitaet()) ?>
            </span>
        </p>
        <p>
            <label>
                Ausdauer
            </label>
            <span>
                <?= $werte->getAusdauer() ?>
            </span>
            <span>
                <?= $werte->getCategory($werte->getAusdauer()) ?>
            </span>
        </p>
        <p>
            <label>
                Kontrolle
            </label>
            <span>
                <?= $werte->getKontrolle() ?>
            </span>
            <span>
                <?= $werte->getCategory($werte->getKontrolle()) ?>
            </span>
        </p>
        <p>
            <label>
                Disziplin
            </label>
            <span>
                <?= $werte->getDisziplin() ?>
            </span>
            <span>
                <?= $werte->getCategory($werte->getDisziplin()) ?>
            </span>
        </p>
        <p>
            <label>
                Übung
            </label>
            <span>
                <?= $werte->getUebung() ?>
            </span>
        </p>
    </fieldset>
    <div style="clear: both"></div>
</div>
<div>
    <fieldset style="display: inline-block; width: 45%; float: left">
        <legend>Traits</legend>
<?php foreach($charakter->getTraits() as $trait): ?>
        <h4>
            <?= $purifier->purify($trait->getName()) ?>
        </h4>
        <p>
            <?= $purifier->purify($trait->getBeschreibung()) ?>
        </p>
<?php endforeach; ?>
    </fieldset>
    <div style="clear: both"></div>
</div>
<div>
    <fieldset>
        <legend>Klasse</legend>
        <h4>
            <?= $purifier->purify($charakter->getKlassengruppe()->getBezeichnung()) ?>
        </h4>
        <p>
            Unterklasse: <?= $purifier->purify($charakter->getKlasse()->getBezeichnung()) ?>
        </p>
        <p>
            <?= $purifier->purify($charakter->getKlasse()->getBeschreibung()) ?>
        </p>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Fähigkeiten</legend>
        <?php foreach ($skillarten as $skillart): ?>
        <fieldset>
            <legend><?= $purifier->purify($skillart->getBezeichnung()) ?></legend>
                <?php foreach ($skillart->getSkills() as $skill): ?>
            <h4>
                <?= $purifier->purify($skill->getBezeichnung()) ?>
            </h4>
            <p>
                <?= $purifier->purify($skill->getBeschreibung()) ?>
            </p>
                <?php endforeach; ?>
        </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Magien</legend>
        <?php foreach ($magieschulen as $schule): ?>
            <fieldset>
                <legend><?= $purifier->purify($schule->getBezeichnung()) ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <?php foreach ($schule->getMagien() as $magie): ?>
                    <h4><?= $purifier->purify($magie->getBezeichnung()) ?></h4>
                    <p>
                        <?= $purifier->purify($magie->getBeschreibung()) ?>
                    </p>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>