<div class="row">
    <div class="col-3">
        <a class="btn btn-primary" href="<?= $this->baseUrl() ?>/Nachrichten/outbox/new">
            Nachricht verfassen
        </a>
    </div>
    <div class="col-3">
        <a class="btn btn-secondary" href="<?= $this->baseUrl() ?>/Nachrichten/inbox/">
            Nachrichteneingang
        </a>
    </div>
    <div class="col-3">
        <a class="btn btn-secondary" href="<?= $this->baseUrl() ?>/Nachrichten/outbox">
            Nachrichtenausgang
        </a>
    </div>
    <div class="col-3">
        <a class="btn btn-secondary" href="<?= $this->baseUrl() ?>/Nachrichten/index/archiv">
            Archiv
        </a>
    </div>
</div>