<ul>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten/outbox/new">
            Nachricht verfassen
        </a>
    </li>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten/inbox/">
            Nachrichteneingang
        </a>
    </li>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten/outbox">
            Nachrichtenausgang
        </a>
    </li>
    <li>
        <a href="<?= $this->baseUrl() ?>/Nachrichten/index/archiv">
            Archiv
        </a>
    </li>
</ul>