<?php
$this->headLink()->appendStylesheet($this->autoVersion($this->baseUrl() . '/styles/story.css'));
$plots = $this->plotsToReview;
/* @var $plot \Logs\Models\Plot */
?>
<h1>
    Logcenter
</h1>
<fieldset>
    <?php if(count($plots) > 0) { ?>
    <legend>Plots und Episoden zur Bewertung</legend>
    <?php foreach($plots as $plot): ?>
    <div>
        <h3>Episoden für Plot: <?= $this->purify($plot->getName()) ?></h3>
        <ul>
            <?php foreach($plot->getEpisoden() as $episode): ?>
            <li>
                <a href="<?= $this->baseUrl() ?>/Logs/review/show/episode/<?= $episode->getId() ?>">
                    <?= $this->purify($episode->getName()) ?> - Logs lesen
                </a>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endforeach; ?>
    <?php } else { ?>
    <p>
        Zur Zeit gibt es keine Logs zu bewerten.
    </p>
    <?php } ?>
</fieldset>