<?php

$odo = $this->creationParams['odo'];
$luck = $this->creationParams['luck'];
$circuits = $this->creationParams['circuits'];
$elemente = $this->creationParams['elemente'];
?>
<fieldset class="FormularZeile">
    <label class="FormularLabel">
        <span class="titel">
            Naturelement
        </span>
        <span class="label">
            Das eigene Naturelement zeigt die natürliche Affinität eines Charakters an. Eines dieser vier muss gewählt werden.
            Für Magi gewinnt es zudem an Bedeutung, da alle Magien die das eigene Naturelement in sich tragen 10% weniger FP kosten.
        </span>
    </label>
    <div class="FormularInput">
        <select name="element" id="element" required="" >
            <option selected="" value="">bitte auswählen</option>
            <?php
            foreach ($elemente as $element) {
                if ($element->getCharakterisierung() !== null) {
            ?>
                    <option value="<?= $element->getID() ?>">
                        <?= $element->getBezeichnung() . ' ' . $element->getCharakterisierung() ?>
                    </option>
            <?php
                }
            }
            ?>
        </select>
    </div>
</fieldset>
<fieldset class="FormularZeile">
    <label class="FormularLabel">
        <span class="titel">
            Odo
        </span>
        <span class="label">
            Odo ist die Energie die Wesen für ihre magischen Fähigkeiten benötigen.
            Odo lässt sich nicht trainieren, wieviel man besitzt wird bei der Geburt entschieden und festgelegt.
            F ist der schlechteste, A der beste Wert.
        </span>
    </label>
    <div class="FormularInput ui-widget">
        <select name="odo" id="odo" required="" >
            <option selected="" value="">bitte auswählen</option>
            <?php
            foreach ($odo as $odo) {
                $odo->getKosten() === null ? $disabled = 'disabled=""' : $disabled = '';
                ?>
                <option value="<?= $odo->getID() ?>" <?= $disabled ?> >
                    <?= $odo->getKategorie() . ' (' . $odo->getKosten() . ')' ?>
                </option>
                <?php
            }
            ?>
        </select>
    </div>
    <fieldset>
        <legend>Beschreibung</legend>
        <div class="beschreibungOdo"></div>
    </fieldset>
</fieldset>
<?php if($this->hasCircuit === true): ?>
<fieldset class="FormularZeile">
    <label class="FormularLabel">
        <span class="titel">
            Magic Circuit
        </span>
        <span class="label">
            Magi besitzen sogenannte Magic Circuits im Körper mit denen sie das Odo ihres Körpers und Mana ihrer Umgebung kontrollieren und davon profitieren können.
        </span>
    </label>
    <div class="FormularInput">
        <select name="circuit" id="circuit" >
            <option selected="" value="0">bitte auswählen</option>
            <?php
            foreach ($circuits as $circuit) {
                ?>
                <option value="<?= $circuit->getID() ?>" >
                    <?= $circuit->getKategorie() . ' (' . $circuit->getKosten() . ')' ?>
                </option>
                <?php
            }
            ?>
        </select>
    </div>
    <fieldset>
        <legend>Beschreibung</legend>
        <div class="beschreibungCircuit"></div>
    </fieldset>
</fieldset>
<?php endif; ?>
<fieldset class="FormularZeile">
    <label class="FormularLabel">
        <span class="titel">
            Glück
        </span>
    </label>
    <div class="FormularInput">
        <select name="luck" id="luck" required="" >
            <option selected="" value="">bitte auswählen</option>
            <?php
            foreach ($luck as $luck) {
                $disabled = ($luck->getKosten() === null) ? 'disabled=""' : '';
                ?>
                <option value="<?= $luck->getID() ?>" <?= $disabled ?> >
                    <?= $luck->getKategorie() . ' (' . $luck->getKosten() . ')' ?>
                </option>
                <?php
            }
            ?>
        </select>
    </div>
    <fieldset>
        <legend>Beschreibung</legend>
        <div class="beschreibungLuck"></div>
    </fieldset>
</fieldset>
<input class="nextStep" type="submit" value="Weiter">