<?php
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/erstellung/charaktererstellungNeu.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/erstellung/guide.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/erstellung/reset.js'));
?>
<h1>
    Neuen Charakter erstellen
</h1>
<div id="helpText"></div>
<div id="dialog"></div>
<fieldset id="person">
    <legend class="reset active">Person</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset id="klasse">
    <legend class="reset inactive">Klasse</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset id="eigenschaften">
    <legend class="reset inactive">Eigenschaften</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset id="vorNachteile">
    <legend class="reset inactive">Vorteile / Nachteile</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset id="unterklasse">
    <legend class="reset inactive">Unterklasse</legend>
    <div class="subContent"></div>
</fieldset>