<?php
/* @var $klasse Erstellung_Model_Klasse */
?>
<div style="text-align: center">
    <div style="margin: 0 auto; display: inline-block;">
<?php foreach ($this->klassen as $klasse) : ?>
    <div class="choices klasse" data-id="<?= $klasse->getId() ?>">
        <p>
            <?= $klasse->getBezeichnung() ?>
        </p>
    </div>
<?php endforeach; ?>
    <div style="clear: both"></div>
    </div>
</div>
<fieldset>
    <legend>Beschreibung</legend>
    <div class="beschreibung"></div>
</fieldset>
<input class="nextStep" type="submit" value="Weiter">