<?php
/* @var $unterklasse Erstellung_Model_Unterklasse */
?>
<div style="text-align: center">
    <div style="margin: 0 auto; display: inline-block;">
<?php foreach ($this->unterklassen as $unterklasse) : ?>
    <div class="choices unterklasse" data-id="<?= $unterklasse->getId() ?>">
        <p>
            <?= $unterklasse->getBezeichnung() ?><br />
            (<?= $unterklasse->getKosten() ?>)
        </p>
    </div>
<?php endforeach; ?>
    <div style="clear: both"></div>
    </div>
</div>
<fieldset>
    <legend>Beschreibung</legend>
    <div class="beschreibung"></div>
</fieldset>
<form method="post" action="<?= $this->baseUrl() ?>/Erstellung/Charakter/finish">
    <input class="nextStep" type="submit" value="Charaktererstellung abschließen">
</form>