<p>
    In diesem Schritt müsst ihr euch für die spirituellen Eigenschaften eures Charakters entscheiden. 
    Dabei wählt ihr die Stufe eures Odos, eures Glücks und eures Naturelementes aus. 
    Als Magi müsst ihr zudem die Stufe eures Magic Circuits festlegen.
</p>
<p>
    Beachtet dass euch 30 Punkte für die Erstellung eures Charakters zur Verfügung stehen, 
    die nicht nur für die spirituellen Eigenschaften, sondern auch eure Vor-/Nachteile 
    sowie eure Unterklassen ausreichen müssen. Falls euch die Punkte später ausgehen, 
    könnt ihr jederzeit zu dieser Seite zurückkehren und eure Punkte umverteilen.
</p>