<?php
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/erstellung/general/charaktererstellungNeu.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/erstellung/general/guide.js'));
?>
<h1>
    Neuen Charakter erstellen
</h1>
<div id="helpText">
    <p>
        Herzlichen Willkommen bei Fate/Alpha!
    </p>
    <p>
        In den folgenden Schritten werdet ihr die Lage versetzt, einen Charakter für das Spiel zu erschaffen.
        Zuerst benötigen wir grundlegende Informationen für euren Charakter.
    </p>
    <p>
        Wichtig: Die folgenden Angaben können in bestimmten Situationen das Spiel beeinflussen und sind nicht überflüssig. 
    </p>
    <p>
        Auf dieser Seite (<a href="<?= $this->baseUrl() ?>/index/intro">Für Einsteiger</a> ) kannst du dir von Kirei eine Einführung in die Welt des Nasuverse ansehen, um das Spiel ein wenig besser zu verstehen.
    </p>
</div>
<div id="dialog"></div>
<fieldset id="person">
    <legend class="reset">Die Person</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset id="klasse">
    <legend class="reset">Klasse</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset class="reset">
    <legend>Eigenschaften</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset class="reset">
    <legend>Vorteile / Nachteile</legend>
    <div class="subContent"></div>
</fieldset>
<fieldset class="reset">
    <legend>Unterklasse</legend>
    <div class="subContent"></div>
</fieldset>