<p>
    Herzlich willkommen bei Fate/Alpha!
</p>
<p>
    In den folgenden Schritten werdet ihr in die Lage versetzt, einen Charakter für das Spiel zu erschaffen.
    Zuerst benötigen wir grundlegende Informationen für euren Charakter.
</p>
<p>
    Wichtig: Die folgenden Angaben können in bestimmten Situationen das Spiel beeinflussen und sind nicht überflüssig. 
</p>
<p>
    Auf dieser Seite (<a href="<?= $this->baseUrl() ?>/index/intro">Für Einsteiger</a> ) kannst du dir von Kirei eine Einführung in die Welt des Nasuverse ansehen, um das Spiel ein wenig besser zu verstehen.
</p>