<p>
    Auf dieser Seite wählt ihr eure Unterklasse aus, vornehmlich den Clan dem euer Charakter angehören kann. 
    Falls ihr zu viele oder zu wenige Punkte besitzt, könnt ihr noch einmal auf die vorherigen 
    Seiten zurückkehren um eure bisherigen Entscheidungen anzupassen. 
    Die Wahl einer Unterklasse (sowie die mögliche Nicht-Wahl) kann entscheidend dafür sein, 
    wie euer Charakter in der Welt wahrgenommen wird.
</p>
<p>
    Vergesst nicht, dass ihr den Nachnamen eures Clans oder eurer Familie annehmt, falls ihr einem beitreten solltet.
</p>