<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $item Story_Model_Item */
$items = $this->items;
?>
<fieldset>
    <legend>Gegenstände entfernen</legend>
    <div>
        <?php if(count($items) > 0){ ?>
            <select id="removeItems" multiple="" size="5">
                <?php foreach($items as $item): ?>
                    <option value="<?= $item->getId() ?>"><?= $purifier->purify($item->getName()) ?></option>
                <?php endforeach; ?>
            </select>
            <input class="removeItems" type="submit" value="Speichern">
        <?php } else { ?>
            Der Charakter hat keine Items die er abgeben kann.
        <?php } ?>
    </div>
</fieldset>