<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $item Story_Model_Item */
$items = $this->items;
?>
<fieldset>
    <legend>Items eintragen</legend>
    <div>
        <?php if(count($items) > 0){ ?>
            <select id="acquireItems" multiple="" size="<?= min(count($items), 5) ?>">
                <?php foreach($items as $item): ?>
                    <option value="<?= $item->getId() ?>"><?= $purifier->purify($item->getName()) ?></option>
                <?php endforeach; ?>
            </select>
            <input class="saveItems" type="submit" value="Speichern">
        <?php } else { ?>
            Der Charakter kann aktuell keine Gegenstände per RPG erlangen.
        <?php } ?>
    </div>
</fieldset>