<?php
/* @var $nachrichten \Nachrichten\Models\Message[] */
$nachrichten = $this->nachrichten;

?>
<h1>
    Nachrichteneingang
</h1>
<?php include __DIR__ . '/../partials/submenu.phtml'; ?>
<div class="row m-2 g-0 p-1">
    <div class="col-1">

    </div>
    <div class="col-4">
        Betreff
    </div>
    <div class="col-3">
        Verfasser
    </div>
    <div class="col-3">
        Datum
    </div>
    <div class="col-1">

    </div>
</div>
<?php
foreach ($nachrichten as $nachricht):
    $subject = $nachricht->getBetreff() !== ''
        ? $this->purify($nachricht->getBetreff())
        : 'Nachricht von: ' . $this->purify($nachricht->getVerfasser()->getProfilname());
    ?>
    <div class="row m-2 g-0 p-1">
        <div class="col-1">
            <?= ($nachricht->getStatus() === 'ungelesen') ? '! ! !' : '' ?>
        </div>
        <div class="col-4">
            <a href="<?= $this->baseUrl() ?>/Nachrichten/index/show/id/<?= $nachricht->getId() ?>/read/true">
                <?= $subject ?>
            </a>
        </div>
        <div class="col-3">
            <?= ($nachricht->getAdmin() === false) ? $this->purify($nachricht->getVerfasser()->getProfilname()) : 'Admin' ?>
        </div>
        <div class="col-3">
            <?= $nachricht->getCreationDate() ?>
        </div>
        <div class="col-1">
            <a class="btn btn-danger" href="<?= $this->baseUrl() ?>/Nachrichten/index/delete/id/<?= $nachricht->getId() ?>">
                löschen
            </a>
        </div>
        <hr />
    </div>
<?php endforeach; ?>