<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/gruppen/editor.js'));
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$gruppenArray = array();
?>
<h1>
    Spielgruppen
</h1>
<img src="http://i.imgur.com/wZvdsOw.jpg">
<fieldset>
    <legend>
        einer Gruppe beitreten
    </legend>
    <?php if($this->layoutData->getHasChara() === true){ ?>
    <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/enter">
        <p>
            <label for="gruppenname">
                Gruppenname
            </label>
            <input type="text" name="gruppenname"/>
            <label for="passwort">
                Passwort
            </label>
            <input type="password" name="passwort"/>
            <input type="submit"/>
        </p>
    </form>
    <?php } else { ?>
    <p>
        Du musst einen Charakter erstellen bevor du einer Spielergruppe beitreten kannst.
    </p>
    <?php } ?>
</fieldset>
<fieldset>
    <legend>
        dir bekannte Gruppen
    </legend>
<?php foreach ($this->eigeneGruppen as $gruppe): 
    $gruppenArray[] = $gruppe->getId();
?>
    <a href="<?= $this->baseUrl() ?>/Gruppen/index/show/id/<?= $gruppe->getId() ?>">
        <kbd><?= $purifier->purify($gruppe->getName()) ?> (von dir gegründet)</kbd>
    </a><br />
<?php endforeach; ?>
<?php foreach ($this->gruppen as $gruppe): 
    if(in_array($gruppe->getId(), $gruppenArray)){
        continue;
    }
?>
    <a href="<?= $this->baseUrl() ?>/Gruppen/index/show/id/<?= $gruppe->getId() ?>">
        <kbd><?= $purifier->purify($gruppe->getName()) ?></kbd>
    </a><br />
<?php endforeach; ?>
</fieldset>
<fieldset>
    <legend>
        neue Gruppe gründen
    </legend>
    <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/create">
        <p>
            <label for="gruppenname">
                Gruppenname
            </label>
            <input type="text" name="gruppenname"/>
            <label for="passwort">
                Passwort
            </label>
            <input type="password" name="passwort"/>
            <input type="submit" value="Gruppe erstellen"/>
        </p>
        <p>
            <textarea name="beschreibung"></textarea>
        </p>
    </form>
</fieldset>