<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/gruppen/editor.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/gruppen/gruppen.js');
/* @var $gruppe Gruppen_Model_Gruppe */
/* @var $charakter Application_Model_Charakter */
/* @var $nachricht Gruppen_Model_Nachricht */
/* @var $purifier HTMLPurifier */
/* @var $log Application_Model_Log */
$purifier = $this->purifier;
$gruppe = $this->gruppe;
$charaktere = $this->charaktere;
$mitgliedArray = array();
foreach ($this->charaktere as $charakter) {
    foreach ($this->gruppe->getMitglieder() as $mitglied) {
        if($charakter->getCharakterid() === $mitglied->getCharakterId()){
            $mitgliedArray[] = $charakter->getCharakterid();
        }
    }
}
?>
<h1>
    <?= $gruppe->getName() ?>
</h1>
<p>
    <?= $gruppe->getBeschreibung() ?>
</p>
<?php include __DIR__ . '/partials/gruppenleiter.phtml'; ?>
<?php include __DIR__ . '/partials/mitglieder.phtml'; ?>
<div>
    <fieldset>
        <legend>Logcenter</legend>
        <div>
            <form enctype="multipart/form-data" method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/upload">
                <?php if(count($this->plots)): ?>
                    <label>hochladen für: </label>
                    <select name="plot">
                        <option value="">keinen Plot</option>
                        <?php foreach($this->plots as $plot): ?>
                        <option value="<?= $plot->getId() ?>"><?= $plot->getName() ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
                <input type="file" name="logfile">
                <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                <input type="submit" value="Log hochladen">
            </form>
        </div>
        <div>
            <?php foreach($this->logs as $log): ?>
            <a><?= $log->getName() ?></a>
            <?php endforeach; ?>
        </div>
    </fieldset>
</div>
<?php include __DIR__ . '/partials/gruppenchat.phtml'; ?>