<h1>
    Passwort vergessen
</h1>
<?php
if ($this->message !== null) {
    ?>
    <div class="error">
        <?= $this->message ?>
    </div>
    <?php
}
?>
<form method="post" action="<?= $this->baseUrl() ?>/login/newpw">
    <div class="row m-3 justify-content-center">
        <div class=" col-6 mb-3">
            <label class="form-label" for="loginname">
                Username
            </label>
            <input class="form-control" name="loginname" id="loginname" type="text" required>
        </div>
    </div>
    <div class="row m-3 justify-content-center">
        <div class=" col-6 mb-3">
            <label class="form-label" for="email">
                Email
            </label>
            <input class="form-control" name="email" id="email" type="text" required>
        </div>
    </div>
    <div class="row m-3 justify-content-center">
        <div class="col-3">
            <input class="btn btn-primary" name="Submit" type="submit" value="neues Passwort senden">
        </div>
    </div>
</form>