<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/magieList.js'));
/* @var $magie Administration_Model_Magie */
/* @var $schule Application_Model_Schule */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$schoolArray = [];
foreach ($this->list as $magie) {
    $schoolArray[$magie->getSchule()->getId()] = [
        'name' => $magie->getSchule()->getBezeichnung(),
        'descr' => $magie->getSchule()->getBeschreibung(),
        'magien' => [],
    ];
}
foreach ($this->list as $magie) {
    $schoolArray[$magie->getSchule()->getId()]['magien'][] = $magie;
}
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Magien
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <h2 class="fs-2">Filter</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <select class="form-select" id="magieschulen" multiple size="7">
                <?php foreach ($this->schulen as $schule) : ?>
                    <option value="<?= $schule->getId() ?>"><?= $purifier->purify($schule->getBezeichnung()) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-3">
            <select class="form-select" id="gruppen" multiple size="5">
                <?php foreach ($this->klassengruppen as $gruppe) : ?>
                    <option value="<?= $gruppe->getId() ?>"><?= $purifier->purify($gruppe->getBezeichnung()) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="col-3">
            <select class="form-select" id="klassen" multiple size="7" >
                <?php foreach ($this->klassen as $klasse) : ?>
                    <option value="<?= $klasse->getId() ?>"><?= $purifier->purify($klasse->getBezeichnung()) ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <button class="btn btn-secondary" id="filterExecute">Suchen</button>
        </div>
    </div>
    <div id="list">
        <?php
        foreach ($schoolArray as $key => $schoolArray) {
            ?>
            <div class="row">
                <div class="col-12">
                    <h2 class="fs-2" id="<?= $key ?>">
                        <?= $schoolArray['name'] ?>
                    </h2>
                    <p class="text-muted"><?= $schoolArray['descr'] ?></p>
                </div>
            </div>
            <div class="row">
                <?php foreach ($schoolArray['magien'] as $magie): ?>
                    <div class="col-4 p-2">
                        <div class="card" style="height: 10rem; overflow: auto">
                            <a href="<?= $this->baseUrl() ?>/Administration/magie/show/id/<?= $magie->getId() ?>">
                                <div class="card-body">
                                    <div class="card-title fs-3">
                                        <?= $purifier->purify($magie->getBezeichnung()) ?>
                                    </div>
                                    <div class="text-muted">
                                        <?= $purifier->purify(substr($magie->getBeschreibung(), 0, 200)) ?>
                                        <?= (strlen($purifier->purify($magie->getBeschreibung())) > 200) ? '...' : '' ?>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php
        }
        ?>
    </div>
</div>