<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));

$lernbedingungen = [
    'Standard',
    'RPG-Ereignis',
    'Lehrer',
];
/** @var Application_Model_Charakter $characters */
$characters = $this->characters;
?>
<h1 class="fs-1">Magie erstellen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/magie/create" method="post" name="News" id="News">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="name">Name</label>
            <input class="form-control" type="text" size="30" name="name" />
        </div>
        <div class="col-4">
            <label class="form-label" for="fp">FP-Kosten</label>
            <input class="form-control" type="number" name="fp"/>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/characters.phtml', ['characters' => $characters, 'requirementList' => new Administration_Model_Requirementlist()]) ?>

        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="magieschule">
                Magieschule
            </label>
            <select class="form-select" name="magieschule">
                <?php foreach ($this->schulen as $schule) { ?>
                    <option value="<?= $schule->getId() ?>">
                        <?= $this->purify($schule->getBezeichnung()) ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="element">
                Element
            </label>
            <select class="form-select" name="element">
                <?php foreach ($this->elemente as $element) { ?>
                    <option value="<?= $element->getId() ?>">
                        <?= $this->purify($element->getBezeichnung()) ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="rang">
                Rang
            </label>
            <select class="form-select" id="rang" name="rang">
                <option>EX</option>
                <option>A</option>
                <option>B</option>
                <option>C</option>
                <option>D</option>
                <option>E</option>
                <option>F</option>
                <option>EA</option>
                <option>EB</option>
                <option>EC</option>
                <option>ED</option>
                <option>EE</option>
                <option>EF</option>
            </select>
        </div>
        <div class="col-4">
            <label class="form-label" for="stufe">
                Stufe
            </label>
            <select class="form-select" id="stufe" name="stufe">
                <option>1</option>
                <option>2</option>
                <option>3</option>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="prana">Prana-Kosten</label>
            <input class="form-control" type="number" id="prana" name="prana" />
        </div>
    </div>

    <div class="row m-3">
        <div class="col">
            <h2>Voraussetzungen</h2>
        </div>
    </div>

    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="lernbedingung">
                Lernbedingung
            </label>
            <select class="form-select" id="lernbedingung" name="lernbedingung">
                <?php foreach($lernbedingungen as $bedingung): ?>
                    <option><?= $bedingung ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>



    <?= $this->partial('partials/values.phtml', ['requirementList' => new Administration_Model_Requirementlist()]) ?>

    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial('partials/groups.phtml',
                [
                    'groups' => $this->klassengruppen,
                    'requirementList' => new Administration_Model_Requirementlist()
                ]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial(
                    'partials/classes.phtml',
                    [
                        'classes' => $this->klassen,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial(
                    'partials/traits.phtml',
                    [
                        'traits' => $this->traits,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial(
                    'partials/skills.phtml',
                    [
                        'skills' => $this->skills,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial(
                    'partials/skillsAny.phtml',
                    [
                        'skills' => $this->skills,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial(
                    'partials/magic.phtml',
                    [
                        'magic' => $this->magien,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
        <div class="col-4">
            <?= $this->partial(
                    'partials/magicAny.phtml',
                    [
                        'magic' => $this->magien,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <?= $this->partial(
                    'partials/skillsNone.phtml',
                    [
                        'skills' => $this->skills,
                        'requirementList' => new Administration_Model_Requirementlist()
                    ]) ?>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-12">
            <textarea class="form-control" name="beschreibung" cols="80" rows="10"></textarea>
        </div>
    </div>

    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Magie speichern" />
        </div>
    </div>
</form>