<?php
/* @var $magie Administration_Model_Magie */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$schoolArray = [];
foreach ($this->list as $magie) {
    $schoolArray[$magie->getSchule()->getId()] = [
        'name' => $magie->getSchule()->getBezeichnung(),
        'descr' => $magie->getSchule()->getBeschreibung(),
        'magien' => [],
    ];
}
foreach ($this->list as $magie) {
    $schoolArray[$magie->getSchule()->getId()]['magien'][] = $magie;
}
$linkList = [];
foreach ($schoolArray as $key => $school) {
    $linkList[] = '<a href="#' . $key . '">#' . $school['name'] . '</a>';
}
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                RPG-Magien
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2 class="fs-2">
                Magieschulen
            </h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <?= implode(', ', $linkList) ?>
        </div>
    </div>

    <?php
    foreach ($schoolArray as $key => $schoolArray) {
        ?>
        <div class="row">
            <div class="col-12">
                <h2 class="fs-2" id="<?= $key ?>">
                    <?= $schoolArray['name'] ?>
                </h2>
            </div>
        </div>
        <div class="row">
            <?php foreach ($schoolArray['magien'] as $magie): ?>
                <div class="col-4 p-2">
                    <div class="card" style="height: 10rem; overflow: auto">
                        <a href="<?= $this->baseUrl() ?>/Administration/magie/show/id/<?= $magie->getId() ?>">
                            <div class="card-body">
                                <div class="card-title fs-3">
                                    <?= $purifier->purify($magie->getBezeichnung()) ?>
                                </div>
                                <div class="text-muted">
                                    <?= $purifier->purify(substr($magie->getBeschreibung(), 0, 200)) ?>
                                    <?= (strlen($purifier->purify($magie->getBeschreibung())) > 200) ? '...' : '' ?>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
    }
    ?>
</div>
