<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$lernbedingungen = [
    'Standard',
    'RPG-Ereignis',
    'Lehrer',
];
$raenge = ['EX','A','B','C','D','E','F',];
$stufen = [1,2,3,];
/* @var $magie Administration_Model_Magie */
$magie = $this->magie;

/** @var Administration_Model_Requirementlist $requirementList */
$requirementList = $magie->getRequirementList();
/** @var Application_Model_Charakter $characters */
$characters = $this->characters;
?>
<h1>Magie anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/magie/edit" method="post">
    <fieldset>
        <div>
            <div style="width: 50%; display: inline-block;">
                <label for="name">Name</label>
                <input type="text" size="30" name="name" value="<?= $magie->getBezeichnung() ?>" />
            </div>
            <div style="width: 45%; display: inline-block;">
                <label for="fp">FP-Kosten</label>
                <input type="number" name="fp" value="<?= $magie->getFp() ?>" />
            </div>
        </div>
        <div>
            <div style="width: 50%; display: inline-block;">
                <?= $this->partial('partials/characters.phtml', ['characters' => $characters, 'requirementList' => $requirementList]) ?>
            </div>
        </div>
        <div>
            <div style="width: 50%; display: inline-block;">
                <label for="magieschule">
                    Magieschule
                </label>
                <select name="magieschule">
                    <?php foreach ($this->schulen as $schule):
                        $selected = ($schule->getId() === $magie->getMagieschuleId()) ? 'selected=""' : '';
                    ?>
                    <option value="<?= $schule->getId() ?>" <?= $selected ?>>
                        <?= $schule->getBezeichnung() ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div style="width: 45%; display: inline-block;">
                <label for="element">
                    Element
                </label>
                <select name="element">
                    <?php foreach ($this->elemente as $element):
                        $selected = '';
                        if($magie->getElement()->getId() == $element->getId()){
                            $selected = 'selected="true"';
                        }
                    ?>
                    <option value="<?= $element->getId() ?>" <?= $selected ?>>
                        <?= $element->getBezeichnung() ?>
                    </option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <label for="rang">
                        Rang
                    </label>
                    <select name="rang">
                        <?php foreach($raenge as $rang): ?>
                            <option <?= ($magie->getRang() == $rang) ? 'selected=""' : '' ?>><?= $rang ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div style="width: 45%; display: inline-block;">
                <label for="stufe">
                    Stufe
                </label>
                <select name="stufe">
                    <?php foreach($stufen as $stufe): ?>
                    <option <?= ($magie->getStufe() == $stufe) ? 'selected=""' : '' ?>><?= $stufe ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>
        <div style="width: 50%; display: inline-block;">
            <label for="prana">Prana-Kosten</label>
            <input type="number" name="prana" value="<?= $magie->getPrana() ?>" />
        </div>
        <fieldset>
            <legend>Voraussetzungen</legend>
            <div>
                <label for="lernbedingung">
                    Lernbedingung
                </label>
                <select id="lernbedingung" name="lernbedingung">
                    <?php foreach($lernbedingungen as $bedingung): ?>
                        <option <?= ($magie->getLernbedingung() == $bedingung) ? 'selected=""' : '' ?>><?= $bedingung ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <?= $this->partial('partials/values.phtml', ['requirementList' => $requirementList]) ?>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/groups.phtml', ['groups' => $this->klassengruppen, 'requirementList' => $requirementList]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/classes.phtml', ['classes' => $this->klassen, 'requirementList' => $requirementList]) ?>
                </div>
            </div>
            <div>
                <?= $this->partial('partials/traits.phtml', ['traits' => $this->traits, 'requirementList' => $requirementList]) ?>
            </div>
            <div>
                <div style="width: 50%; display: inline-block; vertical-align: top">
                    <?= $this->partial('partials/skills.phtml', ['skills' => $this->skills, 'requirementList' => $requirementList]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/skillsAny.phtml', ['skills' => $this->skills, 'requirementList' => $requirementList]) ?>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/magic.phtml', ['magic' => $this->magien, 'requirementList' => $requirementList]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/magicAny.phtml', ['magic' => $this->magien, 'requirementList' => $requirementList]) ?>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/skillsNone.phtml', ['skills' => $this->skills, 'requirementList' => $requirementList]) ?>
                </div>
            </div>
        </fieldset>
        <textarea name="beschreibung" cols="80" rows="10">
            <?= $this->purifier->purify($magie->getBeschreibung()) ?>
        </textarea>
    </fieldset>
    <div align="center">
        <input type="hidden" name="magieId" value="<?= $magie->getId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Magie ändern" />
    </div>
</form>