<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/charakter/editor.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/charakter/charakter.js');
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;

function order(Application_Model_Skillart $a, Application_Model_Skillart $b){
$sortorder = ['Übungsfähigkeiten' => 1, 
    'Schützenfähigkeiten' => 2, 
    'Kämpferfähigkeiten' => 3, 
    'Spezialfähigkeiten' => 4,
    ];
    if($sortorder[$a->getBezeichnung()] > $sortorder[$b->getBezeichnung()]){
        return 1;
    }
}
/* @var $skillart Application_Model_Skillart */
$skillarten = $this->skillarten;
usort($skillarten, "order");
/* @var $schule Application_Model_Schule */
$magieschulen = $this->magieschulen;
?>
<h1>
    Charakterdaten
</h1>
<div>
    <div class="contentLeft">
        <?php include __DIR__ . '/partials/charakterdaten.phtml'; ?>
        <?php include __DIR__ . '/partials/circuit.phtml'; ?>
        <?php include __DIR__ . '/partials/vorteile.phtml' ?>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <?php include __DIR__ . '/partials/statistik.phtml' ?>
        <?php include __DIR__ . '/partials/charakterwerte.phtml' ?>
        <?php include __DIR__ . '/partials/vermoegen.phtml' ?>
        <?php include __DIR__ . '/partials/klasse.phtml' ?>
        <?php include __DIR__ . '/partials/nachteile.phtml' ?>
    </div>
    <div class="clearBoth"></div>
</div>
<h1>
    Profil
</h1>
<div>
    <div class="contentLeft">
        <?php include __DIR__ . '/partials/profilbild.phtml' ?>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <?php include __DIR__ . '/partials/charakterbild.phtml' ?>
    </div>
    <div class="clearBoth"></div>
</div>
<div>
    <fieldset>
        <legend>Charaktergeschichte <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/story">
                <textarea class="data" id="story" name="story" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getCharaktergeschichte()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Private Charakterdaten <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/private">
                <textarea class="data" id="private" name="private" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getPrivatdaten()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<h1>
    Fähigkeiten
</h1>
<div>
    <fieldset>
        <legend>Fähigkeiten</legend>
        <?php foreach ($skillarten as $skillart): 
            if(count($skillart->getSkills()) === 0){
                continue;
            }
        ?>
        <fieldset>
            <legend><?= $skillart->getBezeichnung() ?> <span class="indicator"></span></legend>
            <div class="subContent">
                <?php foreach ($skillart->getSkills() as $skill): ?>
                <p>
                    <span class="skill">
                        <input type="hidden" value="<?= $skill->getId() ?>">
                        <?= $skill->getBezeichnung() ?>
                    </span>
                </p>
                <?php endforeach; ?>
            </div>
        </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Besondere Fähigkeiten</legend>
        <?php foreach ($magieschulen as $schule): ?>
            <fieldset>
                <legend><?= $schule->getBezeichnung() ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <?php foreach ($schule->getMagien() as $magie): ?>
                    <p>
                        <span class="magie">
                            <input type="hidden" value="<?= $magie->getId() ?>">
                            <?= $magie->getBezeichnung() ?>
                        </span>
                    </p>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div id="dialog"></div>