<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
$werte = $charakter->getCharakterwerte();
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;


$sortorder = [
    'Übungsfähigkeiten' => 1,
    'Schützenfähigkeiten' => 2,
    'Kämpferfähigkeiten' => 3,
    'Spezialfähigkeiten' => 4,
];

$order = function (Application_Model_Skillart $a, Application_Model_Skillart $b) use ($sortorder)
{
    return $sortorder[$a->getBezeichnung()] > $sortorder[$b->getBezeichnung()];
};
/* @var $skillart Application_Model_Skillart */
$skillarten = $this->skillarten;
usort($skillarten, $order);
/* @var $schule Application_Model_Schule */
$magieschulen = $this->magieschulen;
$magien = $this->magien;
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Charakterdaten
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <?php include __DIR__ . '/partials/charakterdaten.phtml'; ?>
            <?php include __DIR__ . '/partials/circuit.phtml'; ?>
            <?php include __DIR__ . '/partials/traits.phtml' ?>
        </div>
        <div class="col-6">
            <div class="row">
                <div class="col-12">
                    <form action="<?= $this->baseUrl() ?>/Administration/charakter/delete" method="post">
                        <input type="hidden" name="characterId" value="<?= $charakter->getCharakterid() ?>" />
                        <input type="hidden" name="adminId" value="<?= Zend_Auth::getInstance()->getIdentity()->userId ?>"/>
                        <input class="btn btn-danger" type="submit" value="Charakter löschen" />
                    </form>
                </div>
                <div class="col-12">
                    <?php include __DIR__ . '/partials/statistik.phtml' ?>
                    <?php include __DIR__ . '/partials/charakterwerte.phtml' ?>
                    <?php include __DIR__ . '/partials/individualTraits.phtml' ?>
                    <?php include __DIR__ . '/partials/informations.phtml' ?>
                    <?php include __DIR__ . '/partials/klasse.phtml' ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Profil
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <?php include __DIR__ . '/partials/profilbild.phtml' ?>
            <div class="row">
                <div class="col">
                    <fieldset>
                        <legend>Charaktergeschichte <span class="indicator"></span></legend>
                        <div class="subContent">
                            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/story">
                                <textarea class="data" id="story" name="story" rows="10"><?= $purifier->purify($charakter->getCharakterprofil()->getCharaktergeschichte()) ?></textarea>
                                <input type="submit" class="save btn btn-danger" value="Charaktergeschichte speichern">
                            </form>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
        <div class="col-6">
            <?php include __DIR__ . '/partials/charakterbild.phtml' ?>
            <div class="row">
                <div class="col">
                    <fieldset>
                        <legend>Private Charakterdaten <span class="indicator"></span></legend>
                        <div class="subContent">
                            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/private">
                                <textarea class="data" id="private" name="private" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getPrivatdaten()) ?></textarea>
                                <input type="submit" class="save btn btn-danger" value="Daten speichern">
                            </form>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Fähigkeiten und Magie
            </h1>
        </div>
    </div>
    <fieldset>
        <legend class="fs-2">Fähigkeiten</legend>
        <?php foreach ($skillarten as $skillart):
            if(count($skillart->getSkills()) === 0){
                continue;
            }
            ?>
            <fieldset>
                <legend class="fs-3"><?= $skillart->getBezeichnung() ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <div class="row">
                        <?php foreach ($skillart->getSkills() as $skill): ?>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="card-title">
                                        <?= $purifier->purify($skill->getBezeichnung()) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
    <fieldset>
        <legend class="fs-2">Besondere Fähigkeiten</legend>
        <?php
        foreach ($magieschulen as $schule):
            /** @var Application_Model_Schule $schoolMagic */
            $schoolMagic = array_filter($magien, function (Application_Model_Magie $magie) use ($schule) {
                return $magie->getSchule()->getId() === $schule->getId();
            });
            ?>
            <fieldset>
                <legend class="fs-3"><?= $schule->getBezeichnung() ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <div class="row">
                        <?php foreach ($schoolMagic as $magie): ?>
                            <div class="col-4">
                                <div class="card">
                                    <div class="card-body">
                                        <div class="card-title">
                                            <?= $purifier->purify($magie->getBezeichnung()) ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>

<?php include __DIR__ . '/partials/inventar.phtml' ?>
<div id="dialog"></div>