<?php
echo $this->doctype();
$layoutData = $this->layoutData;
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Fate/Alpha</title>
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/style.css') ?>" />
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
    <script type="text/javascript">
        var baseUrl ='<?= $this->baseUrl() ?>';
    </script>
    <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/themes/cupertino/jquery-ui.css" />
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
<body>
<div class="container">
    <div id="row m-3 ">
        <div id="header-logo"></div>
    </div>
    <div id="seitenbereich1">
        <div id="seitenbereich2">
            <div id="steuerung">
                <?php include __DIR__ . '/partials/steuerung.phtml'; ?>
            </div>
            <div id="inhalt">
                <?php echo $this->layout()->content; ?>
            </div>
            <div id="footer">
                <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

</html>
