<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
        <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
                crossorigin="anonymous"
        />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/style.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/login.css') ?>" />
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>

    <div class="container-xxl">
        <header>
            <picture>
                <source media="(max-width: 576px)"
                        srcset="<?= $this->baseUrl() ?>images/fp_forum_logo_custom2.jpg">
                <source media="(min-width: 577px)"
                        srcset="<?= $this->baseUrl() ?>images/fp_forum_logo_custom2.jpg">
                <img style="width: 100%;" src="<?= $this->baseUrl() ?>images/fp_forum_logo_custom2.jpg">
            </picture>
        </header>
        <div id="loginmenu" class="bg-dark">
            <form class="d-flex row" method="post" action="<?= $this->baseUrl(); ?>/login/login">
                <div class="col-4">
                    <input class="form-control" type="text" id="username" name="username" placeholder="Loginname" />
                </div>
                <div class="col-4">
                    <input class="form-control" id="passwort" type="password" name="passwort" placeholder="Passwort" />
                </div>
                <div class="col-4">
                    <input class="btn btn-primary" id="login" type="submit" name="Login" value="Login" />
                </div>
            </form>
            <nav class="navbar navbar-expand">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse justify-content-between" id="menu">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a
                                        class="nav-link text-light"
                                        href="<?= $this->baseUrl(); ?>/login/passwort"
                                >
                                    Passwort vergessen
                                </a>
                            </li>
                            <li class="nav-item">
                                <a
                                        class="nav-link text-light"
                                        href="<?= $this->baseUrl(); ?>/login/registrierung"
                                >
                                    Registrieren
                                </a>
                            </li>
                            <li class="nav-item">
                                <a
                                        class="nav-link text-light"
                                        href="<?= $this->baseUrl(); ?>/index"
                                >
                                    Startseite
                                </a>
                            </li>
                            <li class="nav-item">
                                <a
                                        class="nav-link text-light"
                                        href="<?= $this->baseUrl(); ?>/index/intro"
                                >
                                    Für Einsteiger
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div id="seitenbereich1">
            <div id="navigation">
                <div class="container">
                    <form name="Login" method="post" action="<?= $this->baseUrl(); ?>/login/login">
                        <div class="row">
                            <div class="mb-1">
                                <label class="form-label" for="username">Benutzername</label>
                                <input class="form-control" type="text" id="username" name="username" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-1">
                                <label class="form-label" for="passwort">Passwort</label>
                                <input class="form-control" id="passwort" type="password" name="passwort" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <input class="btn btn-primary" id="login" type="submit" name="Login" value="Login" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12">
                                <a href="<?= $this->baseUrl(); ?>/login/passwort">Passwort vergessen</a>
                            </div>
                        </div>
                        <div class="row">
                            <a href="<?= $this->baseUrl(); ?>/login/registrierung">Registrieren</a>
                        </div>
                    </form>
                    <div class="row">
                        <a href="<?= $this->baseUrl(); ?>/index">Startseite</a>
                    </div>
                    <div class="row">
                        <a href="http://alpha.mainchat.de/">Chat</a>
                    </div>
                    <div class="row">
                        <a href="<?= $this->baseUrl(); ?>/index/intro">Für Einsteiger</a>
                    </div>
                </div>
            </div>
            <div id="seitenbereich2">
                <div id="inhalt">

                    <?php echo $this->layout()->content; ?>

                </div>
                <div id="footer">
                    <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
                </div>
            </div>
        </div>
    </div>
    </body>
</html>