<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/style.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Admin.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Changelog.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Charakter.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/PM.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Profil.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Skills.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Wetter.css" />
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <div id="header-logo">

            </div>
        </div>
        <div id="seitenbereich1">
            <div id="navigation">
                <form name="Login" method="post" action="<?= $this->baseUrl(); ?>/login/login">
                    <label for="username">Benutzername</label>
                    <input type="text" id="username" name="username" size="20" /> <br />
                    <label for="passwort">Passwort</label>
                    <input id="passwort" type="password" name="passwort" size="20" />
                    <br />
                    <input id="login" type="submit" name="Login" value="Login" />   <a href="<?= $this->baseUrl(); ?>/login/passwort">Passwort vergessen</a> <br />
                </form>
                <input class="Button" type="button" onclick="window.location.href = '<?= $this->baseUrl(); ?>/login/registrierung';" value="Registrieren"/>
                <br />
                <br />
                <p>
                    <a href="<?= $this->baseUrl(); ?>/index">Startseite</a>
                </p>
                <p>
                    <a href="http://alpha.mainchat.de/">Chat</a>
                </p>
                <p>
                    Informationen
                </p>
                <p>
                    <a href="<?= $this->baseUrl(); ?>/index/intro">Für Einsteiger</a>
                </p>
            </div>
            <div id="seitenbereich2">
                <div id="inhalt">

                    <?php echo $this->layout()->content; ?>

                </div>
                <div id="footer">
                    <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
                </div>
            </div>
        </div>
    </body>
</html>