<?php
echo $this->doctype();
/* @var $layoutData Application_Model_Layout */
$layoutData = $this->layoutData;
if ($layoutData->getHasChara() === true) {
    $charaData = $layoutData->getCharakter();
    $training = $layoutData->charakterTraining;
}
$displayTraining = array(
    'staerke' => 'Stärke',
    'agilitaet' => 'Agilität',
    'ausdauer' => 'Ausdauer',
    'uebung' => 'Übung',
    'kontrolle' => 'Kontrolle',
    'disziplin' => 'Disziplin',
        );
$dateEnd = new DateTime('2018-09-01 20:00:00');
$date = new DateTime();
$difference = date_diff($date, $dateEnd, true);
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/style.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Admin.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Changelog.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Charakter.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/PM.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Profil.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Skills.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->autoVersion($this->baseUrl() . '/styles/Wetter.css') ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/js/tooltipster/css/tooltipster.css"/>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/themes/cupertino/jquery-ui.css" />
        <?= $this->headLink() ?>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
        <script type="text/javascript">
            var baseUrl ='<?= $this->baseUrl() ?>';
        </script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/tooltipster/js/jquery.tooltipster.min.js"></script>
        <script type="text/javascript" src="<?= $this->autoVersion($this->baseUrl() . '/js/custom/userlist/tooltips.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->autoVersion($this->baseUrl() . '/js/custom/general/map.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->autoVersion($this->baseUrl() . '/js/custom/general/general.js') ?>"></script>
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <div id="header-logo">

            </div>
        </div>
        <div id="seitenbereich1">
            <div id="navigation">
                <?php include __DIR__ . '/partials/character.phtml'; ?>
            </div>
            <div id="navigationrechts">
                <?php include __DIR__ . '/partials/fuyuki.phtml'; ?>
            </div>
            <div id="seitenbereich2">
                <div id="steuerung">
                    <?php include __DIR__ . '/partials/steuerung.phtml'; ?>
                </div>
                <div>
                    <?= $difference->format("Tage: %d Stunden: %h Minuten: %i") ?>
                </div>
                <div id="inhalt">
                    <?php if (count($layoutData->getNotifications()) > 0) : ?>
                    <div id="notifications">
                        <?php
                            /* @var $notification Application_Model_Notification */
                        foreach ($layoutData->getNotifications() as $notification) :?>
                        <p class="notification">
                            Neue Nachricht im Gruppenchat der Gruppe: 
                            <a href="<?= $this->baseUrl() ?>/Gruppen/index/show/id/<?= $notification->getParentId() ?>#<?= $notification->getNotificationElementId() ?>">
                            <?= htmlentities($notification->getParentName()) ?>
                            </a>
                        </p>
                        <?php endforeach; ?>
                    </div>
                    <?php endif; ?>
                    <?= $this->layout()->content; ?>
                </div>
                <div id="footer">
                    <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
                </div>
            </div>
        </div>
    </body>
<div id="dialog"></div>
</html>