<?php 
echo $this->doctype();
$layoutData = $this->layoutData;
if($layoutData->getHasChara() === true){
    $charaData = $layoutData->getCharakter();
    $training = $layoutData->charakterTraining;
}
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Fate/Alpha</title>
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/style.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Admin.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Changelog.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Charakter.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/PM.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Profil.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Skills.css" />
  <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Wetter.css" />
</head>
<body>
    <div id="header">
        <div id="header-logo">

        </div>
    </div>
    <div id="seitenbereich1">
        <div id="navigation">
            <?php
            if($layoutData->getHasChara() !== TRUE){
            ?>
            <p class="Meldung">Du hast noch keinen Charakter erstellt.</p>
            <p class="Meldung"><a href="<?= $this->baseUrl() ?>/charakter/create">Zur Charaktererstellung</a></p>

            <?php
            }else{
            ?>
                <ul style="list-style-type: none;">
                    <li><h3><a href="<?= $this->baseUrl() ?>/charakter"><?= $charaData->getVorname().' '.$charaData->getNachname(); ?></a></h3></li>
                    <li><br></li>
                    <li>Aktuelles Training: 
                <?php 
                    if($training['Dauer'] < 1){
                        echo " - ";
                    }
                ?> 
                    </li>
                <?php
                    if($training['Dauer'] > 0){
                        echo '<li>'.$training['Training'].' ('.$training['Dauer'].' Tage)</li>';
                    } 
                ?>
                    <li><hr></li>
                    <li><br></li>
                    <li><br></li>
                    <li><a href="<?= $this->baseUrl() ?>/training">Training</a></li>
                    <li><a href="<?= $this->baseUrl() ?>/magic">Magie</a></li>
                    <li><a href="<?= $this->baseUrl() ?>/skill">Fähigkeiten</a></li>
                </ul>
            <?php
            }
            ?>
        </div>
        <div id="navigationrechts">
            <p></p>
              <h3>Fuyuki-City</h3>
            <ul style="list-style-type: none;">
              <li><a href="<?= $this->baseUrl() ?>/news">Fuyuki-News</a></li>
              <li><a href="<?= $this->baseUrl() ?>/wetter">Wetterbericht</a></li>
            <?php
            if($layoutData->getUsergruppe() === 'Admin'){ ?>
              <li><br /></li>
              <li><br /></li>
              <li><hr /></li>
              <li><a href="<?= $this->baseUrl() ?>/admin">Admincenter</a></li>
            <?php } ?> 
            </ul>
        </div>
        <div id="seitenbereich2">
            <div id="steuerung">
                <ul>
                    <li><a href="<?= $this->baseUrl() ?>/index">Startseite</a></li>
                    <li>
                        <a href="" onclick="return false;">Informationen</a>
                            <ul>
                                <li><a href="<?= $this->baseUrl() ?>/changelog">Changelog</a></li>
                                <?php
//                                    foreach ($Informationen as $Information){
//                                        echo '<li><a href="Informationen.php?ID='.$Information['ID'].'">'.htmlentities($Information['Name']).'</a></li>';
//                                    }
                                ?>
                            </ul>
                    </li>
                    <li>
                        <a href="" onclick="return false;">Community</a>
                            <ul>
                                <li><a href="http://fate-alpha.forumprofi.de/index.php" target="_blank">Forum</a></li>
                                <li><a href="http://alpha.mainchat.de/" target="_blank">Chat</a></li>
                                <li><a href="<?= $this->baseUrl() ?>/spielergruppen">Spielergruppen</a></li>
                                <li><a href="<?= $this->baseUrl() ?>/npc">NPCs</a></li>
                            </ul>
                    </li>
                    <li><a href="<?= $this->baseUrl() ?>/charakter/friends">Userliste</a></li>
                    <li>
                        <a href="" onclick="return false;">
                            Profil   
                            <?php 
                                if($layoutData->getUnreadPmCount() > 0){
                                    echo ' ('.$layoutData->getUnreadPmCount().'&#9993;)';
                                }
                            ?>

                        </a>
                            <ul>
                                <li><a href="<?= $this->baseUrl() ?>/charakter">Charakter</a></li>
                                <li><a href="<?= $this->baseUrl() ?>/user">Spieler</a></li>
                                <li><a href="<?= $this->baseUrl() ?>/pm">Nachrichten</a></li>

                            </ul>
                    </li>
                    <li><a href="<?= $this->baseUrl() ?>/login/logout">Logout</a></li>
                </ul>
            </div>
            <div id="inhalt">
                
                <?php echo $this->layout()->content; ?>
                
            </div>
            <div id="footer">
                <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
            </div>
        </div>
    </div>
    
</body>

</html>