<?php 
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
<!--        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/style.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/themes/cupertino/jquery-ui.css" />-->
        <?= $this->headLink() ?>
<!--        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/jquery-ui.min.js"></script>-->
        <?= $this->headScript() ?>
    </head>
<body>
    <?php echo $this->layout()->content; ?>
</body>
</html>