<?php
echo $this->doctype();
$layoutData = $this->layoutData;

if ($layoutData->getHasChara() === true) {
    $charaData = $layoutData->getCharakter();
    $training = $layoutData->charakterTraining;
}
$displayTraining = array(
    'staerke' => 'Stärke',
    'agilitaet' => 'Agilität',
    'ausdauer' => 'Ausdauer',
    'uebung' => 'Übung',
    'kontrolle' => 'Kontrolle',
    'disziplin' => 'Disziplin',
        );
$dateEnd = new DateTime('2018-08-12 20:00:00');
$date = new DateTime();
$difference = date_diff($date, $dateEnd, true);
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/style.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Admin.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Changelog.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Charakter.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/PM.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Profil.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Skills.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Wetter.css<?= $this->versionString ?>" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Training.css<?= $this->versionString ?>" />
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-2.1.3.min.js<?= $this->versionString ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/jquery-ui.min.js<?= $this->versionString ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/tooltipster/js/jquery.tooltipster.min.js<?= $this->versionString ?>"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/userlist/tooltips.js<?= $this->versionString ?>"></script>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/themes/cupertino/jquery-ui.css<?= $this->versionString ?>" />
        <script type="text/javascript">
            var baseUrl ='<?= $this->baseUrl() ?>';
        </script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/general/map.js<?= $this->versionString ?>"></script>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="header">
            <div id="header-logo">

            </div>
        </div>
        <div id="seitenbereich1">
            <div id="navigation">
                <?php include __DIR__ . '/partials/menu.phtml'; ?>
            </div>
            <div id="navigationrechts">
                <?php include __DIR__ . '/partials/info.phtml'; ?>
            </div>
            <div id="seitenbereich2">
                <div id="steuerung">
                    <?php include __DIR__ . '/partials/steuerung.phtml'; ?>
                </div>
<div>
    <?= $difference->format("Jahre: %y Monate: %m Tage: %d Stunden: %h Minuten: %i") ?>
</div>
                <div id="inhalt">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="footer">
                    <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
                </div>
            </div>
        </div>
    </body>
<div id="dialog"></div>
</html>