<?php
echo $this->doctype();
$layoutData = $this->layoutData;

if ($layoutData->getHasChara() === true) {
    $charaData = $layoutData->getCharakter();
    $training = $layoutData->charakterTraining;
}
$displayTraining = array(
    'staerke' => 'Stärke',
    'agilitaet' => 'Agilität',
    'ausdauer' => 'Ausdauer',
    'uebung' => 'Übung',
    'kontrolle' => 'Kontrolle',
    'disziplin' => 'Disziplin',
        )
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Fate/Alpha</title>
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/style.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Admin.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Changelog.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Charakter.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/PM.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Profil.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Skills.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Wetter.css" />
        <link rel="stylesheet" type="text/css" media="screen" href="<?= $this->baseUrl() ?>/styles/Training.css" />
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-ui-1.11.2/jquery-ui.min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/js/jquery-2.1.3.min.js"></script>
    </head>
    <body>
        <div id="header">
            <div id="header-logo">

            </div>
        </div>
        <div id="seitenbereich1">
            <div id="navigation">
                <?php include __DIR__ . '/partials/menu.phtml'; ?>
            </div>
            <div id="navigationrechts">
                <?php include __DIR__ . '/partials/info.phtml'; ?>
            </div>
            <div id="seitenbereich2">
                <div id="steuerung">
                    <?php include __DIR__ . '/partials/steuerung.phtml'; ?>
                </div>
                <div id="inhalt">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="footer">
                    <a href="<?= $this->baseUrl(); ?>/index/impressum">Impressum</a>
                </div>
            </div>
        </div>
    </body>
</html>