<?php
/* @var $information Administration_Model_Information */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$lastKategorie = null;

$categories = [];
foreach ($this->list as $information) {
    if (!isset($categories[$information->getKategorie()])) {
        $categories[$information->getKategorie()] = [
            'name' => $information->getKategorie(),
            'informations' => [],
        ];
    }
    $categories[$information->getKategorie()]['informations'][] = $information;
}

?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Informationen
            </h1>
        </div>
    </div>
    <?php
    foreach ($categories as $key => $category) {
        $infos = $category['informations'];
        usort($infos, function (Application_Model_Information $a, Application_Model_Information $b) {
            return strcmp(lcfirst($a->getName()), lcfirst($b->getName()));
        });

        ?>
        <div class="row">
            <div class="col-12">
                <h2 class="fs-2" id="<?= $key ?>">
                    <?= $category['name'] ?>
                </h2>
            </div>
        </div>
        <div class="row">
            <?php foreach ($infos as $information): ?>
                <div class="col-4 p-2">
                    <a href="<?= $this->baseUrl() ?>/Administration/information/show/id/<?= $information->getInformationId() ?>">
                        <div class="card" style="height: 8rem; overflow: auto">
                            <div class="card-body">
                                <div class="card-title fs-3">
                                    <?= $purifier->purify($information->getName()) ?>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
        <?php
    }
    ?>
</div>