<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/formular.js'));
$purifier = $this->purifier;
?>
<h1>Informationen anlegen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/information/create" method="post" name="information" id="information">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input required="" type="text" size="30" name="name" id="name" />
            <label for="kategorie">Kategorie</label>
            <select name="kategorie" id="kategorie">
                <?php foreach($this->kategorien as $kategorie): ?>
                <option><?= $kategorie ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <fieldset>
            <legend>
                Vorraussetzungen
            </legend>
            <?= $this->partial('partials/values.phtml', ['requirementList' => new Administration_Model_Requirementlist()]) ?>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/groups.phtml', ['groups' => $this->klassengruppen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/classes.phtml', ['classes' => $this->klassen, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <div>
                <?= $this->partial('partials/traits.phtml', ['traits' => $this->traits, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
            </div>
            <div>
                <div style="width: 50%; display: inline-block; vertical-align: top">
                    <?= $this->partial('partials/skills.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/skillsAny.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/magic.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <?= $this->partial('partials/magicAny.phtml', ['magic' => $this->magien, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <?= $this->partial('partials/skillsNone.phtml', ['skills' => $this->skills, 'requirementList' => new Administration_Model_Requirementlist()]) ?>
                </div>
            </div>
        </fieldset>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Information speichern" />
    </div>
</form>