<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/formular.js'));
?>
<h1>Informationen anlegen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/information/create" method="post" name="information" id="information">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input required="" type="text" size="30" name="name" id="name" />
            <label for="kategorie">Kategorie</label>
            <select name="kategorie" id="kategorie">
                <?php foreach($this->kategorien as $kategorie): ?>
                <option><?= $kategorie ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
        <fieldset>
            <legend>
                Vorraussetzungen
            </legend>
            <div>
                <label for="staerke">Stärke</label>
                <input type="number" size="30" name="staerke" id="staerke" value="" />
            </div>
            <div>
                <label for="agilitaet">Agilität</label>
                <input type="number" size="30" name="agilitaet" id="agilitaet" value="" />
            </div>
            <div>
                <label for="ausdauer">Ausdauer</label>
                <input type="number" size="30" name="ausdauer" id="ausdauer" value="" />
            </div>
            <div>
                <label for="kontrolle">Kontrolle</label>
                <input type="number" size="30" name="kontrolle" id="kontrolle" value="" />
            </div>
            <div>
                <label for="disziplin">Disziplin</label>
                <input type="number" size="30" name="disziplin" id="disziplin" />
            </div>
            <div>
                <label for="uebung">Übung</label>
                <input type="number" size="30" name="uebung" id="uebung" />
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <label for="gruppen" style="vertical-align: top">
                        Klassengruppen:
                    </label>
                    <select name="gruppen[]" multiple="true" size="5">
                        <?php foreach ($this->klassengruppen as $gruppe) { ?>
                        <option value="<?= $gruppe->getId() ?>">
                            <?= $gruppe->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <label for="klassen" style="vertical-align: top">
                        Klassen:
                    </label>
                    <select name="klassen[]" multiple="true" size="5">
                        <?php foreach ($this->klassen as $klasse) { ?>
                        <option value="<?= $klasse->getId() ?>">
                            <?= $klasse->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div>
                <label for="trait">
                    Nicht kombinierbar mit den Traits:
                </label>
                <select name="trait[]" multiple="true" size="8">
                    <?php foreach ($this->traits as $trait) { ?>
                        <option value="<?= $trait->getTraitId() ?>">
                            <?= $trait->getName() ?>
                        </option>
                    <?php } ?>
                </select>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <label for="skills" style="vertical-align: top">
                        Fähigkeiten:
                    </label>
                    <select name="skills[]" id="skills" multiple="true" size="8">
                        <?php foreach ($this->skills as $skill) { ?>
                        <option value="<?= $skill->getId() ?>">
                            <?= $skill->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <label for="skillsAny" style="vertical-align: top">
                        Irgendeine von diesen Fähigkeiten:
                    </label>
                    <select name="skillsAny[]" id="skillsAny" multiple="true" size="8">
                        <?php foreach ($this->skills as $skill) { ?>
                        <option value="<?= $skill->getId() ?>">
                            <?= $skill->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <label for="skillsIncompatible" style="vertical-align: top">
                        Nicht kombinierbar mit:
                    </label>
                    <select name="skillsIncompatible[]" multiple="true" size="8">
                        <?php foreach ($this->skills as $skill) { ?>
                        <option value="<?= $skill->getId() ?>">
                            <?= $skill->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div>
                <div style="width: 50%; display: inline-block;">
                    <label for="magien" style="vertical-align: top">
                        Magien:
                    </label>
                    <select name="magien[]" id="magien" multiple="true" size="8">
                        <?php foreach ($this->magien as $magie) { ?>
                        <option value="<?= $magie->getId() ?>">
                            <?= $magie->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
                <div style="width: 45%; display: inline-block;">
                    <label for="magienAny" style="vertical-align: top">
                        Irgendeine von diesen Magien:
                    </label>
                    <select name="magienAny[]" id="magienAny" multiple="true" size="8">
                        <?php foreach ($this->magien as $magie) { ?>
                        <option value="<?= $magie->getId() ?>">
                            <?= $magie->getBezeichnung() ?>
                        </option>
                        <?php } ?>
                    </select>
                </div>
            </div>
        </fieldset>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Information speichern" />
    </div>
</form>