<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/formular.js'));
/* @var $information Administration_Model_Information */
$information = $this->information;
?>
<h1>Information ändern</h1>
<form action="<?= $this->baseUrl() ?>/Administration/information/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $this->purifier->purify($information->getName()) ?>" />
            <label for="kategorie">Kategorie</label>
            <select name="kategorie" id="kategorie">
                <?php foreach($this->kategorien as $kategorie): ?>
                <option <?= $information->getKategorie() === $kategorie ? 'selected=""' : '' ?>><?= $kategorie ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        <textarea name="inhalt" cols="80" rows="10"><?= $this->purifier->purify($information->getInhalt()) ?></textarea>
        <fieldset>
            <legend>
                Vorraussetzungen
            </legend>
            <p>
                <label for="staerke">Stärke</label>
                <input type="checkbox" name="str" id="str">
                <input type="text" size="30" name="staerke" id="staerke" disabled="true" />
            </p>
            <p>
                <label for="agilitaet">Agilität</label>
                <input type="checkbox" name="agi" id="agi">
                <input type="text" size="30" name="agilitaet" id="agilitaet" disabled="true" />
            </p>
            <p>
                <label for="ausdauer">Ausdauer</label>
                <input type="checkbox" name="aus" id="aus">
                <input type="text" size="30" name="ausdauer" id="ausdauer" disabled="true" />
            </p>
            <p>
                <label for="uebung">Übung</label>
                <input type="checkbox" name="pra" id="pra">
                <input type="text" size="30" name="uebung" id="uebung" disabled="true" />
            </p>
            <p>
                <label for="kontrolle">Kontrolle</label>
                <input type="checkbox" name="kon" id="kon">
                <input type="text" size="30" name="kontrolle" id="kontrolle" disabled="true" />
            </p>
            <p>
                <label for="disziplin">Disziplin</label>
                <input type="checkbox" name="dis" id="dis">
                <input type="text" size="30" name="disziplin" id="disziplin" disabled="true" />
            </p>
            <p>
            <label for="gruppen">
                Klassengruppen:
            </label>
            <select name="gruppen[]" multiple="true" size="8">
                <?php foreach ($this->klassengruppen as $gruppe) { ?>
                <option value="<?= $gruppe->getId() ?>">
                    <?= $gruppe->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="klassen">
                Klassen:
            </label>
            <select name="klassen[]" multiple="true" size="8">
                <?php foreach ($this->klassen as $klasse) { ?>
                <option value="<?= $klasse->getId() ?>">
                    <?= $klasse->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="skills">
                Fähigkeiten:
            </label>
            <select name="skills[]" multiple="true" size="8">
                <?php foreach ($this->skills as $skill) { ?>
                <option value="<?= $skill->getId() ?>">
                    <?= $skill->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            </p>
        <p>
            <label for="vorteile">
                benötigte Vorteile
            </label>
            <select name="vorteile[]" multiple="true" size="8">
                <?php foreach ($this->vorteile as $vorteil): ?>
                <option value="<?= $vorteil->getId() ?>">
                    <?= $vorteil->getBezeichnung() ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>
        <p>
            <label for="nachteile">
                benötigte Nachteile
            </label>
            <select name="nachteile[]" multiple="true" size="8">
                <?php foreach ($this->nachteile as $nachteil): ?>
                <option value="<?= $nachteil->getId() ?>">
                    <?= $nachteil->getBezeichnung() ?>
                </option>
                <?php endforeach; ?>
            </select>
        </p>
        </fieldset>
    </fieldset>
    <div align="center">
        <input type="hidden" name="informationId" value="<?= $information->getInformationId() ?>" />
        <input type="submit" name="Abschicken" id="Abschicken" value="Information speichern" />
    </div>
</form>