<h1>Admincenter</h1>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/charakter">Charakterliste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/news/new">News Verfassen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/news">News-Archiv</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/wetter">Wetterbericht</a>
    </div>
    <div class="FormularLabel">

    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/circuits/new">Magic Circuits erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/circuits">Magic Circuits</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/magie/new">Neue Magie erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/magie">Magie-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/magie/rpg">Magien per RPG</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/klasse/new">Neue Klasse erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/klasse">Klassen-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/trait/new">Neuen Trait erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/trait">Trait-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/skill/new">Neue Fähigkeit erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/skill">Fähigkeiten-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/skill/rpg">Fähigkeiten per RPG</a>
    </div>
</div>

<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/element/new">Neues Element erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/element">Element-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/schule/new">Neue Magieschule erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/schule">Magieschulen-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/npc/new">Neuen NPC erstellen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/npc">NPC-Liste</a>
    </div>
</div>
<div class="FormularZeile">
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/information/new">Informationen anlegen</a>
    </div>
    <div class="FormularLabel">
        <a href="<?= $this->baseUrl() ?>/Administration/information">Informationen anpassen</a>
    </div>
</div>