<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$profile = $this->profile;
/** @var Application_Model_Charakter $ownCharacter */
$ownCharacter = $this->ownCharacter;
?>
<div class="container">
    <div class="row p-3 m-3">
        <div class="col-12 col-md-4">
            <form class="input-group" method="post" action="<?= $this->baseUrl() ?>/Freunde/Add">
                <input
                    type="text"
                    name="Charaktercode"
                    class="form-control"
                    placeholder="Code"
                    aria-label="Code"
                    aria-describedby="button-addon2"
                >
                <input type="submit" class="btn btn-primary" id="button-addon2" value="Daten Freischalten" />
            </form>
        </div>
        <div class="col-12 col-md-8">
            <div>
                Der Code für deine grundlegenden Charakterdaten:
                <span class="fw-bold">
                    <?= $purifier->purify($profile->getKennenlerncode()) ?>
                </span>
            </div>
            <div>
                Der Code für deine privaten Charakterdaten:
                <span class="fw-bold">
                    <?= $purifier->purify($profile->getPrivatcode()) ?>
                </span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            Hier findet ihr die Codes für eure grundlegenden und eure privaten Charakterdaten.
            Eure grundlegenden Charakterdaten beinhalten euer Charakterbild und eure öffentliche Charakterbeschreibung.
            Eure privaten Charakterdaten beinhalten eine zweite, geheime Charakterbeschreibung, die für Spieler gedacht ist die mehr über euren Charakter wissen dürfen.
        </div>
        <div class="col-12">
            Eure grundlegenden Charakterdaten gebt ihr an Spieler denen ihr im RPG begegnet, eure privaten Charakterdaten gebt ihr an Spieler mit denen ihr sehr viel rpgt.
        </div>
        <div class="col-12">
            Die Codes werden nach einmaliger Benutzung neu generiert.
        </div>
    </div>

    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>

    <div class="row justify-content-around">
        <div class="col-12 col-xl-10">
            <div class="card">
                <a class="card-body" href="<?= $this->baseUrl() ?>/Freunde/profil/charakter/<?= $ownCharacter->getUuid() ?>">
                    <div class="row">
                        <div class="col-4 col-md-2">
                            <img height="100" src="<?= $ownCharacter->getCharakterprofil()->getProfilpic() ?>">
                        </div>
                        <div class="col-8 col-md-2">
                            <div class="card-title fw-bold">
                                <?= $purifier->purify($ownCharacter->getVorname() . ' ' . ($ownCharacter->getNachname())) ?>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="row">
                                <div class="col-6 col-xl-2">Alter</div>
                                <div class="col-6 col-xl-3"><?= $ownCharacter->getAlter('y') ?> Jahre</div>
                                <div class="col-6 col-xl-4">Geburtstag</div>
                                <div class="col-6 col-xl-3"><?= $ownCharacter->getGeburtsdatum('d.m.Y') ?></div>
                            </div>
                            <div class="row">
                                <div class="col-6 col-xl-2">Größe</div>
                                <div class="col-6 col-xl-3"><?= $ownCharacter->getSize() ?> cm</div>
                                <div class="col-6 col-xl-4">Augenfarbe</div>
                                <div class="col-6 col-xl-3"><?= $ownCharacter->getAugenfarbe() ?></div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h1 class="fs-1">Dir bekannte Charaktere</h1>
        </div>
    </div>
    <div class="row mt-3">
        <?php
        foreach ($this->friendlist as $charakter) {
        /** @var Application_Model_Charakter $charakter */
        ?>
            <div class="col-12 col-xl-6 p-1">
                <div class="card">
                    <a class="card-body" href="<?= $this->baseUrl() ?>/Freunde/profil/charakter/<?= $charakter->getUuid() ?>">
                        <div class="row">
                            <div class="col-5 col-xl-3">
                                <img height="80" src="<?= $charakter->getCharakterprofil()->getProfilpic() ?>">
                            </div>
                            <div class="col-7 col-xl-9">
                                <div class="card-title fw-bold">
                                    <?= $purifier->purify($charakter->getVorname() . ' ' . ($charakter->getNachname())) ?>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-xl-2">Alter</div>
                            <div class="col-6 col-xl-3"><?= $charakter->getAlter('y') ?> Jahre</div>
                            <div class="col-6 col-xl-4">Geburtstag</div>
                            <div class="col-6 col-xl-3"><?= $charakter->getGeburtsdatum('d.m.Y') ?></div>
                        </div>
                        <div class="row">
                            <div class="col-6 col-xl-2">Größe</div>
                            <div class="col-6 col-xl-3"><?= $charakter->getSize() ?> cm</div>
                            <div class="col-6 col-xl-4">Augenfarbe</div>
                            <div class="col-6 col-xl-3"><?= $charakter->getAugenfarbe() ?></div>
                        </div>
                    </a>
                </div>
            </div>
        <?php
        }
        ?>
    </div>

</div>

<img src="http://i.imgur.com/fjIL23b.jpg">