<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$profile = $this->profile;
?>
<div class="Zentriert">
    <form method="post" action="<?= $this->baseUrl() ?>/Freunde/Add">
        <input type="text" name="Charaktercode" >
        <input type="submit" name="Freischalten" value="Charakter freischalten">
    </form>
    <p>
        Der Code für deine grundlegenden Charakterdaten: 
        <strong>
            <?= $purifier->purify($profile->getKennenlerncode()) ?>
        </strong>.
        <br />
        Der Code für deine privaten Charakterdaten: 
        <strong>
            <?= $purifier->purify($profile->getPrivatcode()) ?>
        </strong>.
    </p>
    <div style="text-align: left">
        <p>
            Hier findet ihr die Codes für eure grundlegenden und eure privaten Charakterdaten.
            Eure grundlegenden Charakterdaten beinhalten euer Charakterbild und eure öffentliche Charakterbeschreibung.
            Eure privaten Charakterdaten beinhalten eine zweite, geheime Charakterbeschreibung, die für Spieler gedacht ist die mehr über euren Charakter wissen dürfen. 
        </p>
        <p>
            Eure grundlegenden Charakterdaten gebt ihr an Spieler denen ihr im RPG begegnet, eure privaten Charakterdaten gebt ihr an Spieler mit denen ihr sehr viel rpgt. 
        </p>
        <p>
            Die Codes werden nach einmaliger Benutzung neu generiert.
        </p>
    </div>
</div>
<hr>
<h1>Dir bekannte Charaktere</h1>
<ul class="userlist">
    <li class="charakter" id="<?= $this->eigenerCharakter->getCharakterId(); ?>">
        <a href="<?= $this->baseUrl() ?>/Freunde/profil/charakter/<?= $this->eigenerCharakter->getCharakterId() ?>">
            <?= $purifier->purify($this->eigenerCharakter->getVorname() . ' ' . ($this->eigenerCharakter->getNachname())) ?>
        </a>
    </li>
<?php
foreach ($this->friendlist as $charakter) {
?>
    <li class="charakter" id="<?= $charakter->getCharakterId() ?>">
        <a href="<?= $this->baseUrl() ?>/Freunde/profil/charakter/<?= $charakter->getCharakterId() ?>">
            <?= $purifier->purify($charakter->getVorname()) . ' ' . ($charakter->getNachname()) ?>
        </a>
    </li>
<?php
}
?>
</ul>
<img src="http://i.imgur.com/fjIL23b.jpg">