<?php
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$this->headScript()->appendScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headScript()->appendScript('var id = ' . $charakter->getCharakterid(), 'text/javascript');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/profile.js'));
?>
<div id="dialog" title="<?= htmlspecialchars($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>">
    
</div>
<h1>
    <?= htmlspecialchars($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
</h1>
<div class="img">
    <img src="<?= htmlentities($charakter->getCharakterprofil()->getCharpic()) ?>"/>
</div>
<p>
    <?= $purifier->purify($charakter->getCharakterprofil()->outputCharaktergeschichte()) ?>
</p>
<div class="Zentriert">
    <h2>
        <a id="pass">
        Pass
        </a>
    </h2>
</div>
<p>
    <?= $purifier->purify($charakter->getCharakterprofil()->outputPrivatdaten()) ?>
</p>