<?php
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $magien Story_Model_Magie */
$magien = $this->magien;
?>
<fieldset>
    <legend>Magien verlernen</legend>
    <div>
        <?php if(count($magien) > 0){ ?>
            <select id="learnMagien" multiple="" size="5">
                <?php foreach($magien as $magie): ?>
                    <option value="<?= $magie->getId() ?>"><?= $purifier->purify($magie->getBezeichnung()) ?></option>
                <?php endforeach; ?>
            </select>
            <input data-art="magie" data-request="remove" class="removeMagic" type="submit" value="Speichern">
        <?php } else { ?>
            Der Charakter kann keine Magien verlernen.
        <?php } ?>
    </div>
</fieldset>