<h1>
    Fähigkeiten und Magien
</h1>
<div class="submenu">
    <ul>
        <li>
            <a href="<?= $this->baseUrl() ?>/charakter">
                Charakterdaten
            </a>
        </li>
        <li>
            <a href="<?= $this->baseUrl() ?>/charakter/profil">
                Charakterprofil
            </a>
        </li>
        <li>
            <a href="<?= $this->baseUrl() ?>/charakter/abilities">
                Magien und Fähigkeiten
            </a>
        </li>
        <li>
            <a href="<?= $this->baseUrl() ?>/charakter/inventar">
                Ausrüstung
            </a>
        </li>
    </ul>
</div>