<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/charakter/charakter.js');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/charakter/tooltips.js');

function order(Application_Model_Skillart $a, Application_Model_Skillart $b){
$sortorder = ['Übungsfähigkeiten' => 1, 
    'Schützenfähigkeiten' => 2, 
    'Kämpferfähigkeiten' => 3, 
    'Spezialfähigkeiten' => 4,
    ];
    if($sortorder[$a->getBezeichnung()] > $sortorder[$b->getBezeichnung()]){
        return 1;
    }
}
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
/* @var $skillart Application_Model_Skillart */
$skillarten = $this->skillarten;
usort($skillarten, "order");
/* @var $schule Application_Model_Schule */
$magieschulen = $this->magieschulen;
?>
<h1>
    Fähigkeiten
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<br />
<div>
    <fieldset>
        <legend>Fähigkeiten</legend>
        <?php foreach ($skillarten as $skillart): 
            if(count($skillart->getSkills()) === 0){
                continue;
            }
        ?>
        <fieldset>
            <legend><?= $skillart->getBezeichnung() ?> <span class="indicator"></span></legend>
            <div class="subContent">
                <?php foreach ($skillart->getSkills() as $skill): ?>
                <p>
                    <span class="skill">
                        <input type="hidden" value="<?= $skill->getId() ?>">
                        <?= $skill->getBezeichnung() ?>
                    </span>
                    <span>
                        <button class="details skills" data-id="<?= $skill->getId() ?>">
                            Details
                        </button>
                    </span>
                    <span>
                        <button class="upgrade skills">
                            nächste Stufe
                        </button>
                    </span>
                </p>
                <?php endforeach; ?>
            </div>
        </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Besondere Fähigkeiten</legend>
        <?php foreach ($magieschulen as $schule): ?>
            <fieldset>
                <legend><?= $schule->getBezeichnung() ?> <span class="indicator"></span></legend>
                <div class="subContent">
                    <?php foreach ($schule->getMagien() as $magie): ?>
                    <p>
                        <span class="magie">
                            <input type="hidden" value="<?= $magie->getId() ?>">
                            <?= $magie->getBezeichnung() ?>
                        </span>
                    <span>
                        <button class="details magic" data-id="<?= $magie->getId() ?>">
                            Details
                        </button>
                    </span>
                    <span>
                        <button class="upgrade magic">
                            nächste Stufe
                        </button>
                    </span>
                    </p>
                    <?php endforeach; ?>
                </div>
            </fieldset>
        <?php endforeach; ?>
    </fieldset>
</div>
<div id="dialog"></div>