<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/tooltips.js'));

/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;


$order = [
    'Übungsfähigkeiten' => 1,
    'Schützenfähigkeiten' => 2,
    'Kämpferfähigkeiten' => 3,
    'Spezialfähigkeiten' => 4,
];

$order = function (Application_Model_Skillart $a, Application_Model_Skillart $b) use ($order) {
    return $order[$a->getBezeichnung()] > $order[$b->getBezeichnung()];
};

/* @var $skill Application_Model_Skill */
/* @var $skillart Application_Model_Skillart */
$skillarten = $this->skillarten;
usort($skillarten, $order);

/* @var $magieschulen Application_Model_Schule[] */
$magieschulen = $this->magieschulen;
$magien = $this->magien;
?>
<div class="row">
    <div class="col">
        <h1 class="fs-1">
            Fähigkeiten
        </h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="submenu">
            <?php include __DIR__ . '/partials/submenu.phtml'; ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="col fs-2">
        Fähigkeiten
    </div>
</div>
<div class="row">
    <?php foreach ($skillarten as $skillart):
        if (count($skillart->getSkills()) === 0) {
            continue;
        }
        ?>
        <fieldset class="col-12 col-lg-4">
            <legend class="fs-3"><?= $skillart->getBezeichnung() ?> <span class="indicator"></span></legend>
            <div class="subContent">
                <?php foreach ($skillart->getSkills() as $skill): ?>
                    <div class="row m-1">
                        <div class="col-6">
                            <input type="hidden" value="<?= $skill->getId() ?>">
                            <?= $purifier->purify($skill->getBezeichnung()) ?>
                        </div>
                        <div class="col-3">
                            Rang: <?= $skill->getRang() ?>
                        </div>
                        <div class="col-3">
                            <a class="details skills btn btn-info" data-id="<?= $skill->getId() ?>">
                                Details
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    <?php endforeach; ?>
</div>

<div class="row">
    <div class="col fs-2">
        Magieschulen und Magien
    </div>
</div>
<div class="row">
    <?php
    foreach ($magieschulen as $schule):
        /** @var Application_Model_Schule $schoolMagic */
        $schoolMagic = array_filter($magien, function (Application_Model_Magie $magie) use ($schule) {
            return $magie->getSchule()->getId() === $schule->getId();
        });
    ?>
        <fieldset class="col-12 col-lg-4">
            <legend class="fs-3"><?= $purifier->purify($schule->getBezeichnung()) ?> <span class="indicator"></span></legend>
            <div class="subContent">
                <?php foreach ($schoolMagic as $magie): ?>
                    <div class="row m-1">
                        <div class="col-6">
                            <input type="hidden" value="<?= $magie->getId() ?>">
                            <?= $purifier->purify($magie->getBezeichnung()) ?>
                        </div>
                        <div class="col-3">
                            Rang: <?= $magie->getRang() ?>
                        </div>
                        <div class="col-3">
                            <a class="details magic btn btn-info" data-id="<?= $magie->getId() ?>">
                                Details
                            </a>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    <?php endforeach; ?>
</div>
<div id="dialog"></div>