<?php
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
?>
<h1>
    Bonustraining
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<div id="root"></div>
<div id="accessKey" style="display: none"><?= $this->accessKey ?></div>
<script type="text/javascript" src="<?= $this->autoVersion($this->baseUrl() . '/js/custom/bonus/main.js') ?>"></script>
<link rel="stylesheet" type="text/css" href="<?= $this->autoVersion($this->baseUrl() . '/js/custom/bonus/main.css') ?>" />