<?php
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
$categoryStr = $werte->getCategory('str');
$categoryAgi = $werte->getCategory('agi');
$categoryAus = $werte->getCategory('aus');
$categoryKon = $werte->getCategory('kon');
$categoryDis = $werte->getCategory('dis');
/* @var $trainingswerte Application_Model_Trainingswerte */
$trainingswerte = $this->trainingswerte;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/bonus.js'));
?>
    <h2>
        Verfügbare Trainingstage: <span id="trainingstage"><?= $werte->getStartpunkte() ?></span>
    </h2>
    <div>
        <h3>
            Grundwerte
        </h3>
        <?php
        if($trainingswerte->getStrTraining() !== null){
        ?>
        <fieldset>
            <legend>
                Stärke
            </legend>
            <div style="float: left; margin-left: 30px">
                <p>
                    <span class="concreteValue">
                        Aktueller Wert: <span class="value" id="staerkeWert"><?= $werte->getStaerke() ?></span> 
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value"  id="staerkeKategorie"><?= $werte->getCategory($werte->getStaerke()) ?></span>
                    </span>
                </p>
                <p>
                    <input type="number" class="days" name="staerke" placeholder="0" min="0"> Tage + <span class="value" ><?= $trainingswerte->getStrTraining() ?></span> pro Tag
                </p>
                <p>
                    <span class="concreteValue">
                        Neuer Wert: <span class="value"  id="staerkeWertUpdated"></span>
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value" id="staerkeKategorieUpdated"></span>
                    </span>
                    
                </p>
            </div>
            <div style="float: right; vertical-align: middle">
                <button style="width: 200px; height: 70px" class="execute" id="staerke">Stärke Trainieren</button>
            </div>
            <div style="clear: both"></div>
        </fieldset>
        <?php
        }
        ?>
        <?php
        if($trainingswerte->getAgiTraining() !== null){
        ?>
        <fieldset>
            <legend>
                Agilität
            </legend>
            <div style="float: left; margin-left: 30px">
                <p>
                    <span class="concreteValue">
                        Aktueller Wert: <span class="value" id="agilitaetWert"><?= $werte->getAgilitaet() ?></span> 
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value"  id="agilitaetKategorie"><?= $werte->getCategory($werte->getAgilitaet()) ?></span>
                    </span>
                </p>
                <p>
                    <input type="number" class="days" name="agilitaet" placeholder="0" min="0"> Tage + <span class="value" ><?= $trainingswerte->getAgiTraining() ?></span> pro Tag
                </p>
                <p>
                    <span class="concreteValue">
                        Neuer Wert: <span class="value"  id="agilitaetWertUpdated"></span>
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value" id="agilitaetKategorieUpdated"></span>
                    </span>
                    
                </p>
            </div>
            <div style="float: right; vertical-align: middle">
                <button style="width: 200px; height: 70px" class="execute" id="agilitaet">Agilität Trainieren</button>
            </div>
            <div style="clear: both"></div>
        </fieldset>
        <?php
        }
        ?>
        <?php
        if($trainingswerte->getAusTraining() !== null){
        ?>
        <fieldset>
            <legend>
                Ausdauer
            </legend>
            <div style="float: left; margin-left: 30px">
                <p>
                    <span class="concreteValue">
                        Aktueller Wert: <span class="value" id="ausdauerWert"><?= $werte->getAusdauer() ?></span> 
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value"  id="ausdauerKategorie"><?= $werte->getCategory($werte->getAusdauer()) ?></span>
                    </span>
                </p>
                <p>
                    <input type="number" class="days" name="ausdauer" placeholder="0" min="0"> Tage + <span class="value" ><?= $trainingswerte->getAusTraining() ?></span> pro Tag
                </p>
                <p>
                    <span class="concreteValue">
                        Neuer Wert: <span class="value"  id="ausdauerWertUpdated"></span>
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value" id="ausdauerKategorieUpdated"></span>
                    </span>
                    
                </p>
            </div>
            <div style="float: right; vertical-align: middle">
                <button style="width: 200px; height: 70px" class="execute" id="ausdauer">Ausdauer Trainieren</button>
            </div>
            <div style="clear: both"></div>
        </fieldset>
        <?php
        }
        ?>
    </div>
    <?php if($trainingswerte->getKonTraining() !== null OR $trainingswerte->getDisTraining() !== null): ?>
    <div>
        <h3>
            Klassenwerte
        </h3>
        <?php
        if($trainingswerte->getKonTraining() !== null){
        ?>
        <fieldset>
            <legend>
                Kontrolle
            </legend>
            <div style="float: left; margin-left: 30px">
                <p>
                    <span class="concreteValue">
                        Aktueller Wert: <span class="value" id="kontrolleWert"><?= $werte->getKontrolle() ?></span> 
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value"  id="kontrolleKategorie"><?= $werte->getCategory($werte->getKontrolle()) ?></span>
                    </span>
                </p>
                <p>
                    <input type="number" class="days" name="kontrolle" placeholder="0" min="0"> Tage + <span class="value" ><?= $trainingswerte->getKonTraining() ?></span> pro Tag
                </p>
                <p>
                    <span class="concreteValue">
                        Neuer Wert: <span class="value"  id="kontrolleWertUpdated"></span>
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value" id="kontrolleKategorieUpdated"></span>
                    </span>
                    
                </p>
            </div>
            <div style="float: right; vertical-align: middle">
                <button style="width: 200px; height: 70px" class="execute" id="kontrolle">Kontrolle Trainieren</button>
            </div>
            <div style="clear: both"></div>
        </fieldset>
        <?php
        }
        if($trainingswerte->getDisTraining() !== null){
        ?>
        <fieldset>
            <legend>
                Disziplin
            </legend>
            <div style="float: left; margin-left: 30px">
                <p>
                    <span class="concreteValue">
                        Aktueller Wert: <span class="value" id="disziplinWert"><?= $werte->getDisziplin() ?></span> 
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value"  id="disziplinKategorie"><?= $werte->getCategory($werte->getDisziplin()) ?></span>
                    </span>
                </p>
                <p>
                    <input type="number" class="days" name="disziplin" placeholder="0" min="0"> Tage + <span class="value" ><?= $trainingswerte->getDisTraining() ?></span> pro Tag
                </p>
                <p>
                    <span class="concreteValue">
                        Neuer Wert: <span class="value"  id="disziplinWertUpdated"></span>
                    </span>
                    <span class="kategorien">
                        Kategorie: <span class="value" id="disziplinKategorieUpdated"></span>
                    </span>
                    
                </p>
            </div>
            <div style="float: right; vertical-align: middle">
                <button style="width: 200px; height: 70px" class="execute" id="disziplin">Disziplin Trainieren</button>
            </div>
            <div style="clear: both"></div>
        </fieldset>
        <?php
        }
        ?>
    </div>
    <?php endif; ?>