<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/erstellung/charaktererstellung.js');
//$this->headScript()->prependFile($this->baseUrl() . '/js/erstellung/map.js');
$creationParamContainer = $this->creationParams;
$klassen = $this->creationParams['klassen'];
$vorteile = $this->creationParams['vorteile'];
$nachteile = $this->creationParams['nachteile'];
$odo = $this->creationParams['odo'];
$luck = $this->creationParams['luck'];
$circuits = $this->creationParams['circuits'];
$elemente = $this->creationParams['elemente'];
?>
<h1>
    Neuen Charakter erstellen
</h1>
<div id="dialog">
    
</div>
<form method="post" action="<?= $this->baseUrl() ?>/charakter/create">
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Vorname
            </span>
            <span class="label">
                Der Vorname hat keine Auswirkungen auf das Spiel.
            </span>
        </label>
        <div class="FormularInput">
            <input type="text" name="vorname" id="vorname" size="35" required="">
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Nachname
            </span>
            <span class="label">
                Sollte man einem größeren Clan angehören, nimmt man dessen Nachnamen an.
            </span>
        </label>
        <div class="FormularInput">
            <input type="text" name="nachname" id="nachname" size="35" required="">
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Geschlecht
            </span>
            <span class="label">
                Hat Auswirkungen auf die Liebes-Regel sowie Charme-Magien.
            </span>
        </label>
        <div class="FormularInput">
            <input type="radio" id="m" name="geschlecht" required="" value="m"> <label for="m">Männlich</label>
            <input type="radio" id="w" name="geschlecht" required="" value="w"> <label for="w">Weiblich</label>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Geburtsdatum
            </span>
            <span class="label">
                Das Alter gibt die Gesellschaft und Bekanntenkreis an in welchem man sich bei Spielbeginn befindet, hat aber auch Einfluss auf die eigenen Werte. 
                (12-18 = Schüler / 19+ Erwachsen / 50+ Alt). 
                Der Charakter kann zwischen 12 und 90 Jahre alt sein.
            </span>
        </label>
        <div class="FormularInput">
            <input name="geburtsdatum" id="geburtsdatum" size="10" required="">
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Augenfarbe
            </span>
            <span class="label">

            </span>
        </label>
        <div class="FormularInput">
            <select name="augenfarbe" id="augenfarbe" required="">
                <option selected="" value="">bitte auswählen</option>
                <option>Blau</option>
                <option>Grün</option>
                <option>Braun</option>
                <option>Grau</option>
                <option>Schwarz</option>
                <option>Rot</option>
                <option>Lila</option>
                <option>Gelb</option>
                <option>Türkis</option>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Körpergröße
            </span>
            <span class="label">
                Der Charakter kann zwischen 130cm und 210cm groß sein.
            </span>
        </label>
        <div class="FormularInput">
            <input type="number" name="size" id="körpergröße" required="" style="width: 50px" />cm
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Sexuelle Orientierung
            </span>
            <span class="label">
                Hat Auswirkungen auf die Liebes-Regel sowie Charme-Magien.
            </span>
        </label>
        <div class="FormularInput">
            <select name="sex" id="sexualität" required="" >
                <option selected="" value="">bitte auswählen</option>
                <option>Heterosexuell</option>
                <option>Homosexuell</option>
                <option>Bisexuell</option>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">Wohnort</span>
            <span class="label">
                <a href="http://fate-alpha.forumprofi.de/thema-anzeigen-wohnort-alle-t92.html#223" target="_blank">Ort und Art der Wohnung des Charakters</a>
            </span>
        </label>
        <div class="FormularInput">
            <input type="text" name="wohnort" id="wohnort" readonly="" required=""><button id="chooseWohnort" type="button">Wohnort wählen</button>
        </div>
    </fieldset>

    <h2>
        Werte
    </h2>
    <ul>
        <li>Es können bis zu 30 Punkte verteilt werden</li>
        <li>Hinter einer Auswahlmöglichkeit steht in Klammern wieviele Punkte man bezahlt</li>
        <li>bei einem + erhält man Punkte</li>
        <li>Man muss nicht alle Punkte verteilen, darf jedoch nicht in den Minusbereich geraten</li>
    </ul>


    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Charakterklasse
            </span>
            <span class="label">

            </span>
        </label>
        <div class="FormularInput">
            <select name="klasse" id="klasse" required="" >
                <option selected="" value="">bitte auswählen</option>
                <?php
                foreach ($klassen as $klasse) {
                    ?>
                    <option value="<?= $klasse->getID() ?>">
                        <?= $klasse->getBezeichnung() . ' (' . $klasse->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Naturelement
            </span>
            <span class="label">
                Das eigene Naturelement zeigt die natürliche Affinität eines Charakters an. Eines dieser vier muss gewählt werden.
                Für Magi gewinnt es zudem an Bedeutung, da alle Magien die das eigene Naturelement in sich tragen 25% weniger FP kosten.
            </span>
        </label>
        <div class="FormularInput">
            <select name="element" id="element" required="" >
                <option selected="" value="">bitte auswählen</option>
                <?php
                foreach ($elemente as $element) {
                    if ($element->getCharakterisierung() !== null) {
                        ?>
                        <option value="<?= $element->getID() ?>">
                            <?= $element->getBezeichnung() . ' ' . $element->getCharakterisierung() ?>
                        </option>
                        <?php
                    }
                }
                ?>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Odo
            </span>
            <span class="label">
                Odo ist die Energie die Wesen für ihre magischen Fähigkeiten benötigen.
                Odo lässt sich nicht trainieren, wieviel man besitzt wird bei der Geburt entschieden und festgelegt.
                F ist der schlechteste, A der beste Wert.
            </span>
        </label>
        <div class="FormularInput ui-widget">
            <select name="odo" id="odo" required="" >
                <option selected="" value="">bitte auswählen</option>
                <?php
                foreach ($odo as $odo) {
                    $odo->getKosten() === null ? $disabled = 'disabled=""' : $disabled = '';
                    ?>
                    <option value="<?= $odo->getID() ?>" <?= $disabled ?> >
                        <?= $odo->getKategorie() . ' (' . $odo->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Magic Circuit
            </span>
            <span class="label">
                Magi besitzen sogenannte Magic Circuits im Körper mit denen sie das Odo ihres Körpers und Mana ihrer Umgebung kontrollieren und davon profitieren können.
            </span>
        </label>
        <div class="FormularInput">
            <select name="circuit" id="circuit" >
                <option selected="" value="0">bitte auswählen</option>
                <?php
                foreach ($circuits as $circuit) {
                    ?>
                    <option value="<?= $circuit->getID() ?>" >
                        <?= $circuit->getKategorie() . ' (' . $circuit->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <label class="FormularLabel">
            <span class="titel">
                Glück
            </span>
            <span class="label">
                Glück wird benötigt um kritische sowie fatale Treffer zu verhindern oder diese einem Gegner im Kampf zuzufügen. 
                Es kann zu weiteren Situationen kommen in denen der Glückswert eine Rolle spielt.
            </span>
        </label>
        <div class="FormularInput">
            <select name="luck" id="luck" required="" >
                <option selected="" value="">bitte auswählen</option>
                <?php
                foreach ($luck as $luck) {
                    $disabled = ($luck->getKosten() === null) ? 'disabled=""' : '';
                    ?>
                    <option value="<?= $luck->getID() ?>" <?= $disabled ?> >
                        <?= $luck->getKategorie() . ' (' . $luck->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </fieldset>
    <fieldset class="FormularZeile">
        <div style="display: inline-block; width: 40%;">
            <label>
                <span class="titel">Vorteile</span>
                <span class="label">
                    Zur Mehrfachwahl Strg gedrückt halten.
                </span>
            </label>
            <br />
            <select name="vorteile[]" multiple="" size="10" id="vorteile" >
                <?php
                foreach ($vorteile as $vorteil) {
                    ?>
                    <option value="<?= $vorteil->getID() ?>" >
                        <?= $vorteil->getBezeichnung() . ' (' . $vorteil->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
        <div style="display: inline-block; width: 40%;">
            <label>
                <span class="titel">Nachteile</span>
                <span class="label">
                    Zur Mehrfachwahl Strg gedrückt halten.
                </span>
            </label>
            <br />
            <select name="nachteile[]" multiple="" size="10" id="nachteile" >
                <?php
                foreach ($nachteile as $nachteil) {
                    ?>
                    <option value="<?= $nachteil->getID() ?>" >
                        <?= $nachteil->getBezeichnung() . ' (' . $nachteil->getKosten() . ')' ?>
                    </option>
                    <?php
                }
                ?>
            </select>
        </div>
    </fieldset>
    <input id="newchara" type="submit" name="newchara" value="Charakter anlegen"/>
</form>