<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/charakter/charakter.js');
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Charakterdaten
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<br />
<div>
    <div class="contentLeft">
        <fieldset>
            <legend>Charakterdaten</legend>
            <p>
                <label>
                    Name
                </label>
                <?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
            </p>
            <p>
                <label>
                    Geburtsdatum
                </label>
                <?= $charakter->getGeburtsdatum('d.m.Y') . ' (' . $charakter->getAlter() . ')' ?>
            </p>
            <p>
                <label>
                    Wohnort
                </label>
                <?= $charakter->getWohnort() ?>
            </p>
            <p>
                <label>
                    Sexuelle Orientierung
                </label>
                <?= $charakter->getSexualitaet() ?>
            </p>
        </fieldset>
        <fieldset>
            <legend>Profilbild <span class="indicator">+</span></legend>
            <div class="subContent">
                <form method="post" action="<?= $this->baseUrl() ?>/charakter/profilpic">
                    <input type="text" name="profilpic" placeholder="<?= $purifier->purify($charakter->getCharakterprofil()->getProfilpic()) ?>">
                    <input type="submit" value="Profilbild speichern">
                </form>
                <img src="<?= $purifier->purify($charakter->getCharakterprofil()->getProfilpic()) ?>" height="200px" width="200px">
            </div>
        </fieldset>
        <fieldset>
            <legend>Werte <span class="indicator">+</span></legend>
            <div class="subContent">
                <p>
                    <label>
                        Stärke
                    </label>
                    <span>
                        <?= $werte->getStaerke() ?>
                    </span>
                    <span>
                        <?= $werte->getCategory($werte->getStaerke()) ?>
                    </span>
                </p>
                <p>
                    <label>
                        Agilität
                    </label>
                    <span>
                        <?= $werte->getAgilitaet() ?>
                    </span>
                    <span>
                        <?= $werte->getCategory($werte->getAgilitaet()) ?>
                    </span>
                </p>
                <p>
                    <label>
                        Ausdauer
                    </label>
                    <span>
                        <?= $werte->getAusdauer() ?>
                    </span>
                    <span>
                        <?= $werte->getCategory($werte->getAusdauer()) ?>
                    </span>
                </p>
                <p>
                    <label>
                        Kontrolle
                    </label>
                    <span>
                        <?= $werte->getKontrolle() ?>
                    </span>
                    <span>
                        <?= $werte->getCategory($werte->getKontrolle()) ?>
                    </span>
                </p>
                <p>
                    <label>
                        Disziplin
                    </label>
                    <span>
                        <?= $werte->getDisziplin() ?>
                    </span>
                    <span>
                        <?= $werte->getCategory($werte->getDisziplin()) ?>
                    </span>
                </p>
                <p>
                    <label>
                        Übung
                    </label>
                    <span>
                        <?= $werte->getUebung() ?>
                    </span>
                </p>
            </div>
        </fieldset>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <fieldset>
            <legend>Charakterbild <span class="indicator">+</span></legend>
            <div class="subContent">
                <form method="post" action="<?= $this->baseUrl() ?>/charakter/charpic">
                    <input type="text" name="charpic"  placeholder="<?= $purifier->purify($charakter->getCharakterprofil()->getCharpic()) ?>">
                    <input type="submit" value="Charakterbild speichern">
                </form>
                <img src="<?= $purifier->purify($charakter->getCharakterprofil()->getCharpic()) ?>" height="400px" width="300px">
            </div>
        </fieldset>
    <fieldset>
        <legend>Statistik <span class="indicator">+</span></legend>
        <div class="subContent">
            
        </div>
    </fieldset>
    </div>
    <div class="clearBoth"></div>
</div>
