<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Charakterdaten
</h1>
<div class="container-fluid">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>

    <div class="row m-3">
        <div class="col-xl-4 col-lg-6 col-sm-12 g-4">
            <?php include __DIR__ . '/partials/charakterdaten.phtml'; ?>
            <?php include __DIR__ . '/partials/statistik.phtml'; ?>
        </div>
        <div class="col-xl-4 col-lg-6 col-sm-12 g-4">
            <?php include __DIR__ . '/partials/charakterwerte.phtml'; ?>
            <?php include __DIR__ . '/partials/traits.phtml'; ?>
            <?php include __DIR__ . '/partials/circuit.phtml'; ?>
        </div>
        <div class="col-xl-4 col-lg-6 col-sm-12 g-4">
            <?php include __DIR__ . '/partials/klasse.phtml'; ?>
            <?php include __DIR__ . '/partials/hooks.phtml'; ?>
            <?php if ($charakter->hasFerocity()): ?>
                <div class="col-lg-4 col-sm-12 g-4">
                    <?php include __DIR__ . '/partials/ferocity.phtml'; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>

</div>