<?php
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
/* @var $werte Application_Model_Charakterwerte */
$werte = $charakter->getCharakterwerte();
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Charakterdaten
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<br />
<div>
    <div class="contentLeft">
        <?php include __DIR__ . '/partials/charakterdaten.phtml'; ?>
        <?php include __DIR__ . '/partials/circuit.phtml'; ?>
        <?php include __DIR__ . '/partials/traits.phtml' ?>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <?php include __DIR__ . '/partials/statistik.phtml' ?>
        <?php include __DIR__ . '/partials/charakterwerte.phtml' ?>
        <?php include __DIR__ . '/partials/vermoegen.phtml' ?>
        <?php include __DIR__ . '/partials/klasse.phtml' ?>
    </div>
    <div class="clearBoth"></div>
</div>