<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');

$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/ckeditor.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));

/* @var $purifier HTMLpurifier */
$purifier = $this->purifier;
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
?>
<script src="<?= $this->baseurl ?>/js/ckeditor/ckeditor.js"></script>
<style type="text/css">
    .cke_textarea_inline {
        border: 1px solid #ccc;
        padding: 10px;
        min-height: 300px;
        background: #fff;
        color: #000;
    }
</style>
<h1>
    Profil
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<br /><div>
    <div class="contentLeft">
        <?php include __DIR__ . '/partials/profilbild.phtml' ?>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <?php include __DIR__ . '/partials/charakterbild.phtml' ?>
    </div>
    <div class="clearBoth"></div>
</div>
<div>
    <fieldset>
        <legend>Charaktergeschichte <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/story">
                <textarea class="data" id="story" name="story" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getCharaktergeschichte()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Private Charakterdaten <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/private">
                <textarea class="data" id="private" name="private" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getPrivatdaten()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Traithistorie <span class="indicator"></span></legend>
        <div class="subContent">
            <div>
                <?= $this->partial('charakter/partials/traitEntry.phtml', [
                        'headline' => 'Trait aus der Kindheit',
                        'character' => $charakter,
                        'historyKey' => Application_Model_Trait::STORY_TYPE_BIRTH,
                        'purifier' => $purifier,
                ]) ?>
            </div>
            <div>
                <?= $this->partial('charakter/partials/traitEntry.phtml', [
                        'headline' => 'Trait aus der Erziehung',
                        'character' => $charakter,
                        'historyKey' => Application_Model_Trait::STORY_TYPE_RAISED,
                        'purifier' => $purifier,
                ]) ?>
            </div>
            <div>
                <?= $this->partial('charakter/partials/traitEntry.phtml', [
                        'headline' => 'Trait durch ein Ereignis',
                        'character' => $charakter,
                        'historyKey' => Application_Model_Trait::STORY_TYPE_EVENT,
                        'purifier' => $purifier,
                ]) ?>
            </div>
            <div>
                <?= $this->partial('charakter/partials/traitEntry.phtml', [
                        'headline' => 'Erarbeiteter Trait',
                        'character' => $charakter,
                        'historyKey' => Application_Model_Trait::STORY_TYPE_GAINED,
                        'purifier' => $purifier,
                ]) ?>
            </div>
            <div>
                <?= $this->partial('charakter/partials/traitEntry.phtml', [
                        'headline' => 'Fokustrait',
                        'character' => $charakter,
                        'historyKey' => Application_Model_Trait::STORY_TYPE_FOCUS,
                        'purifier' => $purifier,
                ]) ?>
            </div>
        </div>
    </fieldset>
</div>