<?php

$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/charakter.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/charakter/editor.js'));
/* @var $purifier HTMLpurifier */
$purifier = $this->purifier;
/* @var $charakter Application_Model_Charakter */
$charakter = $this->charakter;
$childhoodTrait = $charakter->getTraitByStory(Application_Model_Trait::STORY_TYPE_BIRTH);
$raisedTrait = $charakter->getTraitByStory(Application_Model_Trait::STORY_TYPE_RAISED);
$eventTrait = $charakter->getTraitByStory(Application_Model_Trait::STORY_TYPE_EVENT);
$gainedTrait = $charakter->getTraitByStory(Application_Model_Trait::STORY_TYPE_GAINED);
$focusTrait = $charakter->getTraitByStory(Application_Model_Trait::STORY_TYPE_FOCUS);
?>
<h1>
    Profil
</h1>
<div class="submenu">
    <?php include __DIR__ . '/partials/submenu.phtml'; ?>
</div>
<br /><div>
    <div class="contentLeft">
        <?php include __DIR__ . '/partials/profilbild.phtml' ?>
    </div>
    <div class="clearRight"></div>
    <div class="contentRight">
        <?php include __DIR__ . '/partials/charakterbild.phtml' ?>
    </div>
    <div class="clearBoth"></div>
</div>
<div>
    <fieldset>
        <legend>Charaktergeschichte <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/story">
                <textarea class="data" id="story" name="story" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getCharaktergeschichte()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Private Charakterdaten <span class="indicator"></span></legend>
        <div class="subContent">
            <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/private">
                <textarea class="data" id="private" name="private" rows="30"><?= $purifier->purify($charakter->getCharakterprofil()->getPrivatdaten()) ?></textarea>
                <br />
                <input type="submit" class="save" value="Charaktergeschichte speichern">
            </form>
        </div>
    </fieldset>
</div>
<div>
    <fieldset>
        <legend>Traithistorie <span class="indicator"></span></legend>
        <div class="subContent">
            <div>
                <h4>Trait aus der Kindheit</h4>
                <div>
                    <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/traits">
                        <select name="traitId">
                            <option>Bitte wählen</option>
                            <?php
                            foreach($charakter->getTraits() as $trait):
                                if ($trait->getStoryType() !== 0 && $trait->getStoryType() !== Application_Model_Trait::STORY_TYPE_BIRTH) {
                                    continue;
                                }
                                $selected = '';
                                if ($trait->getStoryType() === Application_Model_Trait::STORY_TYPE_BIRTH) {
                                    $selected = 'selected=""';
                                }
                            ?>
                            <option <?= $selected ?> value="<?= $trait->getTraitId() ?>"><?= $trait->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <textarea class="data" id="private" name="story" rows="10"><?= $purifier->purify($childhoodTrait->getStory()) ?></textarea>
                        <input type="hidden" name="storyType" value="<?= Application_Model_Trait::STORY_TYPE_BIRTH ?>">
                        <input type="submit" class="save" value="Eintrag speichern">
                    </form>
                </div>
            </div>
            <div>
                <h4>Trait aus der Erziehung</h4>
                <div>
                    <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/traits">
                        <select name="traitId">
                            <option>Bitte wählen</option>
                            <?php
                            foreach($charakter->getTraits() as $trait):
                                if ($trait->getStoryType() !== 0 && $trait->getStoryType() !== Application_Model_Trait::STORY_TYPE_RAISED) {
                                    continue;
                                }
                                $selected = '';
                                if ($trait->getStoryType() === Application_Model_Trait::STORY_TYPE_RAISED) {
                                    $selected = 'selected=""';
                                }
                            ?>
                            <option <?= $selected ?> value="<?= $trait->getTraitId() ?>"><?= $trait->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <textarea class="data" id="private" name="story" rows="10"><?= $purifier->purify($raisedTrait->getStory()) ?></textarea>
                        <input type="hidden" name="storyType" value="<?= Application_Model_Trait::STORY_TYPE_RAISED ?>">
                        <input type="submit" class="save" value="Eintrag speichern">
                    </form>
                </div>
            </div>
            <div>
                <h4>Trait durch ein Ereignis</h4>
                <div>
                    <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/traits">
                        <select name="traitId">
                            <option>Bitte wählen</option>
                            <?php
                            foreach($charakter->getTraits() as $trait):
                                if ($trait->getStoryType() !== 0 && $trait->getStoryType() !== Application_Model_Trait::STORY_TYPE_EVENT) {
                                    continue;
                                }
                                $selected = '';
                                if ($trait->getStoryType() === Application_Model_Trait::STORY_TYPE_EVENT) {
                                    $selected = 'selected=""';
                                }
                            ?>
                            <option <?= $selected ?> value="<?= $trait->getTraitId() ?>"><?= $trait->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <textarea class="data" id="private" name="story" rows="10"><?= $purifier->purify($eventTrait->getStory()) ?></textarea>
                        <input type="hidden" name="storyType" value="<?= Application_Model_Trait::STORY_TYPE_EVENT ?>">
                        <input type="submit" class="save" value="Eintrag speichern">
                    </form>
                </div>
            </div>
            <div>
                <h4>Erarbeiteter Trait</h4>
                <div>
                    <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/traits">
                        <select name="traitId">
                            <option>Bitte wählen</option>
                            <?php
                            foreach($charakter->getTraits() as $trait):
                                if ($trait->getStoryType() !== 0 && $trait->getStoryType() !== Application_Model_Trait::STORY_TYPE_GAINED) {
                                    continue;
                                }
                                $selected = '';
                                if ($trait->getStoryType() === Application_Model_Trait::STORY_TYPE_GAINED) {
                                    $selected = 'selected=""';
                                }
                            ?>
                            <option <?= $selected ?> value="<?= $trait->getTraitId() ?>"><?= $trait->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <textarea class="data" id="private" name="story" rows="10"><?= $purifier->purify($gainedTrait->getStory()) ?></textarea>
                        <input type="hidden" name="storyType" value="<?= Application_Model_Trait::STORY_TYPE_GAINED ?>">
                        <input type="submit" class="save" value="Eintrag speichern">
                    </form>
                </div>
            </div>
            <div>
                <h4>Fokustrait</h4>
                <div>
                    <form class="profil" method="post" action="<?= $this->baseUrl() ?>/charakter/traits">
                        <select name="traitId">
                            <option>Bitte wählen</option>
                            <?php
                            foreach($charakter->getTraits() as $trait):
                                if ($trait->getStoryType() !== 0 && $trait->getStoryType() !== Application_Model_Trait::STORY_TYPE_FOCUS) {
                                    continue;
                                }
                                $selected = '';
                                if ($trait->getStoryType() === Application_Model_Trait::STORY_TYPE_FOCUS) {
                                    $selected = 'selected=""';
                                }
                            ?>
                            <option <?= $selected ?> value="<?= $trait->getTraitId() ?>"><?= $trait->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                        <textarea class="data" id="private" name="story" rows="10"><?= $purifier->purify($focusTrait->getStory()) ?></textarea>
                        <input type="hidden" name="storyType" value="<?= Application_Model_Trait::STORY_TYPE_FOCUS?>">
                        <input type="submit" class="save" value="Eintrag speichern">
                    </form>
                </div>
            </div>
        </div>
    </fieldset>
</div>