<?php if($this->eigeneGruppe === true): ?>
<div>
    <fieldset>
        <legend>
            Gruppenleiter
        </legend>
        <div>
            <fieldset style="display: inline-block; width: 45%; float: left">
                <legend>Charakter einladen</legend>
                <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/add">
                    <select name="charaktere[]" size="3" multiple="">
                        <?php foreach($this->charaktere as $charakter): 
                            if(in_array($charakter->getCharakterid(), $mitgliedArray)){
                                continue;
                            }
                        ?>
                        <option value="<?= $charakter->getCharakterId() ?>"><?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="In Gruppe einladen">
                </form>
            </fieldset>
            <fieldset style="display: inline-block; width: 45%; float: right">
                <legend>Charakter kicken</legend>
                <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/remove">
                    <select name="charaktere[]" size="3" multiple="">
                        <?php foreach($gruppe->getMitglieder() as $charakter): ?>
                        <option value="<?= $charakter->getCharakterId() ?>"><?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="Aus Gruppe kicken">
                </form>
            </fieldset>
        </div>
    </fieldset>
</div>
<?php endif; ?>