<?php if($this->eigeneGruppe === true): ?>
<div>
    <fieldset>
        <legend>
            Gruppenleiter
        </legend>
        <div>
            <fieldset style="display: inline-block; width: 45%; float: left">
                <legend>Charakter einladen</legend>
                <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/add">
                    <select name="charaktere[]" size="3" multiple="">
                        <?php foreach($this->charaktere as $charakter): 
                            if(in_array($charakter->getCharakterid(), $mitgliedArray)){
                                continue;
                            }
                        ?>
                        <option value="<?= $charakter->getCharakterId() ?>"><?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="In Gruppe einladen">
                </form>
            </fieldset>
            <fieldset style="display: inline-block; width: 45%; float: right">
                <legend>Charakter kicken</legend>
                <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/remove">
                    <select name="charaktere[]" size="3" multiple="">
                        <?php foreach($gruppe->getMitglieder() as $charakter): ?>
                        <option value="<?= $charakter->getCharakterId() ?>"><?= $purifier->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?></option>
                        <?php endforeach; ?>
                    </select>
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="Aus Gruppe kicken">
                </form>
            </fieldset>
        </div>
        <fieldset>
            <legend>Neuen Plot erstellen <span class="indicator"></span></legend>
            <div class="subContent">
                <form method="post" action="<?= $this->baseUrl() ?>/Gruppen/story/create">
                    <label for="plotname">Plotname</label>
                    <input type="text" name="plotname">
                    <p class="genres">
                        Genres: 
                        <input type="checkbox" name="genre[]" name="Horror" value="Horror"> <label for="Horror">Horror</label>
                        <input type="checkbox" name="genre[]" name="Mystery" value="Mystery"> <label for="Mystery">Mystery</label>
                        <input type="checkbox" name="genre[]" name="Action" value="Action"> <label for="Action">Action</label>
                        <input type="checkbox" name="genre[]" name="Comedy" value="Comedy"> <label for="Comedy">Comedy</label>
                        <input type="checkbox" name="genre[]" name="Romance" value="Romance"> <label for="Romance">Romance</label>
                    </p>
                    <textarea name="beschreibung"></textarea>
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="Storyline erstellen">
                </form>
            </div>
        </fieldset>
    </fieldset>
</div>
<?php endif; ?>