<div class="row">
<?php if($this->exposed !== false): ?>
    <div class="col-6">
        <h4 class="fs-4">
            Charakter
        </h4>
        <div>
            <div>
                <form style="display: inline" method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/exit">
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input class="btn btn-danger" type="submit" value="Gruppe verlassen">
                </form>
            </div>
        </div>
        <p>
            Gruppenmitglied seit:
        </p>
    </div>
<?php endif; ?>
    <div class="col-6">
        <h4 class="fs-4">
            Gruppenmitglieder
        </h4>
        <ul>
            <?php foreach($gruppe->getMitglieder() as $charakter) : ?>
                <li>
                    <?= $this->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>