<div>
<?php if($this->exposed !== false): ?>
    <fieldset style="display: inline-block; width: 45%; float: left">
        <legend>
            Charakter
        </legend>
        <div>
            <div>
                <form style="display: inline" method="post" action="<?= $this->baseUrl() ?>/Gruppen/index/exit">
                    <input type="hidden" name="gruppenId" value="<?= $gruppe->getId() ?>">
                    <input type="submit" value="Gruppe verlassen">
                </form>
            </div>
        </div>
        <p>
            Gruppenmitglied seit: 
        </p>
    </fieldset>
    <?php endif; ?>
    <fieldset style="display: inline-block; width: 45%; float: right; max-height: 150px; overflow: auto">
        <legend>Gruppenmitglieder</legend>
        <ul>
            <?php foreach($gruppe->getMitglieder() as $charakter) : ?>
                <li>
                    <?= $this->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </fieldset>
    <div style="clear: both"></div>
</div>