<?php
/* @var $klasse Administration_Model_Klasse */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<div class="container">
    <div class="row">
        <div class="col">
            <h1 class="fs-1">
                Klassen
            </h1>
        </div>
    </div>
    <div class="row">
        <?php
        foreach ($this->klassen as $klasse){
        ?>
            <div class="col-4 p-2">
                <div class="card" style="height: 10rem; overflow: auto">
                    <a href="<?= $this->baseUrl() ?>/Administration/klasse/show/id/<?= $klasse->getId() ?>">
                        <div class="card-body">
                            <div class="card-title fs-3">
                                <?= $purifier->purify($klasse->getBezeichnung()) ?>
                            </div>
                            <div class="text-muted">
                                <?= $purifier->purify(substr($klasse->getBeschreibung(), 0, 100)) ?>
                                <?= (strlen($klasse->getBeschreibung()) > 100) ? '...' : '' ?>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        <?php
        }
        ?>
    </div>
</div>