<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
?>
<h1>Klasse erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/klasse/create" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" />
            <label for="klassengruppe">
                Klassengruppe:
            </label>
            <select name="klassengruppe">
                <?php foreach ($this->klassengruppen as $gruppe) { ?>
                <option value="<?= $gruppe->getId() ?>">
                    <?= $gruppe->getBezeichnung() ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="familienname">Familienname</label>
            <input type="text" size="30" name="familienname" />
        </p>
        <p>
            <label for="traits">
                Traits:
            </label>
            <select name="traits[]" multiple="true" size="8">
                <?php foreach ($this->traits as $trait) { ?>
                <option value="<?= $trait->getTraitId() ?>">
                    <?= $trait->getName() ?>
                </option>
                <?php } ?>
            </select>
        </p>
        <label for="beschreibung">
            Beschreibung
        </label>
        <textarea name="beschreibung" cols="80" rows="10"></textarea>
    </fieldset>
    <div align="center">
        <input type="submit" name="Abschicken" id="Abschicken" value="Klasse erstellen" />
    </div>
</form>