<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
/* @var $klasse Administration_Model_Klasse */
$klasse = $this->klasse;
$purifier = $this->purifier
?>
<h1>Klasse anpassen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/klasse/edit" method="post">
    <fieldset>
        <p>
            <label for="name">Name</label>
            <input type="text" size="30" name="name" value="<?= $purifier->purify($klasse->getBezeichnung()) ?>" />
            <label for="kosten">Kosten</label>
            <input type="number" name="kosten" value="<?= $klasse->getKosten() ?>" />
            <label for="klassengruppe">
                Klassengruppe:
            </label>
            <select name="klassengruppe">
                <?php 
                foreach ($this->klassengruppen as $gruppe) { 
                    $selected = ($gruppe->getId() === $klasse->getGruppe()) ? 'selected="true"' : '';
                ?>
                <option <?= $selected ?> value="<?= $gruppe->getId() ?>">
                    <?= $purifier->purify($gruppe->getBezeichnung()) ?>
                </option>
                <?php } ?>
            </select>
            <br />
            <label for="familienname">Familienname</label>
            <input type="text" size="30" name="familienname" value="<?= $purifier->purify($klasse->getFamilienname()) ?>" />
        </p>
        <p>
            <label for="trait">
                Nicht kombinierbar mit den Traits:
            </label>
            <select name="trait[]" multiple="true" size="8">
                <?php foreach ($this->traits as $trait) { ?>
                    <option value="<?= $trait->getTraitId() ?>">
                        <?= $purifier->purify($trait->getName()) ?>
                    </option>
                <?php } ?>
            </select>
        </p>
        <label for="beschreibung">
            Beschreibung
        </label>
        <textarea name="beschreibung" cols="80" rows="10">
            <?= $purifier->purify($klasse->getBeschreibung()) ?>
        </textarea>
    </fieldset>
    <div align="center">
        <input type="hidden" name="klassenId" value="<?= $klasse->getId() ?>">
        <input type="submit" name="Abschicken" id="Abschicken" value="Klasse ändern" />
    </div>
</form>