<?php
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/Administration/editor.js'));
/* @var $klasse Administration_Model_Klasse */
$klasse = $this->klasse;
$purifier = $this->purifier
?>
<h1 class="fs-1">Klasse anpassen</h1>
<form class="container" action="<?= $this->baseUrl() ?>/Administration/klasse/edit" method="post">
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="name">Name</label>
            <input class="form-control" id="name" type="text" size="30" name="name" value="<?= $purifier->purify($klasse->getBezeichnung()) ?>" />
        </div>
        <div class="col-4">
            <label class="form-label" for="kosten">Kosten</label>
            <input class="form-control" id="kosten" type="number" name="kosten" value="<?= $klasse->getKosten() ?>" />
        </div>
        <div class="col-4">
            <label class="form-label" for="familienname">Familienname</label>
            <input class="form-control" id="familienname" type="text" size="30" name="familienname" value="<?= $purifier->purify($klasse->getFamilienname()) ?>" />
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="klassengruppe">
                Klassengruppe:
            </label>
            <select class="form-select" id="klassengruppe" name="klassengruppe">
                <?php
                foreach ($this->klassengruppen as $gruppe) {
                    $selected = ($gruppe->getId() === $klasse->getGruppe()) ? 'selected="true"' : '';
                ?>
                    <option <?= $selected ?> value="<?= $gruppe->getId() ?>">
                        <?= $purifier->purify($gruppe->getBezeichnung()) ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-4">
            <label class="form-label" for="traits">
                Traits:
            </label>
            <select class="form-select" id="traits" name="traits[]" multiple="true" size="8">
                <?php
                foreach ($this->traits as $trait) {
                ?>
                    <option value="<?= $trait->getTraitId() ?>">
                        <?= $purifier->purify($trait->getName()) ?>
                    </option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="row m-3">
        <div class="col-12">
            <textarea class="form-control" name="beschreibung" cols="80" rows="10"><?= $purifier->purify($klasse->getBeschreibung()) ?></textarea>
        </div>
    </div>

    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="hidden" name="klassenId" value="<?= $klasse->getId() ?>">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Klasse ändern" />
        </div>
    </div>
</form>