<fieldset>
    <form method="POST" action="<?= $this->baseUrl() ?>/user/charakter">
        <p>
            <label>
                Passwort eingeben
            </label>
            <input type="password" name="password" />
        </p>
        <p>
            <label>
                Passwort bestätigen
            </label>
            <input type="password" name="passwordConfirm" />
        </p>
        <input type="submit" value="Charakter löschen" name="deleteCharakter" />
    </form>
</fieldset>