<fieldset>
    <form action="<?= $this->baseUrl() ?>/user/password" method="POST">
        <p>
            <label>
                Neues Passwort
            </label>
            <input type="password" name="passwordNew" />
        </p>
        <p>
            <label>
                Neues Passwort bestätigen
            </label>
            <input type="password" name="passwordNewConfirm" />
        </p>
        <p>
            <label>
                Altes Passwort
            </label>
            <input type="password" name="passwordOld" />
        </p>
        <input type="submit" name="newPw" value="speichern" />
    </form>
</fieldset>