<?php
/* @var $circuit Application_Model_Circuit */
$this->headScript()->prependFile($this->baseUrl() . '/js/tinymce/tinymce.min.js');
$this->headScript()->prependFile($this->baseUrl() . '/js/Administration/editor.js');
?>
<h1>Magic Circuit erstellen</h1>
<form action="<?= $this->baseUrl() ?>/Administration/circuits/create" method="post">
    <div class="row justify-content-around">
        <div class="col-8">
            <label class="form-label" for="kategorie">Kategorie</label>
            <input type="text" size="30" id="kategorie" name="kategorie" class="form-control" />
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-8">
            <label class="form-label" for="kosten">Kosten</label>
            <input type="number" id="kosten" name="kosten" class="form-control" />
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-8">
            <label class="form-label" for="menge">Odo-Menge</label>
            <input type="number" id="menge" name="menge" class="form-control">
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-8">
            <label class="form-label" for="beschreibung">
                Beschreibung
            </label>
            <textarea id="beschreibung" name="beschreibung" cols="80" rows="10" class="form-control"></textarea>
        </div>
    </div>
    <div class="row justify-content-around">
        <div class="col-3 p-3">
            <input type="submit" class="btn btn-primary btn-block" name="Abschicken" id="Abschicken" value="Circuit erstellen" />
        </div>
    </div>
</form>