<?php
/* @var $werte Application_Model_CharakterWerte */
$categoryStr = $werte->getCategory('str');
$categoryAgi = $werte->getCategory('agi');
$categoryAus = $werte->getCategory('aus');
$categoryKon = $werte->getCategory('kon');
$categoryDis = $werte->getCategory('dis');
?>
<fieldset>
    <legend>Werte</legend>
    <div>
        <p>
            <label>
                Stärke
            </label>
            <span title="<?= $werte->getStaerke() ?>">
                <?= floor($werte->getStaerke()) ?>
            </span>
                <span class="<?= $categoryStr->getUebermensch() ? 'uber' : '' ?>">
                    <?= $categoryStr->getCategory() ?>
                </span>
        </p>
        <p>
            <label>
                Agilität
            </label>
            <span title="<?= $werte->getAgilitaet() ?>">
                <?= floor($werte->getAgilitaet()) ?>
            </span>
            <span class="<?= $categoryAgi->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryAgi->getCategory() ?>
            </span>
        </p>
        <p>
            <label>
                Ausdauer
            </label>
            <span title="<?= $werte->getAusdauer() ?>">
                <?= floor($werte->getAusdauer()) ?>
            </span>
            <span class="<?= $categoryAus->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryAus->getCategory() . ' (' . $werte->getEnergie() . ' HP)' ?>
            </span>
        </p>
        <p>
            <label>
                Kontrolle
            </label>
            <span title="<?= $werte->getKontrolle() ?>">
                <?= floor($werte->getKontrolle()) ?>
            </span>
            <span class="<?= $categoryKon->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryKon->getCategory() ?>
            </span>
        </p>
        <p>
            <label>
                Disziplin
            </label>
            <span title="<?= $werte->getDisziplin() ?>">
                <?= floor($werte->getDisziplin()) ?>
            </span>
            <span class="<?= $categoryDis->getUebermensch() ? 'uber' : '' ?>">
                <?= $categoryDis->getCategory() ?>
            </span>
        </p>
        <p>
            <label>
                Übung
            </label>
            <span title="<?= $werte->getUebung() ?>">
                <?= floor($werte->getUebung()) ?>
            </span>
        </p>
        <p>
            <label>
                FP
            </label>
            <span>
                <?= floor($werte->getFp()) ?>
            </span>
        </p>
    </div>
</fieldset>