<?php
/* @var $werte Application_Model_CharakterWerte */
$categoryStr = $werte->getCategory('str');
$categoryAgi = $werte->getCategory('agi');
$categoryAus = $werte->getCategory('aus');
$categoryKon = $werte->getCategory('kon');
$categoryDis = $werte->getCategory('dis');
$categoryPra = $werte->getCategory('pra');
?>
<fieldset>
    <legend>Werte</legend>
    <div>
        <p>
            <label>
                Stärke
            </label>
            <span title="<?= $werte->getStaerke() ?>">
                <?= floor($werte->getStaerke()) ?>
            </span>
            <span>
                <?= $categoryStr->getCategory() ?> (<?= $categoryStr->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Agilität
            </label>
            <span title="<?= $werte->getAgilitaet() ?>">
                <?= floor($werte->getAgilitaet()) ?>
            </span>
            <span>
                <?= $categoryAgi->getCategory() ?> (<?= $categoryAgi->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Ausdauer
            </label>
            <span title="<?= $werte->getAusdauer() ?>">
                <?= floor($werte->getAusdauer()) ?>
            </span>
            <span>
                <?= $categoryAus->getCategory() ?> (<?= $categoryAus->getNumericValue() ?>) = <?= $werte->getEnergie() ?> HP
            </span>
        </p>
        <p>
            <label>
                Kontrolle
            </label>
            <span title="<?= $werte->getKontrolle() ?>">
                <?= floor($werte->getKontrolle()) ?>
            </span>
            <span>
                <?= $categoryKon->getCategory() ?> (<?= $categoryKon->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Disziplin
            </label>
            <span title="<?= $werte->getDisziplin() ?>">
                <?= floor($werte->getDisziplin()) ?>
            </span>
            <span>
                <?= $categoryDis->getCategory() ?> (<?= $categoryDis->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                Übung
            </label>
            <span title="<?= $werte->getUebung() ?>">
                <?= floor($werte->getUebung()) ?>
            </span>
            <span>
                <?= $categoryPra->getCategory() ?> (<?= $categoryPra->getNumericValue() ?>)
            </span>
        </p>
        <p>
            <label>
                FP
            </label>
            <span>
                <?= floor($werte->getFp()) ?>
            </span>
        </p>
    </div>
</fieldset>