<?php
/* @var $charakter Application_Model_Charakter */
?>
<div class="card bg-info m-2">
    <h5 class="card-title">Charakterdaten</h5>
    <div class="card-body">
        <div class="row">
            <div class="col-4">
                Name
            </div>
            <div class="col-8">
                <?= $this->purify($charakter->getVorname() . ' ' . $charakter->getNachname()) ?>
            </div>
        </div>
        <?php if($charakter->getOrigin() !== ''): ?>
            <div class="row">
                <div class="col-4">
                    Origin
                </div>
                <div class="col-8">
                    <?= $this->purify($charakter->getOrigin()) ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-4">
                Geburtsdatum
            </div>
            <div class="col-8">
                <?= $charakter->getGeburtsdatum('d.m.Y') . ' (' . $charakter->getAlter() . ')' ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Geschlecht
            </div>
            <div class="col-8">
                <?= $this->purify($charakter->getGeschlecht()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Wohnort
            </div>
            <div class="col-8">
                <?= $this->purify($charakter->getWohnort()) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Vermögen
            </div>
            <div class="col-8">
                <?= $charakter->getVermoegen()->getMenge() . '(' . $charakter->getVermoegen()->getKategorie() . ')' ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Sexuelle Orientierung
            </div>
            <div class="col-8">
                <?= $charakter->getSexualitaet() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Odo-Kategorie
            </div>
            <div class="col-8">
                <?= $charakter->getOdo()->getKategorie() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Odo
            </div>
            <div class="col-8">
                <?= $charakter->getOdo()->getActualAmount() ?>
            </div>
        </div>
        <div class="row">
            <div class="col-4">
                Naturelement
            </div>
            <div class="col-8">
                <?= $charakter->getNaturElement()->getBezeichnung(); ?>
            </div>
        </div>
        <?php if($charakter->getMagiccircuit()->getKategorie() !== 'F'): ?>
            <div class="row">
                <div class="col-4">
                    Magic-Circuit
                </div>
                <div class="col-8">
                    <?= $charakter->getMagiccircuit()->getKategorie() ?>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    Mana
                </div>
                <div class="col-8">
                    <?= $charakter->getMagiccircuit()->getMana($charakter) ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-4">
                Glück
            </div>
            <div class="col-8">
                <?= $charakter->getLuck()->getKategorie() ?>
            </div>
        </div>
        <?php if($charakter->hasKurotama()): ?>
            <div class="row">
                <div class="col-4">
                    Kurotama
                </div>
                <div class="col-8">
                    <?= $charakter->getKurotama() ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>