<?php
/* @var $charakter Application_Model_Charakter */
?>
<div class="card bg-info m-2">
    <h5 class="toggleLegend">Hooks <span class="indicator"></span></h5>
    <div class="card-body subContent">
        <?php foreach ($charakter->getAchievements() as $achievement): ?>
            <h4><?= $this->purify($achievement->getTitle()) ?></h4>
            <p>
                <?= $this->purify($achievement->getDescription()) ?>
            </p>
        <?php endforeach; ?>
    </div>
</div>