
<div class="card bg-info m-2">
<!--    <div class="subContent">-->
    <div class="card-body">
        <h4>Klasse - <?= $this->purify($charakter->getKlassengruppe()->getBezeichnung()) ?></h4>
        <p>
            <?= $this->purify($charakter->getKlassengruppe()->getBeschreibung()) ?>
        </p>
        <h4>Unterklasse - <?= $this->purify($charakter->getKlasse()->getBezeichnung()) ?></h4>
        <p>
            <?= $this->purify($charakter->getKlasse()->getBeschreibung()) ?>
        </p>
    </div>
</div>