<fieldset>
    <legend>Nachteile</legend>
<?php foreach($charakter->getNachteile() as $nachteil): ?>
    <div>
        <legend>
            <?= $purifier->purify($nachteil->getBezeichnung()) ?> <span class="indicator"></span>
        </legend>
        <div class="subContent">
            <?= $purifier->purify($nachteil->getBeschreibung()) ?>
        </div>
    </div>
<?php endforeach; ?>
</fieldset>