
<div class="card bg-info m-2">
    <h5 class="toggleLegend card-title">Statistik</h5>
    <div class="card-body">
        <p>
            <label>Überlebt seit</label>
            <span>
                <?= $charakter->getCreatedate('d.m.Y') ?>
            </span>
        </p>
        <?php if ($charakter->getUndead()): ?>
        <p>
            <label>Untot seit</label>
            <span>
                <?= $charakter->getUndeadDate('d.m.Y') ?>
            </span>
        </p>
        <?php endif; ?>
        <p>
            <label>Getötet</label>
            <span>
                <?= $charakter->getKillcount() ?>
            </span>
        </p>
    </div>
</div>