<fieldset>
    <legend>Statistik</legend>
    <div>
        <p>
            <label>Überlebt seit</label>
            <span>
                <?= $charakter->getCreatedate('d.m.Y') ?>
            </span>
        </p>
        <?php if ($charakter->getUndead()): ?>
        <p>
            <label>Untot seit</label>
            <span>
                <?= $charakter->getUndeadDate('d.m.Y') ?>
            </span>
        </p>
        <?php endif; ?>
        <p>
            <label>Getötete NPCs</label>
            <span>
                <?= $charakter->getKillcount() ?>
            </span>
        </p>
    </div>
</fieldset>