<div class="row m-3 ">
    <div class="col-lg-2 col-sm-12">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/charakter">
            Charakterdaten
        </a>
    </div>
    <div class="col-lg-2 col-sm-12">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/charakter/profil">
            Charakterprofil
        </a>
    </div>
    <div class="col-lg-3 col-sm-12">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/charakter/abilities">
            Magien und Fähigkeiten
        </a>
    </div>
    <div class="col-lg-2 col-sm-12">
        <a class="btn btn-info" href="<?= $this->baseUrl() ?>/charakter/inventar">
            Ausrüstung
        </a>
    </div>
    <?php if($this->charakter->getCharakterwerte()->getStartpunkte() > 0): ?>
        <div class="col-lg-2 col-sm-12">
            <a class="btn btn-primary" href="<?= $this->baseUrl() ?>/charakter/bonus">
                Bonustage verteilen
            </a>
        </div>
    <?php endif; ?>
</div>