
<div class="card bg-info m-2">
    <h5 class="card-title">Traits</h5>
<?php foreach($charakter->getTraits() as $trait): ?>
    <div class="card-body">
        <div class="toggleLegend">
            <?= $this->purify($trait->getName()) ?> <span class="indicator"></span>
        </div>
        <div class="subContent">
            <?= $this->purify($trait->getBeschreibung()) ?>
        </div>
    </div>
<?php endforeach; ?>
</div>