<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/magieschulen.js'));
/* @var $magieschule Shop_Model_Schule */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
?>
<h1>
    Magieschulen
</h1>
<?php
if(count($this->magieschulen) < 1):
?>
<p>
    Für deinen Charakter gibt es zur Zeit keine Magieschulen.
</p>
<?php
endif;
?>
<img src="http://i.imgur.com/eJTNdlH.jpg">
<?php
$lockedSchools = array();
foreach ($this->magieschulen as $magieschule):
    if($magieschule->getLearned() === false){
        $lockedSchools[] = $magieschule;
        continue;
    }
?>
<fieldset style="margin-bottom: 1.5em">
    <legend>
        <?= $purifier->purify($magieschule->getBezeichnung()) ?> <span class="indicator">+</span>
    </legend>
    <div class="subContent">
        <p>
            <?= $purifier->purify($magieschule->getBeschreibung()) ?>
        </p>
    </div>
    <fieldset>
        <legend class="school" data-id="<?= $magieschule->getId() ?>">Magien dieser Schule anzeigen</legend>
        <div class="subContent"></div>
    </fieldset>
</fieldset>
<?php
endforeach;
foreach ($lockedSchools as $magieschule):
?>
<fieldset style="margin-bottom: 1.5em">
    <legend>
        <?= $purifier->purify($magieschule->getBezeichnung()) ?> <span class="indicator">+</span>
    </legend>
    <div class="subContent">
        <p>
            <?= $purifier->purify($magieschule->getBeschreibung()) ?>
        </p>
    </div>
    <form method="POST" action="<?= $this->baseUrl() ?>/Shop/magie/unlockschool">
        <input type="hidden" value="<?= $magieschule->getId() ?>" name="magieschuleId">
        <input type="submit" value="Magieschule freischalten - <?= $magieschule->getKosten() ?>FP">
    </form>
</fieldset>
<?php
endforeach;
?>