<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/magieschulen.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/magien.js'));
$this->headLink()->prependStylesheet($this->autoVersion($this->baseUrl() . '/styles/magieschulen.css'));
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
/* @var $magieschule \Shop\Models\Schule */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$clockTower = '';
$atlas = '';
$wanderingSea = '';
switch ($this->organization) {
    case Application_Model_MagiOrganization::CLOCK_TOWER:
        $clockTower = 'selected=""';
        break;
    case Application_Model_MagiOrganization::ATLAS:
        $atlas = 'selected=""';
        break;
    case Application_Model_MagiOrganization::WANDERING_SEA:
        $wanderingSea = 'selected=""';
        break;
}
/** @var \Shop\Models\Schule[] $organizationSchools */
$organizationSchools = $this->organizationSchools;
/** @var \Shop\Models\Schule[] $schools */
$schools = $this->schools;
?>
<h1 class="fs-1">
    Magieschulen
</h1>
<img src="http://i.imgur.com/eJTNdlH.jpg"/>
<?php if($this->organization === 0 && $this->layoutData->getCharakter()->getKlassengruppe()->getId() === 1): ?>
<div>
    <h2>Organisation</h2>
    <form method="post" action="<?= $this->baseUrl() ?>/Shop/magie/organization">
        <p>
            <label for="organization">Tritt einer Organisation bei: </label>
        </p>
        <select id="organization" name="organization">
            <option>Bitte wählen</option>
            <option <?= $clockTower ?> value="<?= Application_Model_MagiOrganization::CLOCK_TOWER ?>">Clock Tower</option>
            <option <?= $atlas ?> value="<?= Application_Model_MagiOrganization::ATLAS ?>">Atlas</option>
            <option <?= $wanderingSea ?> value="<?= Application_Model_MagiOrganization::WANDERING_SEA ?>">Wandering Sea</option>
        </select>
        <input type="submit" value="Speichern" />
    </form>
</div>
<?php
endif;
if (count($organizationSchools) > 0):
?>
<div>
    <h2>Magieschulen deiner Organisation</h2>
    <?php
    $lockedSchools = [];
    foreach ($organizationSchools as $organizationSchool) {
        if ($organizationSchool->getLearned() === false) {
            $lockedSchools[] = $organizationSchool;
            continue;
        }
    ?>
        <fieldset style="margin-bottom: 1.5em">
            <legend>
                <?= $purifier->purify($organizationSchool->getBezeichnung()) ?> <span class="indicator">+</span>
            </legend>
            <div class="subContent">
                <p>
                    <?= $purifier->purify($organizationSchool->getBeschreibung()) ?>
                </p>
            </div>
            <fieldset>
                <legend class="school" data-id="<?= $organizationSchool->getId() ?>">Magien dieser Schule anzeigen</legend>
                <div class="subContent"></div>
            </fieldset>
        </fieldset>
    <?php
    }
    foreach ($lockedSchools as $magieschule):
    ?>
    <fieldset style="margin-bottom: 1.5em">
        <legend>
            <?= $purifier->purify($magieschule->getBezeichnung()) ?> <span class="indicator">+</span>
        </legend>
        <div class="subContent">
            <p>
                <?= $purifier->purify($magieschule->getBeschreibung()) ?>
            </p>
        </div>
        <form method="POST" action="<?= $this->baseUrl() ?>/Shop/magie/unlockschool">
            <input type="hidden" value="<?= $magieschule->getId() ?>" name="magieschuleId">
            <input type="submit" class="unlockSchool btn btn-primary"
                   value="Magieschule freischalten - <?= $magieschule->getKosten() ?>FP">
        </form>
    </fieldset>
    <?php
endforeach;
?>
</div>
<?php
endif;
if (count($schools) > 0):
?>
<div>
    <h2>Allgemeine Magieschulen</h2>
    <?php
    foreach ($schools as $school) {
        ?>
        <fieldset style="margin-bottom: 1.5em">
            <legend>
                <?= $purifier->purify($school->getBezeichnung()) ?> <span class="indicator">+</span>
            </legend>
            <div class="subContent">
                <p>
                    <?= $purifier->purify($school->getBeschreibung()) ?>
                </p>
            </div>
            <fieldset>
                <legend class="school" data-id="<?= $school->getId() ?>">Magien dieser Schule anzeigen</legend>
                <div class="subContent"></div>
            </fieldset>
        </fieldset>
    <?php
    }
    ?>
</div>
<?php
endif;