<?php
$this->headScript()->setScript("var baseUrl ='{$this->baseUrl()}';", 'text/javascript');
$this->headLink()->prependStylesheet($this->baseUrl() . '/js/tooltipster/css/tooltipster.css');
$this->headScript()->prependFile($this->baseUrl() . '/js/tooltipster/js/jquery.tooltipster.min.js');
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/magieschulen.js'));
$this->headScript()->prependFile($this->autoVersion($this->baseUrl() . '/js/custom/shop/magien.js'));
$this->headLink()->prependStylesheet($this->autoVersion($this->baseUrl() . '/styles/magieschulen.css'));
$this->headScript()->prependFile($this->baseUrl() . '/js/sweetalert/sweetalert2.js');
/* @var $magieschule Shop_Model_Schule */
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$clockTower = '';
$atlas = '';
$wanderingSea = '';
switch ($this->organization) {
    case Application_Model_MagiOrganization::CLOCK_TOWER:
        $clockTower = 'selected=""';
        break;
    case Application_Model_MagiOrganization::ATLAS:
        $atlas = 'selected=""';
        break;
    case Application_Model_MagiOrganization::WANDERING_SEA:
        $wanderingSea = 'selected=""';
        break;
}
?>
<h1>
    Magieschulen
</h1>
<?php if($this->organization === 0): ?>
<div>

    <h2>Organisation</h2>
    <form method="post" action="<?= $this->baseUrl() ?>/Shop/magie/organization">
        <p>
            <label for="organization">Tritt einer Organisation bei: </label>
        </p>
        <select id="organization" name="organization">
            <option>Bitte wählen</option>
            <option <?= $clockTower ?> value="<?= Application_Model_MagiOrganization::CLOCK_TOWER ?>">Clock Tower</option>
            <option <?= $atlas ?> value="<?= Application_Model_MagiOrganization::ATLAS ?>">Atlas</option>
            <option <?= $wanderingSea ?> value="<?= Application_Model_MagiOrganization::WANDERING_SEA ?>">Wandering Sea</option>
        </select>
        <input type="submit" value="Speichern" />
    </form>
</div>
<?php endif; ?>
<?php
if (count($this->magieschulen) < 1):
    ?>
    <p>
        Für deinen Charakter gibt es zur Zeit keine Magieschulen.
    </p>
<?php
endif;
?>
    <img src="http://i.imgur.com/eJTNdlH.jpg">
<?php
$lockedSchools = [];
foreach ($this->magieschulen as $magieschule):
    if ($magieschule->getLearned() === false) {
        $lockedSchools[] = $magieschule;
        continue;
    }
    ?>
    <fieldset style="margin-bottom: 1.5em">
        <legend>
            <?= $purifier->purify($magieschule->getBezeichnung()) ?> <span class="indicator">+</span>
        </legend>
        <div class="subContent">
            <p>
                <?= $purifier->purify($magieschule->getBeschreibung()) ?>
            </p>
        </div>
        <fieldset>
            <legend class="school" data-id="<?= $magieschule->getId() ?>">Magien dieser Schule anzeigen</legend>
            <div class="subContent"></div>
        </fieldset>
    </fieldset>
<?php
endforeach;
foreach ($lockedSchools as $magieschule):
    ?>
    <fieldset style="margin-bottom: 1.5em">
        <legend>
            <?= $purifier->purify($magieschule->getBezeichnung()) ?> <span class="indicator">+</span>
        </legend>
        <div class="subContent">
            <p>
                <?= $purifier->purify($magieschule->getBeschreibung()) ?>
            </p>
        </div>
        <form method="POST" action="<?= $this->baseUrl() ?>/Shop/magie/unlockschool">
            <input type="hidden" value="<?= $magieschule->getId() ?>" name="magieschuleId">
            <input type="submit" class="unlockSchool"
                   value="Magieschule freischalten - <?= $magieschule->getKosten() ?>FP">
        </form>
    </fieldset>
<?php
endforeach;
?>