<?php
/* @var $magie \Shop\Models\Magie */
$magien = $this->magien;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$countGelernt = 0;
foreach ($magien as $magie):
    if($magie->getLearned() === true){
        $countGelernt++;
        continue;
    }
?>
<div class="magien">
    <p class="magieHeader" data-id="<?= $magie->getId() ?>">
        <span class="name">
            <?= $purifier->purify($magie->getBezeichnung()) ?>
        </span>
        <span class="kosten">
            Kosten: <?= $purifier->purify($magie->getFp()) ?> FP
        </span>
    </p>
    <div class="magieDetails" style="display: none">
        <p>
            <?= $purifier->purify($magie->getBeschreibung()) ?>
        </p>
        <div>
            <table>
                <colgroup>
                    <col width="200px">
                    <col width="100px">
                    <col width="100px">
                    <col width="100px">
                </colgroup>
                <thead>
                    <tr>
                        <th>
                            Anwendungskosten
                        </th>
                        <th>
                            Element
                        </th>
                        <th>
                            Stufe
                        </th>
                        <th>
                            Rang
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <?= $purifier->purify($magie->getPrana()) ?>
                        </td>
                        <td>
                            <?= $magie->getElement()->getBezeichnung() ?>
                        </td>
                        <td>
                            <?= $purifier->purify($magie->getStufe()) ?>
                        </td>
                        <td>
                            <?= $purifier->purify($magie->getRang()) ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="unlock">
            <button id="<?= $magie->getId() ?>" class="magie">Magie freischalten - <?= $purifier->purify($magie->getFp()) ?> FP</button>
        </div>
    </div>
</div>
<hr />
<?php 
endforeach; 
if(count($magien) === $countGelernt){
?>
<p>
    Für dich gibt es gerade keine Magien in dieser Schule.
</p>
<?php } ?>