<?php
/* @var $magie \Shop\Models\Magie */
$magien = $this->magien;
/* @var $purifier HTMLPurifier */
$purifier = $this->purifier;
$countGelernt = 0;
foreach ($magien as $magie):
    if($magie->getLearned() === true){
        $countGelernt++;
        continue;
    }
?>
<div class="col-12 p-2">
    <div class="card" style="height: 20rem; overflow: auto;">
        <div class="card-body">
            <div class="row justify-content-between">
                <div class="col-9">
                    <div class="card-title fs-4">
                        <?= $purifier->purify($magie->getBezeichnung()) ?>
                    </div>
                </div>
                <div class="col-3">
                    <button id="<?= $magie->getId() ?>" class="magie btn btn-primary">
                        Lernen - <?= $purifier->purify($magie->getFp()) ?> FP
                    </button>
                </div>
            </div>
            <div class="row">
                <div class="col-4 col-lg-2">
                    Rang: <span class="fw-bold"><?= $purifier->purify($magie->getRang()) ?></span>
                </div>
                <div class="col-8 col-lg-4">
                    Anwendungskosten: <span class="fw-bold"><?= $purifier->purify($magie->getPrana()) ?></span>
                </div>
                <div class="col-4 col-lg-3">
                    Element: <span class="fw-bold"><?= $purifier->purify($magie->getElement()->getBezeichnung()) ?></span>
                </div>
                <div class="col-4 col-lg-3">
                    Stufe: <span class="fw-bold"><?= $purifier->purify($magie->getStufe()) ?></span>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="m-1 text-muted">
                        <?= $purifier->purify($magie->getBeschreibung()) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php 
endforeach; 
if(count($magien) === $countGelernt){
?>
<p>
    Für dich gibt es gerade keine Magien in dieser Schule.
</p>
<?php } ?>